// CORE-01, CORE-02, CORE-03, CORE-04: this shell uses independent issue modules, never the old review screens.
function renderReviewPage() {
  $("#topEyebrow").textContent="REVIEW";
  const open=state.issues.filter(issue=>issue.status==="open"),selected=state.issues.find(issue=>issue.id===state.selectedIssue)||open[0]||state.issues[0];if(selected)state.selectedIssue=selected.id;
  const filter=state.reviewKind || "all",query=(state.reviewSearch || "").toLowerCase(),visible=state.issues.filter(issue=>(filter==="all"||issue.reviewType===filter)&&(issue.displayColumn || issue.column).toLowerCase().includes(query));
  state.reviewQueueExpanded ||= {};
  function list(issues,key) { // CORE-10, CORE-11, CORE-58, CORE-60
    const columns=["All columns",...state.headers],ordered=[...issues].sort((a,b)=>columns.indexOf(a.displayColumn || a.column)-columns.indexOf(b.displayColumn || b.column)||ReviewCore.order.indexOf(a.reviewType)-ReviewCore.order.indexOf(b.reviewType)),groups=new Map();
    for(const issue of state.reviewQueueExpanded[key]?ordered:ordered.slice(0,200)) {const column=issue.displayColumn || issue.column;if(!groups.has(column))groups.set(column,[]);groups.get(column).push(issue);}
    return [...groups].map(([column,items])=>`<section class="review-issue-column" data-ui="review.issues.column" data-column="${escapeHtml(column)}"><h3>${escapeHtml(column)}</h3>${items.map(issue=>{const module=ReviewCore.moduleFor(issue),count=module.queueCount?module.queueCount(issue):module.count?module.count(issue):reviewRows(issue).length,status=issue.status==="open"?"open":issue.status==="valid"?"accepted":"fixed";return `<button id="reviewIssue${issue.id}" class="review-issue ${selected?.id===issue.id?"active":""}" data-ui="review.issues.item" data-review-issue="${issue.id}" data-column="${escapeHtml(issue.column)}" data-issue="${issue.reviewType || "manual"}" aria-pressed="${selected?.id===issue.id}"><i class="review-issue-dot ${status}" aria-label="${status}"></i><span>${escapeHtml(issue.reviewType==="missing"&&issue.status==="open"?"Missing candidates":ReviewPageEngine.labels[issue.reviewType] || issue.type)}</span><b title="${escapeHtml(module.queueCountLabel?module.queueCountLabel(issue):ReviewCore.count(count,module.unit || "cells"))}">${count.toLocaleString()}</b></button>`;}).join("")}</section>`).join("")+(ordered.length>200&&!state.reviewQueueExpanded[key]?`<button class="text-button" data-queue-show-all="${key}">Show all ${ordered.length} issues</button>`:"");
  }
  // CORE-12, CORE-13: type/column filters and a collapsed, separately bounded resolved list.
  screen.innerHTML=`<div class="review-page"><aside class="review-issues" data-ui="review.issues"><div class="review-issues-heading"><h2>Issues</h2><span>${open.length} open</span></div><div class="review-issues-filter" data-ui="review.issues.filter"><select id="reviewTypeFilter" aria-label="Filter issue type"><option value="all">All issue types</option>${Object.entries(ReviewPageEngine.labels).map(([key,label])=>`<option value="${key}" ${filter===key?"selected":""}>${label}</option>`).join("")}</select><input id="reviewColumnSearch" type="search" aria-label="Search column name" placeholder="Search column name" value="${escapeHtml(state.reviewSearch || "")}"></div><div class="review-issue-list">${list(visible.filter(issue=>issue.status==="open"),"open") || '<p class="review-empty-copy">No matching open issues.</p>'}<details class="review-resolved" data-ui="review.issues.done"><summary>Resolved (${visible.filter(issue=>issue.status!=="open").length})</summary>${list(visible.filter(issue=>issue.status!=="open"),"resolved")}</details></div></aside><main class="review-main" data-ui="review.main">${selected?reviewIssueHtml(selected):'<h1>No findings</h1><p>The current checks found no issues to review.</p>'}</main></div>`;
  $("#reviewTypeFilter").onchange=event=>{state.reviewKind=event.target.value;renderPreservingReviewFocus();};$("#reviewColumnSearch").oninput=event=>{state.reviewSearch=event.target.value;renderPreservingReviewFocus();};
  document.querySelectorAll("[data-review-issue]").forEach(button=>button.onclick=()=>ReviewCore.select(Number(button.dataset.reviewIssue)));
  document.querySelectorAll("[data-queue-show-all]").forEach(button=>button.onclick=()=>{state.reviewQueueExpanded[button.dataset.queueShowAll]=true;renderPreservingReviewFocus();});
  // CORE-20: on narrow screens, issue browsing is available without pushing the active task below a second dashboard.
  const panel=document.querySelector(".review-issues");
  if(panel){
    const disclosure=document.createElement("details"),content=document.createElement("div");disclosure.className="review-queue-disclosure";content.className="review-queue-content";
    disclosure.innerHTML=`<summary>Browse issues <span>${open.length} open</span></summary>`;disclosure.open=innerWidth>900||Boolean(state.reviewQueueOpen);
    content.append(panel.querySelector(".review-issues-filter"),panel.querySelector(".review-issue-list"));disclosure.append(content);panel.append(disclosure);
    disclosure.addEventListener("toggle",()=>{if(disclosure.isConnected&&innerWidth<=900)state.reviewQueueOpen=disclosure.open;});
  }
  // CORE-27, CORE-37: actions have their own layout space; evidence scrolls without hiding or covering Apply/Undo.
  const task=document.querySelector(".review-main"),footer=task?.querySelector(".review-fix-footer,.review-review-footer");
  if(footer)task.append(footer);
  if(selected?.status==="open"&&!ReviewCore.exploreScope(selected).length){const help=document.createElement("p");help.id="reviewTabHelp";help.className="review-tab-help";help.textContent="Select at least one value in Explore to enable Fix.";task.querySelector(".review-tabs").after(help);document.getElementById("reviewTab-fix").setAttribute("aria-describedby",help.id);}
  if(selected)ReviewCore.bindShared(selected);
}
function reviewIssueHtml(issue) { // CORE-14, CORE-15, CORE-16, CORE-20, CORE-49, CORE-61, CORE-62
  const session=ReviewCore.data(issue),module=ReviewCore.moduleFor(issue);module.init?.(issue,session);
  const rows=ReviewCore.exploreScope(issue),count=module.count?module.count(issue):reviewRows(issue).length,unit=module.unit || "cells",decision=state.changes.find(change=>change.issue.id===issue.id),countLabel=module.countLabel?module.countLabel(issue):unit==="percent"?`${count}% ${issue.unit?.includes("empty")?"empty":"one value"}`:ReviewCore.count(count,unit);
  return `<header class="review-issue-header" data-ui="review.issue-header"><div><h1>${escapeHtml(issue.displayColumn || issue.column)}</h1><p>${escapeHtml(ReviewPageEngine.labels[issue.reviewType] || issue.type)} · ${escapeHtml(countLabel)}</p></div>${issue.status==="open"?'<button class="text-button" id="reviewAccept" data-ui="review.issue-header.accept">Accept as is</button>':'<span class="review-resolved-label">Reviewed</span>'}</header><nav class="review-tabs" data-ui="review.tabs" role="tablist" aria-label="Issue review">${["explore","fix","review"].map(tab=>{const disabled=tab==="fix"&&!rows.length||tab==="review"&&!decision,reason=tab==="fix"?"Lock at least one item in Explore":"Apply a fix to see changes";return `<button id="reviewTab-${tab}" data-review-tab="${tab}" role="tab" aria-selected="${session.tab===tab}" aria-controls="reviewTabContent" tabindex="${session.tab===tab?0:-1}" ${disabled?`disabled title="${reason}"`:""}>${tab[0].toUpperCase()+tab.slice(1)}</button>`;}).join("")}</nav>${session.aiUnavailableByConfig&&!session.aiRequested?ReviewCore.aiStatus(issue):""}<section id="reviewTabContent" class="review-tab-content ${session.tab}" role="tabpanel" aria-labelledby="reviewTab-${session.tab}">${session.tab==="explore"?module.renderExplore(issue,session):session.tab==="fix"?ReviewCore.fixHtml(issue):ReviewCore.reviewHtml(issue)}</section>`;
}
// CORE-19: shortcuts never intercept value, note, instruction, or content editing.
document.addEventListener("keydown",event=>{
  if(state.screen!=="issues"||event.altKey||event.ctrlKey||event.metaKey||event.target.closest("input,textarea,select,[contenteditable=true],.review-row-panel"))return;
  const issue=ReviewCore.current();if(!issue)return;
  if(["1","2","3"].includes(event.key)){event.preventDefault();ReviewCore.switchTab(issue,["explore","fix","review"][Number(event.key)-1]);}
  if(["j","k"].includes(event.key)){event.preventDefault();const open=state.issues.filter(item=>item.status==="open"),index=open.findIndex(item=>item.id===issue.id),next=open[(index+(event.key==="j"?1:open.length-1)+open.length)%open.length];if(next)ReviewCore.select(next.id);}
  if(["ArrowLeft","ArrowRight"].includes(event.key)&&event.target.matches("[data-review-tab]")){event.preventDefault();const tabs=[...document.querySelectorAll("[data-review-tab]:not(:disabled)")],index=tabs.indexOf(event.target),next=tabs[(index+(event.key==="ArrowRight"?1:tabs.length-1))%tabs.length];ReviewCore.switchTab(issue,next.dataset.reviewTab);document.getElementById(next.id)?.focus();}
});
document.addEventListener("click",event=>{document.querySelectorAll(".priority-add[open]").forEach(picker=>{if(!picker.contains(event.target))picker.open=false;});});
// CORE-20, CORE-48: resizing recomposites only display geometry, keeping the preview and scope.
let reviewResizeTimer,reviewViewportWidth=window.innerWidth;
window.addEventListener("resize",()=>{if(window.innerWidth===reviewViewportWidth)return;reviewViewportWidth=window.innerWidth;clearTimeout(reviewResizeTimer);reviewResizeTimer=setTimeout(()=>{if(typeof state!=="undefined"&&state.screen==="issues"&&state.headers.length)renderPreservingReviewFocus();},100);});
