// CORE-40…47: shared, traceable chart primitives; no statistical treatment lives here.
var ReviewCharts = (() => {
  const colors = {before:"#E07B39",after:"#2E6BD9",neutral:"#9AA3AE"};
  const chartWidth = () => typeof window!=="undefined" && window.innerWidth<=620 ? Math.max(280,window.innerWidth-56) : 720;
  const numeric = (rows,column,excluded = new Set()) => rows.flatMap(row => { if (excluded.has(row._row) || !String(row[column] ?? "").trim()) return []; try { return [CleaningEngine.parseNumber(row[column],columnPolicy(column))]; } catch { return []; } });
  function skew(values) { if (values.length < 3) return 0; const mean = CleaningEngine.stats(values).mean, variance = values.reduce((sum,value) => sum+(value-mean)**2,0)/values.length; return variance ? values.reduce((sum,value) => sum+(value-mean)**3,0)/values.length/variance**1.5 : 0; }
  function histogramChart(column,beforeRows,afterRows,options = {}) {
    const before = numeric(beforeRows,column,options.missingBefore || new Set()), after = numeric(afterRows,column,options.missingAfter || new Set());
    if (!before.length && !after.length) return '<p class="review-empty-copy">No present numerical values are available for a distribution.</p>';
    const log = options.log ?? skew(before.length ? before : after) > 2, signed = before.concat(after).some(value => value < 0), transform = value => !log ? value : signed ? Math.sign(value)*Math.log1p(Math.abs(value)) : Math.log1p(Math.max(0,value)), inverse = value => !log ? value : signed ? Math.sign(value)*Math.expm1(Math.abs(value)) : Math.expm1(value);
    const sets = [before,after].map(values => values.map(transform)), distribution = AnalysisEngine.histogram(sets,20), bins = distribution.bins, canvasWidth=chartWidth(), left = 38, width = canvasWidth-76, bottom = 142, height = 108;
    // CORE-41, CORE-44: percentages use each series' own population; filled values stack in after.
    const filled = (options.patches || []).filter(patch => patch.column === column && !options.missingAfter?.has(patch.rowId)).map(patch => Number(patch.after)).filter(Number.isFinite), fillHist = histogram(filled.map(transform),distribution.min,distribution.max,bins), rates = distribution.sets.map((set,index) => set.counts.map(count => count/Math.max(1,sets[index].length))), ymax = options.ymax || Math.max(.01,...rates.flat()), x = value => left+Math.max(0,Math.min(1,(transform(value)-distribution.min)/(distribution.max-distribution.min || 1)))*width;
    // CORE-40…45: responsive geometry changes pixels, never the shared bins, rates, or medians.
    const binWidth=width/bins,afterOffset=Math.min(6,binWidth*.2),afterWidth=Math.max(2,binWidth*.55);
    const bars = distribution.sets[0].counts.map((count,index) => { const oldHeight = rates[0][index]/ymax*height, nextHeight = rates[1][index]/ymax*height, filledHeight = fillHist.counts[index]/Math.max(1,after.length)/ymax*height; return `<rect x="${left+index*binWidth}" y="${bottom-oldHeight}" width="${Math.max(2,binWidth-3)}" height="${oldHeight}" fill="${colors.before}" opacity=".65"/><rect x="${left+index*binWidth+afterOffset}" y="${bottom-nextHeight}" width="${afterWidth}" height="${nextHeight}" fill="${colors.after}"/><rect x="${left+index*binWidth+afterOffset}" y="${bottom-filledHeight}" width="${afterWidth}" height="${filledHeight}" fill="${colors.before}" stroke="white" stroke-width=".5"><title>Before ${count}; after ${distribution.sets[1].counts[index]}; filled ${fillHist.counts[index]}</title></rect>`; }).join("");
    const medians = [CleaningEngine.stats(before).median,CleaningEngine.stats(after).median], marks = medians.map((value,index) => value === null ? "" : `<line x1="${x(value)}" x2="${x(value)}" y1="24" y2="${bottom}" stroke="${index ? colors.after : colors.before}" stroke-width="1"/><text x="${x(value)}" y="${index ? 21 : 10}" text-anchor="middle" fill="${index ? colors.after : colors.before}">${index ? "After" : "Before"} median ${ReviewCore.format(value,column)}</text>`).join("");
    // INV-E-03, INV-R-02: a visible bounded validity band shares the distribution's axes.
    const range=options.range, low=range?.min!==undefined && range.min!=="" ? x(Number(range.min)) : left, high=range?.max!==undefined && range.max!=="" ? x(Number(range.max)) : left+width;
    const validBand=range ? `<rect x="${low}" y="28" width="${Math.max(0,high-low)}" height="${bottom-28}" fill="${colors.after}" opacity=".09"/><text x="${low+3}" y="38">Valid range</text>` : "";
    const locations = [...new Set(filled)].sort((a,b)=>a-b), landing = locations.length <= 4 ? locations.map(value => ReviewCore.format(value,column)).join(" / ") : `${ReviewCore.format(CleaningEngine.stats(filled).min,column)}–${ReviewCore.format(CleaningEngine.stats(filled).max,column)}`, takeaway = options.title || (filled.length ? `+${filled.length.toLocaleString()} filled at ${landing}; median ${ReviewCore.format(medians[0],column)} → ${ReviewCore.format(medians[1],column)}` : `Median ${ReviewCore.format(medians[0],column)} → ${ReviewCore.format(medians[1],column)}`);
    return `<figure class="review-chart ${options.compact ? "compact" : ""}"><figcaption>${escapeHtml(takeaway)}</figcaption><div class="review-chart-legend"><span class="before">Before ${before.length.toLocaleString()}</span><span class="after">After ${after.length.toLocaleString()}</span>${filled.length ? `<span class="filled">+${filled.length.toLocaleString()} filled</span>` : ""}<span>% of present values${log ? " · log scale" : ""}</span></div><svg viewBox="0 0 ${canvasWidth} 169" role="img" aria-label="${escapeHtml(takeaway)}"><text x="2" y="35">${Math.round(ymax*100)}%</text>${validBand}${bars}${marks}<text x="${left}" y="162">${ReviewCore.format(inverse(distribution.min),column)}</text><text x="${left+width}" y="162" text-anchor="end">${ReviewCore.format(inverse(distribution.max),column)}</text></svg><p class="review-chart-edges">◂ ${distribution.sets[0].below} → ${distribution.sets[1].below} below · ${distribution.sets[0].above} → ${distribution.sets[1].above} above ▸ · 1st–99th percentile</p></figure>`;
  }
  function categoryChart(column,before,after,options = {}) {
    const count = rows => ReviewPageEngine.frequencies(rows,column), value = group => options.metric ? ReviewCore.total(group.rows,options.metric) : group.rows.length, old = new Map(count(before).map(group=>[group.value,value(group)])), next = new Map(count(after).map(group=>[group.value,value(group)])), keys = [...new Set([...old.keys(),...next.keys()])], changed = keys.filter(key=>(old.get(key)||0)!==(next.get(key)||0)), shown = options.keys || (options.changedOnly ? changed : keys.sort((a,b)=>(next.get(b)||0)-(next.get(a)||0)).slice(0,10));
    if (!options.changedOnly && (old.has("") || next.has("")) && !shown.includes("")) shown.push("");
    if (!shown.length) return '<p class="review-empty-copy">No category totals change.</p>';
    const max = Math.max(1,...shown.flatMap(key=>[Math.abs(old.get(key)||0),Math.abs(next.get(key)||0)]));
    return `<figure class="review-chart"><figcaption>${escapeHtml(options.title || `${changed.length} labels change; ${keys.length-changed.length} others unchanged`)}</figcaption><div class="review-chart-legend"><span class="before">Before</span><span class="after">After</span>${options.metric ? `<span>${escapeHtml(options.metric)}</span>` : ""}</div><div class="review-category-bars">${shown.map(key=>`<div class="${changed.includes(key) ? "changed" : "unchanged"}"><span>${escapeHtml(key || "(blank)")}</span><div><i class="before" style="width:${Math.abs(old.get(key)||0)/max*100}%"></i><i class="after" style="width:${Math.abs(next.get(key)||0)/max*100}%"></i></div><b>${options.metric ? ReviewCore.money(old.get(key)||0,options.metric) : old.get(key)||0} → ${options.metric ? ReviewCore.money(next.get(key)||0,options.metric) : next.get(key)||0}</b></div>`).join("")}</div></figure>`;
  }
  function timeline(column,before,after,range) { // INV-E-03, INV-R-02: date positions share one axis and a shaded valid interval.
    const parse=rows=>rows.flatMap(row=>{try{return [{row,date:ReviewPageEngine.dateValue(row[column],reviewDateFormats()[JSON.stringify([row._row,column,row[column]])] || columnPolicy(column).dateFormat)}];}catch{return [];}}), sets=[parse(before),parse(after)], values=sets.flat().map(entry=>Date.parse(entry.date));
    if (!values.length) return '<p class="review-empty-copy">No valid calendar dates are available for a timeline.</p>';
    const min=Math.min(...values),max=Math.max(...values),x=value=>35+Math.max(0,Math.min(1,(Date.parse(value)-min)/(max-min||1)))*635, low=range.min ? x(range.min) : 35, high=range.max ? x(range.max) : 670;
    return `<figure class="review-chart"><figcaption>Valid dates run from ${escapeHtml(range.min || "the first observed date")} to ${escapeHtml(range.max || "the last observed date")}</figcaption><div class="review-chart-legend"><span class="before">Before ${sets[0].length}</span><span class="after">After ${sets[1].length}</span></div><svg viewBox="0 0 720 130" role="img" aria-label="Date timeline with the valid interval shaded"><rect x="${low}" y="20" width="${Math.max(0,high-low)}" height="80" fill="${colors.after}" opacity=".09"/>${sets.map((entries,index)=>entries.map(entry=>`<circle cx="${x(entry.date)}" cy="${index ? 75 : 45}" r="3" fill="${index ? colors.after : colors.before}"><title>Row ${entry.row._row}: ${entry.date}</title></circle>`).join("")).join("")}<text x="35" y="122">${new Date(min).toISOString().slice(0,10)}</text><text x="670" y="122" text-anchor="end">${new Date(max).toISOString().slice(0,10)}</text></svg></figure>`;
  }
  return {colors,numeric,skew,histogram:histogramChart,categories:categoryChart,timeline};
})();
