// CORE-10…20, CORE-60…62: the page owns navigation only; issue modules own their evidence.
function renderReviewPage() {
  $("#topEyebrow").textContent="REVIEW";
  const open=state.issues.filter(issue=>issue.status==="open"), selected=state.issues.find(issue=>issue.id===state.selectedIssue)||open[0]||state.issues[0];if(selected)state.selectedIssue=selected.id;
  const filter=state.reviewKind||"all",query=(state.reviewSearch||"").toLowerCase(), visible=state.issues.filter(issue=>(filter==="all"||issue.reviewType===filter)&&(issue.displayColumn||issue.column).toLowerCase().includes(query));
  const list=issues=>{const columns=["All columns",...state.headers], ordered=issues.sort((a,b)=>columns.indexOf(a.displayColumn||a.column)-columns.indexOf(b.displayColumn||b.column)||ReviewCore.order.indexOf(a.reviewType)-ReviewCore.order.indexOf(b.reviewType)), groups=new Map();ordered.forEach(issue=>{const column=issue.displayColumn||issue.column;if(!groups.has(column))groups.set(column,[]);groups.get(column).push(issue);});return [...groups].map(([column,items])=>`<section class="review-issue-column" data-ui="review.issues.column" data-column="${escapeHtml(column)}"><h3>${escapeHtml(column)}</h3>${items.map(issue=>{const module=ReviewCore.moduleFor(issue),count=module.count?module.count(issue):reviewRows(issue).length,status=issue.status==="open"?"open":issue.status==="valid"?"accepted":"fixed";return `<button id="reviewIssue${issue.id}" class="review-issue ${selected?.id===issue.id?"active":""}" data-ui="review.issues.item" data-review-issue="${issue.id}" data-column="${escapeHtml(issue.column)}" data-issue="${issue.reviewType}" aria-pressed="${selected?.id===issue.id}"><i class="review-issue-dot ${status}" aria-label="${status}"></i><span>${escapeHtml(ReviewPageEngine.labels[issue.reviewType]||issue.type)}</span><b>${count.toLocaleString()}</b></button>`;}).join("")}</section>`).join("");};
  screen.innerHTML=`<div class="review-page"><aside class="review-issues" data-ui="review.issues"><div class="review-issues-heading"><h2>Issues</h2><span>${open.length} open</span></div><div class="review-issues-filter" data-ui="review.issues.filter"><select id="reviewTypeFilter" aria-label="Filter issue type"><option value="all">All issue types</option>${Object.entries(ReviewPageEngine.labels).map(([key,label])=>`<option value="${key}" ${filter===key?"selected":""}>${label}</option>`).join("")}</select><input id="reviewColumnSearch" type="search" aria-label="Search column name" placeholder="Search column name" value="${escapeHtml(state.reviewSearch||"")}"></div><div class="review-issue-list">${list(visible.filter(issue=>issue.status==="open"))||'<p class="review-empty-copy">No matching open issues.</p>'}<details class="review-resolved" data-ui="review.issues.done"><summary>Resolved (${visible.filter(issue=>issue.status!=="open").length})</summary>${list(visible.filter(issue=>issue.status!=="open"))}</details></div></aside><main class="review-main" data-ui="review.main">${selected?reviewIssueHtml(selected):'<h1>No findings</h1><p>The current checks found no issues to review.</p>'}</main></div>`;
  $("#reviewTypeFilter").onchange=event=>{state.reviewKind=event.target.value;renderPreservingReviewFocus();};$("#reviewColumnSearch").oninput=event=>{state.reviewSearch=event.target.value;renderPreservingReviewFocus();};document.querySelectorAll("[data-review-issue]").forEach(button=>button.onclick=()=>ReviewCore.select(Number(button.dataset.reviewIssue)));if(selected)ReviewCore.bindShared(selected);
}
function reviewIssueHtml(issue) {
  const session=ReviewCore.data(issue),module=ReviewCore.moduleFor(issue);module.init?.(issue,session);const rows=ReviewCore.affected(issue),count=module.count?module.count(issue):reviewRows(issue).length,unit=module.unit||"cells",decision=state.changes.find(change=>change.issue.id===issue.id);
  const countLabel=unit==="percent" ? `${count}% ${issue.unit?.includes("empty")?"empty":"one value"}` : ReviewCore.count(count,unit);
  return `<header class="review-issue-header" data-ui="review.issue-header"><div><h1>${escapeHtml(issue.displayColumn||issue.column)}</h1><p>${escapeHtml(ReviewPageEngine.labels[issue.reviewType]||issue.type)} · ${escapeHtml(countLabel)}</p></div>${issue.status==="open"?'<button class="text-button" id="reviewAccept" data-ui="review.issue-header.accept">Accept as is</button>':'<span class="review-resolved-label">Reviewed</span>'}</header><nav class="review-tabs" data-ui="review.tabs" role="tablist" aria-label="Issue review">${["explore","fix","review"].map(tab=>{const disabled=tab==="fix"&&!rows.length||tab==="review"&&!decision,reason=tab==="fix"?"Lock at least one item in Explore":"Apply a fix to see changes";return `<button id="reviewTab-${tab}" data-review-tab="${tab}" role="tab" aria-selected="${session.tab===tab}" aria-controls="reviewTabContent" tabindex="${session.tab===tab?0:-1}" ${disabled?`disabled title="${reason}"`:""}>${tab[0].toUpperCase()+tab.slice(1)}</button>`;}).join("")}</nav><section id="reviewTabContent" class="review-tab-content ${session.tab}" role="tabpanel" aria-labelledby="reviewTab-${session.tab}">${session.tab==="explore"?module.renderExplore(issue,session):session.tab==="fix"?ReviewCore.fixHtml(issue):ReviewCore.reviewHtml(issue)}</section>`;
}
// CORE-19: shortcuts never intercept editing a value, note, or instruction.
document.addEventListener("keydown",event=>{
  if(state.screen!=="issues"||event.altKey||event.ctrlKey||event.metaKey||event.target.closest("input,textarea,select,[contenteditable=true]"))return;
  const issue=ReviewCore.current();if(!issue)return;
  if(["1","2","3"].includes(event.key)){event.preventDefault();ReviewCore.switchTab(issue,["explore","fix","review"][Number(event.key)-1]);}
  if(["j","k"].includes(event.key)){event.preventDefault();const open=state.issues.filter(item=>item.status==="open"),index=open.findIndex(item=>item.id===issue.id),next=open[(index+(event.key==="j"?1:open.length-1)+open.length)%open.length];if(next)ReviewCore.select(next.id);}
  if(["ArrowLeft","ArrowRight"].includes(event.key)&&event.target.matches("[data-review-tab]")){event.preventDefault();const tabs=[...document.querySelectorAll("[data-review-tab]:not(:disabled)")],index=tabs.indexOf(event.target),next=tabs[(index+(event.key==="ArrowRight"?1:tabs.length-1))%tabs.length];ReviewCore.switchTab(issue,next.dataset.reviewTab);document.getElementById(next.id)?.focus();}
});
// CORE-20, CORE-48: recomposite measurement lettering after a viewport resize; keep the preview and scope.
let reviewResizeTimer;
window.addEventListener("resize",()=>{
  clearTimeout(reviewResizeTimer);
  reviewResizeTimer=setTimeout(()=>{if(typeof state!=="undefined" && state.screen==="issues" && state.headers.length)renderPreservingReviewFocus();},100);
});
