// CONST-D-01, CONST-D-02: inspect the rare informative rows before deciding to remove a column.
ReviewModules.constant = (() => {
  function facts(rows,column){const locked=new Set(state.reviewPage?.[`${column}:missing`]?.locked||[""]),values=ReviewPageEngine.frequencies(rows,column),missing=rows.filter(row=>locked.has(String(row[column]??"").trim()?String(row[column]):"")),ids=new Set(missing.map(row=>row._row)),present=rows.filter(row=>!ids.has(row._row)),top=ReviewPageEngine.frequencies(present,column)[0],empty=missing.length/Math.max(1,rows.length)>=.95,constant=top?.rows.length/Math.max(1,present.length)>=.99;return {values,missing,present,top,empty,constant,share:empty?missing.length/Math.max(1,rows.length)*100:(top?.rows.length||0)/Math.max(1,present.length)*100};}
  function detect(dataset){return dataset.headers.flatMap(column=>{const info=facts(dataset.rows,column);return info.empty||info.constant?[{column,reviewType:"constant",type:"Empty or constant column",label:"Empty or constant column",rows:dataset.rows,recommendation:"manual",severity:"medium",summary:"The column carries almost no information.",status:"open",unit:info.empty?"% empty":"% one value"}]:[];});}
  function lockedRows(issue){return state.rows;}
  function count(issue){return Number(facts(state.rows,issue.column).share.toFixed(1));}
  function countLabel(issue){const info=facts(state.rows,issue.column);return `${info.share.toFixed(1)}% ${info.empty?"empty":"one value"}`;}
  function getFixOptions(){return [{key:"keep",label:"Keep column",risk:"Doesn't change values",compute:()=>({operation:"retain",interpretation:"legitimate"})},{key:"drop-column",label:"Remove column",risk:"Changes structure",disabled:state.headers.length<2?"Keep at least one column":"",compute:()=>({operation:"dropColumn"})}];}
  function reminder(issue){return `Fixing: the almost empty or constant ${issue.column} column`;}
  function consequence(issue,session,preview,option){ // CONST-F-01
    const filled=state.rows.filter(row=>String(row[issue.column]??"").trim()).length,rules=[...state.ruleConfig.schema,...state.ruleConfig.metrics,...state.ruleConfig.kpis,...(state.ruleConfig.relations||[])].filter(rule=>[rule.column,rule.target,rule.left,rule.right,rule.metric,rule.denominator,rule.groupBy,...(rule.terms||[])].includes(issue.column)),fixes=state.issues.filter(other=>other.id!==issue.id&&other.status==="open").filter(other=>{const draft=state.reviewDrafts?.[other.id];return draft&&[...(draft.groupColumns||[]),...(draft.similar?.columns||[]),draft.orderColumn,draft.scope?.mode==="condition"?draft.scope.column:null].includes(issue.column);});
    return {sentence:option.key==="keep"?`Keeps ${issue.column} and all ${filled} non-empty values.`:`Removes 1 column; ${filled} non-empty values will be lost from the working dataset.`,figures:[{label:"Columns",before:state.headers.length,after:state.headers.length-(option.key==="drop-column"?1:0)}],reason:rules.length||fixes.length?`${[...rules.map(rule=>rule.name||rule.id),...fixes.map(fix=>`${fix.column} treatment preview`)].join(", ")} uses this column and must be reviewed.`:"No other configured rule, KPI or pending fix uses this column."};}
  function exploreContent(issue){ // CONST-E-01…03 / C3 + C4
    const c=ReviewComponents,info=facts(state.rows,issue.column),different=info.empty?info.present:state.rows.filter(row=>row[issue.column]!==info.top.value),context=state.headers.filter(column=>column!==issue.column).slice(0,3),columns=[{key:"row",label:"Row",numeric:true},{key:issue.column,label:issue.column},...context.map(column=>({key:column,label:column}))];
    const items=info.values.slice(0,5).map(group=>({value:group.value||"(blank)",count:group.rows.length,share:`${(group.rows.length/state.rows.length*100).toFixed(1)}%`,meta:"observed value"})),rows=different.slice(0,20).map(row=>({row:row._row,...Object.fromEntries(columns.slice(1).map(column=>[column.key,{value:row[column.key]||"(blank)",raw:true}]))}));
    return {lead:info.empty?`Should this ${info.share.toFixed(1)}% empty column be kept?`:`Should ${issue.column} be kept when ${info.share.toFixed(1)}% have the same value?`,sub:"It carries almost no information; the exceptions may still matter.",selection:c.selection(items,{total:`${state.rows.length} entries in this column`}),evidence:c.table({columns,rows,ui:"review.explore.constant.rows",empty:"Every entry has the same value."}),evidenceTitle:"Inspect the exceptions"};
  }
  function fixContent(issue,session,preview,option){return {metrics:[{label:"Columns",value:`${state.headers.length} → ${state.headers.length-preview.removedColumns.length}`}],text:option.key==="keep"?"No values change.":"The column disappears from the working table and export; Undo restores its original position."};}
  function reviewContent(issue,decision){ // CONST-R-01…02
    const impact=decision.reviewImpact,lost=decision.structure.removedColumns.length?impact.beforeRows.filter(row=>String(row[issue.column]).trim()).length:0;
    return {lead:decision.structure.removedColumns.length?`1 column removed: ${issue.column}.`:`${issue.column} kept unchanged.`,sub:`${decision.reviewSpec.label} · ${new Date(decision.createdAt).toLocaleTimeString()} · ${decision.note||"No note"}`,count:decision.rows.length,change:{metrics:[{label:"Columns",value:`${impact.beforeHeaders.length} → ${impact.afterHeaders.length}`},{label:"Values lost",value:lost}]}};
  }
  return {detect,count,countLabel,unit:"percent",lockedRows,exploreContent,fixContent,reviewContent,renderExplore:issue=>ReviewComponents.explore(issue,exploreContent(issue)),getFixOptions,reminder,consequence};
})();
