// CONST-D-01, CONST-D-02: inspect the rare informative rows before deciding to remove a column.
ReviewModules.constant = (() => {
  function facts(rows,column){const locked=new Set(state.reviewPage?.[`${column}:missing`]?.locked||[""]),values=ReviewPageEngine.frequencies(rows,column),missing=rows.filter(row=>locked.has(String(row[column]??"").trim()?String(row[column]):"")),ids=new Set(missing.map(row=>row._row)),present=rows.filter(row=>!ids.has(row._row)),top=ReviewPageEngine.frequencies(present,column)[0],empty=missing.length/Math.max(1,rows.length)>=.95,constant=top?.rows.length/Math.max(1,present.length)>=.99;return {values,missing,present,top,empty,constant,share:empty?missing.length/Math.max(1,rows.length)*100:(top?.rows.length||0)/Math.max(1,present.length)*100};}
  function detect(dataset){return dataset.headers.flatMap(column=>{const info=facts(dataset.rows,column);return info.empty||info.constant?[{column,reviewType:"constant",type:"Empty or constant column",label:"Empty or constant column",rows:dataset.rows,recommendation:"manual",severity:"medium",summary:"The column carries almost no information.",status:"open",unit:info.empty?"% empty":"% one value"}]:[];});}
  function lockedRows(issue){return state.rows;}
  function count(issue){return Number(facts(state.rows,issue.column).share.toFixed(1));}
  function countLabel(issue){const info=facts(state.rows,issue.column);return `${info.share.toFixed(1)}% ${info.empty?"empty":"one value"}`;}
  function renderExplore(issue){ // CONST-E-01, CONST-E-02, CONST-E-03
    const info=facts(state.rows,issue.column),different=info.empty?info.present:state.rows.filter(row=>row[issue.column]!==info.top.value),context=state.headers.filter(column=>column!==issue.column).slice(0,3);return `<section class="constant-explore" data-ui="review.explore.constant"><div data-ui="review.explore.constant.summary"><h2>${info.empty?`This column is ${info.share.toFixed(1)}% empty`:`${info.share.toFixed(1)}% of rows have “${escapeHtml(info.top.value)}”`}</h2><p>It carries almost no information.</p></div><div data-ui="review.explore.constant.values">${info.values.slice(0,5).map(group=>`<p><b>${escapeHtml(group.value||"(blank)")}</b> · ${group.rows.length}</p>`).join("")}</div><div class="review-table-scroll" data-ui="review.explore.constant.rows"><h3>The rows that differ</h3>${different.length?`<table><thead><tr><th>Row</th><th>${escapeHtml(issue.column)}</th>${context.map(column=>`<th>${escapeHtml(column)}</th>`).join("")}</tr></thead><tbody>${different.slice(0,20).map(row=>`<tr><td>${row._row}</td><td>${escapeHtml(row[issue.column]||"(blank)")}</td>${context.map(column=>`<td>${escapeHtml(row[column])}</td>`).join("")}</tr>`).join("")}</tbody></table>`:"<p>Every row has the same representation.</p>"}</div></section>`;}
  function getFixOptions(){return [{key:"keep",label:"Keep column",risk:"Doesn't change values",compute:()=>({operation:"retain",interpretation:"legitimate"})},{key:"drop-column",label:"Remove column",risk:"Changes structure",disabled:state.headers.length<2?"Keep at least one column":"",compute:()=>({operation:"dropColumn"})}];}
  function reminder(issue){return `Fixing: the almost empty or constant ${issue.column} column`;}
  function consequence(issue,session,preview,option){ // CONST-F-01
    const filled=state.rows.filter(row=>String(row[issue.column]??"").trim()).length,rules=[...state.ruleConfig.schema,...state.ruleConfig.metrics,...state.ruleConfig.kpis,...(state.ruleConfig.relations||[])].filter(rule=>[rule.column,rule.target,rule.left,rule.right,rule.metric,rule.denominator,rule.groupBy,...(rule.terms||[])].includes(issue.column)),fixes=state.issues.filter(other=>other.id!==issue.id&&other.status==="open").filter(other=>{const draft=state.reviewDrafts?.[other.id];return draft&&[...(draft.groupColumns||[]),...(draft.similar?.columns||[]),draft.orderColumn,draft.scope?.mode==="condition"?draft.scope.column:null].includes(issue.column);});
    return {sentence:option.key==="keep"?`Keeps ${issue.column} and all ${filled} non-empty values.`:`Removes 1 column; ${filled} non-empty values will be lost from the working dataset.`,figures:[{label:"Columns",before:state.headers.length,after:state.headers.length-(option.key==="drop-column"?1:0)}],reason:rules.length||fixes.length?`${[...rules.map(rule=>rule.name||rule.id),...fixes.map(fix=>`${fix.column} treatment preview`)].join(", ")} uses this column and must be reviewed.`:"No other configured rule, KPI or pending fix uses this column."};}
  function renderPreview(issue,session,preview,option){return `<p>${option.key==="keep"?"No values change.":`${issue.column} will disappear from the working sheet and export. Undo restores it in its original position.`}</p>`;}
  function renderReview(issue,decision){ // CONST-R-01, CONST-R-02: structure metrics, no redundant chart.
    const impact=decision.reviewImpact,lost=impact.beforeRows.filter(row=>String(row[issue.column]??"").trim()).length;return ReviewCore.metricStrip([{label:"Columns",value:`${impact.beforeHeaders.length} → ${impact.afterHeaders.length}`},{label:"Values lost",value:decision.structure.removedColumns.length?lost:0},{label:"Cells changed",value:0},{label:"Rows removed",value:0}]);}
  return {detect,count,countLabel,unit:"percent",lockedRows,renderExplore,getFixOptions,reminder,consequence,renderPreview,renderReview};
})();
