// XCOL-D-01, XCOL-D-02, XCOL-D-03, XCOL-D-04: formulas are supported only by usable input evidence.
ReviewModules["cross-column"] = (() => {
   function baseDefinitions(headers){const find=regex=>headers.find(column=>regex.test(column)),revenue=find(/^revenue(?:_|$)/i),cost=find(/^(?:cost|total_cost)(?:_|$)/i),profit=find(/^profit(?:_|$)/i),spend=find(/^spend(?:_|$)/i),clicks=find(/^clicks$/i),impressions=find(/^impressions$/i),conversions=find(/^conversions$/i),quantity=find(/^quantity$|^qty$/i),price=find(/unit_price/i),discount=find(/discount/i),roas=find(/^roas(?:_|$)/i),cpc=find(/^cpc/i),ctr=find(/^ctr|click_through_rate/i),start=find(/start.*date|order_date|admit.*date/i),end=find(/end.*date|delivery.*date|discharge.*date/i),systolic=find(/systolic/i),diastolic=find(/diastolic/i),rules=[];
     const add=(target,inputs,operation,label,factor=1)=>{if(target&&inputs.every(Boolean))rules.push({id:`auto:${target}:${operation}`,column:target,target,inputs,operation,label,factor,suggested:true});};add(profit,[revenue,cost],"difference",`${profit} = ${revenue} − ${cost}`);add(revenue,[quantity,price,discount],"discount-product",`${revenue} = ${quantity} × ${price} × (1 − ${discount}/100)`);add(roas,[revenue,spend],"ratio",`${roas} = ${revenue} ÷ ${spend}`);add(cpc,[spend,clicks],"ratio",`${cpc} = ${spend} ÷ ${clicks}`);add(ctr,[clicks,impressions],"ratio",`${ctr} = ${clicks} ÷ ${impressions}`,/pct|percent/i.test(ctr)?100:1);add(clicks,[clicks,impressions],"less-equal",`${clicks} ≤ ${impressions}`);add(conversions,[conversions,clicks],"less-equal",`${conversions} ≤ ${clicks}`);add(end,[start,end],"date-order",`${end} ≥ ${start}`);add(diastolic,[diastolic,systolic],"less",`${diastolic} < ${systolic}`);return rules;}
   function definitions(headers){const rules=baseDefinitions(headers).filter(rule=>rule.operation!=="date-order");for(const [a,b] of [[/start.*date|date.*start/i,/end.*date|date.*end/i],[/order.*date|date.*order/i,/deliver.*date|date.*deliver/i],[/admi(?:t|ssion).*date|date.*admi(?:t|ssion)/i,/discharge.*date|date.*discharge/i]]){const start=headers.find(column=>a.test(column)),end=headers.find(column=>b.test(column));if(start&&end)rules.push({id:`auto:${end}:date-order`,column:end,target:end,inputs:[start,end],operation:"date-order",label:`${end} ≥ ${start}`,factor:1,suggested:true});}return rules;}
   function expected(row,rule){
     if (rule.operation === "relation") {
       const problem=relationProblem(row,rule.relation);
       if (/can’t|cannot|missing|unreadable/i.test(problem || "") && rule.relation.kind!=="requiredIf") throw new Error(problem);
       const actual=row[rule.column], value=row[rule.relation.right] || "Required value", valid=!problem;
       return {value,actual,difference:valid?0:1,valid};
     }
     const missingInput=rule.inputs.find(column=>observationState(row,column)!=="present");if(missingInput)throw new Error(`${missingInput} missing or unavailable`);
     if(rule.operation==="date-order"){
       const date=column=>ReviewPageEngine.dateValue(row[column],reviewDateFormats()[JSON.stringify([row._row,column,row[column]])] || columnPolicy(column).dateFormat),start=date(rule.inputs[0]),end=date(rule.inputs[1]);
       return {value:start,actual:end,difference:(Date.parse(end)-Date.parse(start))/86400000,valid:end>=start};
     }
     const values=rule.inputs.map(column=>CleaningEngine.parseNumber(row[column],columnPolicy(column)));
     if(observationState(row,rule.column)!=="present")throw new Error(`${rule.column} missing or unavailable`);
     const actual=CleaningEngine.parseNumber(row[rule.column],columnPolicy(rule.column));let value;
     if(rule.operation==="difference")value=values[0]-values[1];else if(rule.operation==="product")value=values[0]*values[1];else if(rule.operation==="sum")value=values.reduce((sum,value)=>sum+value,0);else if(rule.operation==="discount-product")value=values[0]*values[1]*(1-values[2]/100);else if(rule.operation==="ratio"){if(!values[1])throw new Error("zero denominator");value=values[0]/values[1];}else value=values[1];
     if (!["less","less-equal","discount-product"].includes(rule.operation)) value*=rule.factor??1;
     if(rule.decimals!==undefined)value=Number(value.toFixed(rule.decimals));
     if(!Number.isFinite(value))throw new Error("Calculation does not produce a finite target value");
     const difference=actual-value,valid=rule.operation==="less-equal"?actual<=value:rule.operation==="less"?actual<value:Math.abs(difference)<=rule.tolerance;
     return {value,actual,difference,valid};
   }
  function measureRows(rows,rule){const entries=[],blocked=[];for(const row of rows){try{entries.push({row,...expected(row,rule)});}catch(error){blocked.push({row,reason:error.message});}}return {entries,blocked,violations:entries.filter(entry=>!entry.valid).sort((a,b)=>Math.abs(b.difference)-Math.abs(a.difference))};}
   function detect(dataset){
     const removed=new Set(state.changes.map(change=>change.treatment?.removedRule).filter(Boolean));
     const declared=state.ruleConfig.metrics.map(rule=>({...rule,column:rule.target,inputs:rule.terms?.length?rule.terms:[rule.left,rule.right],label:metricFormula(rule),suggested:false}));
     const relations=(state.ruleConfig.relations || []).map(rule=>({id:rule.id,column:rule.column,inputs:rule.kind==="requiredIf"?[rule.left,rule.column]:[rule.left,rule.right],operation:"relation",relation:rule,label:rule.name || `${rule.left} ${rule.operator} ${rule.right}`,suggested:false,tolerance:0}));
     const rules=definitions(dataset.headers).filter(rule=>!declared.some(other=>other.column===rule.column&&other.operation===rule.operation)).concat(declared,relations).filter(rule=>!removed.has(rule.id));
     return rules.flatMap(rule=>{const policy=ReviewCore.precision(rule.column),median=CleaningEngine.stats(ReviewCharts.numeric(dataset.rows,rule.column).map(Math.abs)).median;rule.tolerance=rule.tolerance??Math.max((median||0)*.01,10**-policy);const overrides=state.reviewPage?.[`${rule.column}:cross-column:${rule.id}`]?.tolerance;if(Number.isFinite(overrides)&&overrides>=0)rule.tolerance=overrides;const measured=measureRows(dataset.rows,rule);if(rule.suggested&&measured.entries.filter(entry=>entry.valid).length/Math.max(1,measured.entries.length)<.8)return [];if(!measured.violations.length)return [];return [{column:rule.column,reviewType:"cross-column",type:"Conflicting columns",label:"Conflicting columns",rows:measured.violations.map(entry=>entry.row),recommendation:"manual",severity:"medium",status:"open",summary:rule.label,crossRule:rule,ruleId:rule.id,unit:"rows"}];});
   }
  function init(issue,session){session.tolerance??=issue.crossRule.tolerance;if(session.locked===null)session.locked=measureRows(state.rows,issue.crossRule).violations.map(entry=>String(entry.row._row));}
  function lockedRows(issue,session){init(issue,session);const ids=new Set(session.locked.map(Number));return measureRows(state.rows,{...issue.crossRule,tolerance:session.tolerance}).violations.filter(entry=>ids.has(entry.row._row)).map(entry=>entry.row);}
  function count(issue){return measureRows(state.rows,{...issue.crossRule,tolerance:ReviewCore.data(issue).tolerance??issue.crossRule.tolerance}).violations.length;}
  function contexts(issue){return issue.crossRule.inputs;}
   function getFixOptions(issue,session){
     const rule=issue.crossRule,date=rule.operation==="date-order",formula=["difference","sum","product","ratio","discount-product"].includes(rule.operation);
     const options=[...(formula?[{key:"recalculate",label:`Recalculate ${issue.column}`,risk:"Estimates values",compute:()=>({operation:"rowValues",rowMapping:Object.fromEntries(lockedRows(issue,session).map(row=>[row._row,Number(expected(row,{...rule,tolerance:session.tolerance}).value).toFixed(rule.decimals??ReviewCore.precision(issue.column))]))})}]:[]),{key:"set-missing",label:`Mark ${issue.column} as missing`,risk:"Doesn't invent information",compute:()=>({operation:"missing",interpretation:"missing"})},{key:"keep",label:"Keep as is",risk:"Doesn't change values",compute:()=>({operation:"retain",interpretation:"legitimate"})},...(date?[{key:"swap-dates",label:"Swap the two dates",risk:"Estimates values",compute:()=>({operation:"swapDates",otherColumn:rule.inputs[0]})}]:[])];
      return options.map(option=>({...option,compute:async()=>({...await option.compute(),ruleTolerance:session.tolerance,reviewedRelationship:structuredClone(rule)})}));
   }
  function reminder(issue,session){return `Fixing: ${lockedRows(issue,session).length} rows that do not match ${issue.crossRule.label}`;}
   function consequence(issue,session,preview){ // XCOL-F-01, XCOL-F-02, XCOL-F-03
     const before=ReviewCore.total(state.rows,issue.column),after=ReviewCore.total(preview.after,issue.column),dependency=CapabilitiesEngine.dependencyImpact(state.headers,state.rows,preview,state.ruleConfig.metrics,capabilityOptions()), rule=issue.crossRule;
     const duration=rows=>CleaningEngine.stats(measureRows(rows,rule).entries.map(entry=>entry.difference)).mean;
     const revenue=state.headers.find(column=>/^revenue(?:_|$)/i.test(column)),margin=rows=>ReviewCore.total(rows,revenue) ? ReviewCore.total(rows,issue.column)/ReviewCore.total(rows,revenue)*100 : null;
     return {sentence:rule.operation==="date-order" ? `Average time from ${rule.inputs[0]} to ${rule.inputs[1]}: ${ReviewCore.format(duration(state.rows),"",{decimals:1})} → ${ReviewCore.format(duration(preview.after),"",{decimals:1})} days.` : rule.operation==="relation" ? `${preview.patches.length} cells change for the declared relationship; review which source field should be trusted.` : `Total ${issue.column}: ${ReviewCore.money(before,issue.column)} → ${ReviewCore.money(after,issue.column)} (${ReviewCore.money(after-before,issue.column)} change).`,figures:rule.operation==="date-order" || rule.operation==="relation" ? [] : [{label:issue.column,before:ReviewCore.money(before,issue.column),after:ReviewCore.money(after,issue.column)},...(/^profit/i.test(issue.column)&&revenue?[{label:"Margin",before:`${ReviewCore.format(margin(state.rows),"",{decimals:1})}%`,after:`${ReviewCore.format(margin(preview.after),"",{decimals:1})}%`}]:[])],reason:"Trusts the selected source columns; review whether the target rather than an input is wrong.",detail:dependency.map(entry=>`${entry.target} uses ${issue.column}: ${entry.violatingRowIds.length} values will no longer match; ${entry.blockedRowIds.length} cannot be checked.`).join(" ")};}
   function scatterActual(issue,rows,rule,bounds){
     const date=rule.operation==="date-order",entries=measureRows(rows,rule).entries.filter(entry=>date||typeof entry.value==="number"),number=value=>date?Date.parse(value):value,xy=value=>30+(number(value)-bounds.min)/(bounds.max-bounds.min||1)*260;
     if(!entries.length)return '<p class="review-empty-copy">No usable numerical or dated pairs remain for this comparison.</p>';
      return `<svg viewBox="0 0 320 320" class="cross-scatter" role="img" aria-label="Expected versus actual values; both plots share axes"><line x1="30" y1="290" x2="290" y2="30" stroke="#C9CFD8"/>${entries.slice(0,1000).map(entry=>`<circle cx="${xy(entry.value)}" cy="${320-xy(entry.actual)}" r="3" fill="${entry.valid?"#2E6BD9":"#E07B39"}"><title>Row ${entry.row._row}: expected ${date?entry.value:ReviewCore.format(entry.value,issue.column)}, actual ${date?entry.actual:ReviewCore.format(entry.actual,issue.column)}</title></circle>`).join("")}<text x="140" y="313">Expected</text><text x="5" y="20">Actual</text></svg>`;
   }
   async function aiExplore(issue,session){ // XCOL-A-01: bounded actual inputs + target, not target-only strings.
     const fields=[...new Set([issue.column,...issue.crossRule.inputs])],selected=lockedRows(issue,session),context={column:issue.column,type:"cross-column",role:issue.crossRule.operation==="date-order"?"date":ReviewCore.numericType(issue.column)?"number":"text",headers:state.headers,meaning:issue.crossRule.label,allowedFixes:getFixOptions(issue,session).map(option=>option.key),count:state.rows.length,affected:selected.length,values:ReviewPageEngine.frequencies(selected,issue.column).slice(0,20).map(group=>({value:group.value,count:group.rows.length,locked:true})),samples:[],statistics:{},groups:[],comparisonRows:selected.slice(0,20).map(row=>Object.fromEntries(fields.map(column=>[column,String(row[column]??"").slice(0,500)]))),columnStatistics:Object.fromEntries(fields.map(column=>[column,cleaningProfile().columns.find(profile=>profile.column===column)?.statistics || {}])),relationship:{label:issue.crossRule.label,target:issue.column,inputs:issue.crossRule.inputs,operation:issue.crossRule.operation,tolerance:session.tolerance}};
     const result=await ReviewCore.requestAi(issue,"explore",context);if(result?.suggestedFix){session.aiFixProposal=result.suggestedFix;renderPreservingReviewFocus();}
   }
   function bind(issue,session){
     const changed=edit=>{const before=lockedRows(issue,session).length;edit();ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();};
     document.getElementById("crossTolerance")?.addEventListener("change",event=>{const tolerance=Number(event.target.value);if(!Number.isFinite(tolerance)||tolerance<0){notify("Tolerance must be a finite number at least zero.");return;}changed(()=>{session.tolerance=tolerance;session.locked=measureRows(state.rows,{...issue.crossRule,tolerance}).violations.map(entry=>String(entry.row._row));});});
     document.querySelectorAll("[data-cross-row]").forEach(input=>input.onchange=()=>changed(()=>{const id=input.dataset.crossRow;session.locked=input.checked?session.locked.concat(id):session.locked.filter(value=>value!==id);}));
     const large=document.getElementById("crossOnlyLarge");if(large){large.checked=Boolean(session.onlyLarge);large.addEventListener("change",event=>changed(()=>{session.onlyLarge=event.target.checked;const rule={...issue.crossRule,tolerance:session.tolerance};session.locked=measureRows(state.rows,rule).violations.filter(entry=>!session.onlyLarge||Math.abs(entry.difference)>=rule.tolerance*5).map(entry=>String(entry.row._row));}));}
     document.getElementById("crossRemove")?.addEventListener("click",()=>ReviewCore.accept(issue,{removedRule:issue.ruleId}));document.getElementById("crossAi")?.addEventListener("click",()=>aiExplore(issue,session));
     const table=document.querySelector('[data-ui="review.explore.cross.table"]'),all=measureRows(state.rows,{...issue.crossRule,tolerance:session.tolerance}).violations;
     if(table&&all.length>200){const button=document.createElement("button");button.className="text-button";button.textContent=`Show all ${all.length} violating rows`;button.onclick=()=>{session.expandedLists ||= {};session.expandedLists["cross-rows"]=true;renderPreservingReviewFocus();};if(!session.expandedLists?.["cross-rows"])table.after(button);else{const body=table.querySelector("tbody"),rule=issue.crossRule;body.innerHTML=all.map(entry=>`<tr><td><input type="checkbox" data-cross-row="${entry.row._row}" ${session.locked.includes(String(entry.row._row))?"checked":""}></td><td>${entry.row._row}</td>${rule.inputs.map(column=>`<td>${escapeHtml(entry.row[column])}</td>`).join("")}<td>${escapeHtml(entry.row[issue.column])}</td><td>${typeof entry.value==="number"?ReviewCore.format(entry.value,issue.column):escapeHtml(entry.value)}</td><td>${ReviewCore.format(entry.difference,issue.column)}</td></tr>`).join("");body.querySelectorAll("[data-cross-row]").forEach(input=>input.onchange=()=>changed(()=>{const id=input.dataset.crossRow;session.locked=input.checked?session.locked.concat(id):session.locked.filter(value=>value!==id);}));}}
   }
    function exploreContent(issue,session){ // XCOL-E-01…04 / T1 shared slots.
      init(issue,session);const c=ReviewComponents,rule={...issue.crossRule,tolerance:session.tolerance},measured=measureRows(state.rows,rule),threshold=rule.tolerance*5;
      const items=measured.violations.slice(0,200).map(entry=>({value:entry.row[issue.column],count:`row ${entry.row._row}`,share:"",control:`<input type="checkbox" data-cross-row="${entry.row._row}" ${session.locked.includes(String(entry.row._row))?"checked":""}>`,meta:`difference ${ReviewCore.format(entry.difference,issue.column)}`,attrs:{"data-row":entry.row._row}}));
      const fields=[...new Set(rule.inputs)],columns=[{key:"row",label:"Row",numeric:true},...fields.map(column=>({key:column,label:column})),{key:"actual",label:"Actual"},{key:"expected",label:"Expected"},{key:"difference",label:"Difference",numeric:true}];
      const examples=measured.violations.slice(0,200).map(entry=>({row:entry.row._row,...Object.fromEntries(fields.map(column=>[column,{value:entry.row[column],raw:true}])),actual:{value:entry.actual,raw:true,problem:true},expected:typeof entry.value==="number"?ReviewCore.format(entry.value,issue.column):entry.value,difference:ReviewCore.format(entry.difference,issue.column)}));
      return {lead:`Which column should be trusted in these ${measured.violations.length} ${c.noun()}?`,sub:`${rule.label}. ${measured.blocked.length} cannot be checked${measured.blocked.length?` (${measured.blocked[0].reason})`:""}.`,selection:c.selection(items,{ui:"review.explore.cross.values",total:`${lockedRows(issue,session).length} entries selected`,ai:`<button class="text-button" id="crossAi">Which column is wrong? AI</button>${session.aiRequested?ReviewCore.aiStatus(issue):""}${session.ai?`<p>${c.text(session.ai.note)}</p>`:""}`}),evidence:c.toolbar("Rule",`<label>Tolerance<input id="crossTolerance" type="number" min="0" step="any" value="${session.tolerance}"></label><label><input type="checkbox" id="crossOnlyLarge" ${session.onlyLarge?"checked":""}>Select only large differences</label><button class="text-button" id="crossRemove">Remove rule</button>`,"review.explore.cross.rule")+c.headline(`${measured.violations.filter(entry=>Math.abs(entry.difference)<threshold).length} differences are smaller than ${ReviewCore.format(threshold,issue.column)}; check whether rounding explains them.`)+c.table({columns,rows:examples,ui:"review.explore.cross.table"}),evidenceTitle:"Compare actual and expected values"};
    }
    function fixContent(issue,session,preview){ // XCOL-F-03 / C6
      return {examples:ReviewComponents.table({columns:[{key:"row",label:"Row",numeric:true},{key:"before",label:"Before"},{key:"after",label:"After"}],rows:preview.patches.slice(0,5).map(patch=>({row:patch.rowId,before:{value:patch.before,raw:true},after:{value:patch.after||"(blank)",raw:true}})),card:false,empty:"No values change for this option."})};
    }
    function reviewContent(issue,decision){ // XCOL-R-01…03 / frozen rule and one comparison chart.
      const a=decision.reviewImpact.beforeRows,b=decision.reviewImpact.afterRows,rule={...(decision.treatment.reviewedRelationship||issue.crossRule),tolerance:decision.treatment.ruleTolerance??issue.crossRule.tolerance},before=measureRows(a,rule),after=measureRows(b,rule),values=before.entries.concat(after.entries).flatMap(entry=>typeof entry.value==="number"?[entry.value,entry.actual]:[]),bounds={min:Math.min(0,...values),max:Math.max(1,...values)};
      return {lead:`${new Set(decision.patches.map(patch=>patch.rowId)).size} ${ReviewComponents.noun()} corrected for ${issue.column}.`,sub:`${decision.reviewSpec.label} · ${new Date(decision.createdAt).toLocaleTimeString()} · ${decision.note||"No note"}`,count:decision.rows.length,change:{metrics:[{label:"Rows changed",value:new Set(decision.patches.map(patch=>patch.rowId)).size},{label:"Violations",value:`${before.violations.length} → ${after.violations.length}`},{label:"Column total",value:`${ReviewCore.money(ReviewCore.total(a,issue.column),issue.column)} → ${ReviewCore.money(ReviewCore.total(b,issue.column),issue.column)}`}],visual:values.length?scatterActual(issue,b,rule,bounds):"",text:`${before.violations.length} → ${after.violations.length} disagreements; points on the diagonal match the source calculation.`},examples:fixContent(issue,{}, {patches:decision.patches}).examples};
    }
    return {detect,init,count,unit:"rows",lockedRows,contextColumns:contexts,exploreContent,fixContent,reviewContent,renderExplore:(issue,session)=>ReviewComponents.explore(issue,exploreContent(issue,session)),getFixOptions,reminder,consequence,aiExplore,bind};
})();
