// XCOL-D-01, XCOL-D-02, XCOL-D-03, XCOL-D-04: formulas are supported only by usable input evidence.
ReviewModules["cross-column"] = (() => {
  function definitions(headers){const find=regex=>headers.find(column=>regex.test(column)),revenue=find(/^revenue(?:_|$)/i),cost=find(/^cost(?:_|$)/i),profit=find(/^profit(?:_|$)/i),spend=find(/^spend(?:_|$)/i),clicks=find(/^clicks$/i),impressions=find(/^impressions$/i),conversions=find(/^conversions$/i),quantity=find(/^quantity$|^qty$/i),price=find(/unit_price/i),discount=find(/discount/i),roas=find(/^roas$/i),cpc=find(/^cpc/i),ctr=find(/^ctr|click_through_rate/i),start=find(/start.*date|order_date|admit.*date/i),end=find(/end.*date|delivery.*date|discharge.*date/i),systolic=find(/systolic/i),diastolic=find(/diastolic/i),rules=[];
    const add=(target,inputs,operation,label,factor=1)=>{if(target&&inputs.every(Boolean))rules.push({id:`auto:${target}:${operation}`,column:target,target,inputs,operation,label,factor,suggested:true});};add(profit,[revenue,cost],"difference",`${profit} = ${revenue} − ${cost}`);add(revenue,[quantity,price,discount],"discount-product",`${revenue} = ${quantity} × ${price} × (1 − ${discount}/100)`);add(roas,[revenue,spend],"ratio",`${roas} = ${revenue} ÷ ${spend}`);add(cpc,[spend,clicks],"ratio",`${cpc} = ${spend} ÷ ${clicks}`);add(ctr,[clicks,impressions],"ratio",`${ctr} = ${clicks} ÷ ${impressions}`,/pct|percent/i.test(ctr)?100:1);add(clicks,[clicks,impressions],"less-equal",`${clicks} ≤ ${impressions}`);add(conversions,[conversions,clicks],"less-equal",`${conversions} ≤ ${clicks}`);add(end,[start,end],"date-order",`${end} ≥ ${start}`);add(diastolic,[diastolic,systolic],"less",`${diastolic} < ${systolic}`);return rules;}
   function expected(row,rule){
     if (rule.operation === "relation") {
       const problem=relationProblem(row,rule.relation);
       if (/can’t|cannot|missing|unreadable/i.test(problem || "") && rule.relation.kind!=="requiredIf") throw new Error(problem);
       const actual=row[rule.column], value=row[rule.relation.right] || "Required value", valid=!problem;
       return {value,actual,difference:valid?0:1,valid};
     }
     if(rule.inputs.some(column=>observationState(row,column)!=="present"))throw new Error("input missing");
     if(rule.operation==="date-order"){
       const date=column=>ReviewPageEngine.dateValue(row[column],reviewDateFormats()[JSON.stringify([row._row,column,row[column]])] || columnPolicy(column).dateFormat),start=date(rule.inputs[0]),end=date(rule.inputs[1]);
       return {value:start,actual:end,difference:(Date.parse(end)-Date.parse(start))/86400000,valid:end>=start};
     }
     const values=rule.inputs.map(column=>CleaningEngine.parseNumber(row[column],columnPolicy(column)));
     if(observationState(row,rule.column)!=="present")throw new Error("target missing");
     const actual=CleaningEngine.parseNumber(row[rule.column],columnPolicy(rule.column));let value;
     if(rule.operation==="difference")value=values[0]-values[1];else if(rule.operation==="product")value=values[0]*values[1];else if(rule.operation==="sum")value=values.reduce((sum,value)=>sum+value,0);else if(rule.operation==="discount-product")value=values[0]*values[1]*(1-values[2]/100);else if(rule.operation==="ratio"){if(!values[1])throw new Error("zero denominator");value=values[0]/values[1];}else value=values[1];
     if (!["less","less-equal","discount-product"].includes(rule.operation)) value*=rule.factor??1;
     if(rule.decimals!==undefined)value=Number(value.toFixed(rule.decimals));
     const difference=actual-value,valid=rule.operation==="less-equal"?actual<=value:rule.operation==="less"?actual<value:Math.abs(difference)<=rule.tolerance;
     return {value,actual,difference,valid};
   }
  function measureRows(rows,rule){const entries=[],blocked=[];for(const row of rows){try{entries.push({row,...expected(row,rule)});}catch(error){blocked.push({row,reason:error.message});}}return {entries,blocked,violations:entries.filter(entry=>!entry.valid).sort((a,b)=>Math.abs(b.difference)-Math.abs(a.difference))};}
   function detect(dataset){
     const removed=new Set(state.changes.map(change=>change.treatment?.removedRule).filter(Boolean));
     const declared=state.ruleConfig.metrics.map(rule=>({...rule,column:rule.target,inputs:rule.terms?.length?rule.terms:[rule.left,rule.right],label:metricFormula(rule),suggested:false}));
     const relations=(state.ruleConfig.relations || []).map(rule=>({id:rule.id,column:rule.column,inputs:rule.kind==="requiredIf"?[rule.left,rule.column]:[rule.left,rule.right],operation:"relation",relation:rule,label:rule.name || `${rule.left} ${rule.operator} ${rule.right}`,suggested:false,tolerance:0}));
     const rules=definitions(dataset.headers).filter(rule=>!declared.some(other=>other.column===rule.column&&other.operation===rule.operation)).concat(declared,relations).filter(rule=>!removed.has(rule.id));
     return rules.flatMap(rule=>{const policy=ReviewCore.precision(rule.column),median=CleaningEngine.stats(ReviewCharts.numeric(dataset.rows,rule.column).map(Math.abs)).median;rule.tolerance=rule.tolerance??Math.max((median||0)*.01,10**-policy);const overrides=state.reviewPage?.[`${rule.column}:cross-column:${rule.id}`]?.tolerance;if(Number.isFinite(overrides)&&overrides>=0)rule.tolerance=overrides;const measured=measureRows(dataset.rows,rule);if(rule.suggested&&measured.entries.filter(entry=>entry.valid).length/Math.max(1,measured.entries.length)<.8)return [];if(!measured.violations.length)return [];return [{column:rule.column,reviewType:"cross-column",type:"Conflicting columns",label:"Conflicting columns",rows:measured.violations.map(entry=>entry.row),recommendation:"manual",severity:"medium",status:"open",summary:rule.label,crossRule:rule,ruleId:rule.id,unit:"rows"}];});
   }
  function init(issue,session){session.tolerance??=issue.crossRule.tolerance;if(session.locked===null)session.locked=measureRows(state.rows,issue.crossRule).violations.map(entry=>String(entry.row._row));}
  function lockedRows(issue,session){init(issue,session);const ids=new Set(session.locked.map(Number));return measureRows(state.rows,{...issue.crossRule,tolerance:session.tolerance}).violations.filter(entry=>ids.has(entry.row._row)).map(entry=>entry.row);}
  function count(issue){return measureRows(state.rows,{...issue.crossRule,tolerance:ReviewCore.data(issue).tolerance??issue.crossRule.tolerance}).violations.length;}
  function contexts(issue){return issue.crossRule.inputs;}
  function renderExplore(issue,session){ // XCOL-E-01, XCOL-E-02, XCOL-E-03, XCOL-E-04
    init(issue,session);const rule={...issue.crossRule,tolerance:session.tolerance},measured=measureRows(state.rows,rule),threshold=rule.tolerance*5,small=measured.violations.filter(entry=>Math.abs(entry.difference)<threshold).length;return `<section class="cross-explore" data-ui="review.explore.cross"><div data-ui="review.explore.cross.rule"><h2>Rule: ${escapeHtml(rule.label)}</h2><span>${rule.suggested?"suggested":"your rule"}</span><label>Tolerance<input id="crossTolerance" type="number" step="any" min="0" value="${session.tolerance}"></label><button class="text-button" id="crossRemove">Remove rule</button></div><p data-ui="review.explore.cross.count">${measured.violations.length} rows don’t match (${(measured.violations.length/state.rows.length*100).toFixed(1)}%) · ${measured.blocked.length} rows can’t be checked${measured.blocked.length?` (${escapeHtml(measured.blocked[0].reason)})`:""}</p><div class="review-table-scroll cross-table" data-ui="review.explore.cross.table"><table><thead><tr><th>Lock</th><th>Row</th>${rule.inputs.map(column=>`<th>${escapeHtml(column)}</th>`).join("")}<th>Actual ${escapeHtml(issue.column)}</th><th>Expected</th><th>Difference</th></tr></thead><tbody>${measured.violations.slice(0,200).map(entry=>`<tr><td><input type="checkbox" data-cross-row="${entry.row._row}" ${session.locked.includes(String(entry.row._row))?"checked":""}></td><td>${entry.row._row}</td>${rule.inputs.map(column=>`<td>${escapeHtml(entry.row[column])}</td>`).join("")}<td>${escapeHtml(entry.row[issue.column])}</td><td>${typeof entry.value==="number"?ReviewCore.format(entry.value,issue.column):escapeHtml(entry.value)}</td><td>${ReviewCore.format(entry.difference,issue.column)}</td></tr>`).join("")}</tbody></table></div><p data-ui="review.explore.cross.split">Small differences (&lt; ${ReviewCore.format(threshold,issue.column)}): ${small} · Large: ${measured.violations.length-small} <label><input id="crossOnlyLarge" type="checkbox"> Lock only large ones</label></p><button class="secondary" id="crossAi">Which column is wrong? AI</button>${session.aiRequested?ReviewCore.aiStatus(issue):""}${session.ai?`<p>${escapeHtml(session.ai.note)}</p>`:""}</section>`;}
   function getFixOptions(issue,session){
     const rule=issue.crossRule,date=rule.operation==="date-order",formula=["difference","sum","product","ratio","discount-product"].includes(rule.operation);
     const options=[...(formula?[{key:"recalculate",label:`Recalculate ${issue.column}`,risk:"Estimates values",compute:()=>({operation:"rowValues",rowMapping:Object.fromEntries(lockedRows(issue,session).map(row=>[row._row,Number(expected(row,{...rule,tolerance:session.tolerance}).value).toFixed(rule.decimals??ReviewCore.precision(issue.column))]))})}]:[]),{key:"set-missing",label:`Mark ${issue.column} as missing`,risk:"Doesn't invent information",compute:()=>({operation:"missing",interpretation:"missing"})},{key:"keep",label:"Keep as is",risk:"Doesn't change values",compute:()=>({operation:"retain",interpretation:"legitimate"})},...(date?[{key:"swap-dates",label:"Swap the two dates",risk:"Estimates values",compute:()=>({operation:"swapDates",otherColumn:rule.inputs[0]})}]:[])];
     return options.map(option=>({...option,compute:async()=>({...await option.compute(),ruleTolerance:session.tolerance})}));
   }
  function reminder(issue,session){return `Fixing: ${lockedRows(issue,session).length} rows that do not match ${issue.crossRule.label}`;}
   function consequence(issue,session,preview){ // XCOL-F-01, XCOL-F-02, XCOL-F-03
     const before=ReviewCore.total(state.rows,issue.column),after=ReviewCore.total(preview.after,issue.column),dependency=CapabilitiesEngine.dependencyImpact(state.headers,state.rows,preview,state.ruleConfig.metrics,capabilityOptions()), rule=issue.crossRule;
     const duration=rows=>CleaningEngine.stats(measureRows(rows,rule).entries.map(entry=>entry.difference)).mean;
     const revenue=state.headers.find(column=>/^revenue(?:_|$)/i.test(column)),margin=rows=>ReviewCore.total(rows,revenue) ? ReviewCore.total(rows,issue.column)/ReviewCore.total(rows,revenue)*100 : null;
     return {sentence:rule.operation==="date-order" ? `Average time from ${rule.inputs[0]} to ${rule.inputs[1]}: ${ReviewCore.format(duration(state.rows),"",{decimals:1})} → ${ReviewCore.format(duration(preview.after),"",{decimals:1})} days.` : rule.operation==="relation" ? `${preview.patches.length} cells change for the declared relationship; review which source field should be trusted.` : `Total ${issue.column}: ${ReviewCore.money(before,issue.column)} → ${ReviewCore.money(after,issue.column)} (${ReviewCore.money(after-before,issue.column)} change).`,figures:rule.operation==="date-order" || rule.operation==="relation" ? [] : [{label:issue.column,before:ReviewCore.money(before,issue.column),after:ReviewCore.money(after,issue.column)},...(/^profit/i.test(issue.column)&&revenue?[{label:"Margin",before:`${ReviewCore.format(margin(state.rows),"",{decimals:1})}%`,after:`${ReviewCore.format(margin(preview.after),"",{decimals:1})}%`}]:[])],reason:"Trusts the selected source columns; review whether the target rather than an input is wrong.",detail:dependency.map(entry=>`${entry.target} uses ${issue.column}: ${entry.violatingRowIds.length} values will no longer match; ${entry.blockedRowIds.length} cannot be checked.`).join(" ")};}
  function renderPreview(issue,session,preview){return ReviewCore.sampleTable(issue,preview.patches,issue.crossRule.inputs,20);}
   function scatterActual(issue,rows,rule,bounds){
     const date=rule.operation==="date-order",entries=measureRows(rows,rule).entries.filter(entry=>date||typeof entry.value==="number"),number=value=>date?Date.parse(value):value,xy=value=>30+(number(value)-bounds.min)/(bounds.max-bounds.min||1)*260;
     if(!entries.length)return '<p class="review-empty-copy">No usable numerical or dated pairs remain for this comparison.</p>';
     return `<svg viewBox="0 0 320 320" class="cross-scatter" role="img" aria-label="Expected versus actual values; both plots share axes"><line x1="30" y1="290" x2="290" y2="30" stroke="#9AA3AE"/>${entries.slice(0,1000).map(entry=>`<circle cx="${xy(entry.value)}" cy="${320-xy(entry.actual)}" r="3" fill="${entry.valid?"#2E6BD9":"#E07B39"}"><title>Row ${entry.row._row}: expected ${date?entry.value:ReviewCore.format(entry.value,issue.column)}, actual ${date?entry.actual:ReviewCore.format(entry.actual,issue.column)}</title></circle>`).join("")}<text x="140" y="313">Expected</text><text x="5" y="20">Actual</text></svg>`;
   }
  function renderReview(issue,decision){ // XCOL-R-01, XCOL-R-02, XCOL-R-03
     const before=decision.reviewImpact.beforeRows,after=decision.reviewImpact.afterRows,rule={...issue.crossRule,tolerance:decision.treatment.ruleTolerance??issue.crossRule.tolerance}, entries=[...measureRows(before,rule).entries,...measureRows(after,rule).entries], values=entries.flatMap(entry=>rule.operation==="date-order"?[Date.parse(entry.value),Date.parse(entry.actual)]:typeof entry.value==="number"?[entry.value,entry.actual]:[]),bounds={min:Math.min(0,...values),max:Math.max(1,...values)};
     if(rule.operation==="date-order"&&values.length)bounds.min=Math.min(...values);
     return `${ReviewCore.metricStrip([{label:"Cells changed",value:decision.patches.length},{label:"Rows removed",value:0},{label:"Columns added / removed",value:"0 / 0"},{label:"Violations",value:`${measureRows(before,rule).violations.length} → ${measureRows(after,rule).violations.length}`},...(rule.operation!=="date-order"&&rule.operation!=="relation"?[{label:issue.column,value:`${ReviewCore.money(ReviewCore.total(before,issue.column),issue.column)} → ${ReviewCore.money(ReviewCore.total(after,issue.column),issue.column)}`}]:[])])}<div data-ui="review.review.chart"><p>${measureRows(before,rule).violations.length} → ${measureRows(after,rule).violations.length} violations; points on the diagonal agree with the source calculation.</p><div class="cross-scatter-pair"><section><h3>Before</h3>${scatterActual(issue,before,rule,bounds)}</section><section><h3>After</h3>${scatterActual(issue,after,rule,bounds)}</section></div></div>${ReviewCore.sampleTable(issue,decision.patches,rule.inputs)}`;}
  async function aiExplore(issue,session){const context={column:issue.column,type:"cross-column",role:"number",headers:state.headers,meaning:issue.crossRule.label,allowedFixes:getFixOptions(issue,session).map(option=>option.key),count:state.rows.length,affected:lockedRows(issue,session).length,values:ReviewPageEngine.frequencies(lockedRows(issue,session),issue.column).slice(0,20).map(group=>({value:group.value,count:group.rows.length,locked:true})),samples:[],statistics:{},groups:[]};await ReviewCore.requestAi(issue,"explore",context);}
  function bind(issue,session){document.getElementById("crossTolerance")?.addEventListener("change",event=>{session.tolerance=Number(event.target.value);session.locked=measureRows(state.rows,{...issue.crossRule,tolerance:session.tolerance}).violations.map(entry=>String(entry.row._row));session.preview=null;renderPreservingReviewFocus();});document.querySelectorAll("[data-cross-row]").forEach(input=>input.onchange=()=>{const id=input.dataset.crossRow;session.locked=input.checked?session.locked.concat(id):session.locked.filter(value=>value!==id);session.preview=null;renderPreservingReviewFocus();});document.getElementById("crossOnlyLarge")?.addEventListener("change",event=>{const rule={...issue.crossRule,tolerance:session.tolerance};session.locked=measureRows(state.rows,rule).violations.filter(entry=>!event.target.checked||Math.abs(entry.difference)>=rule.tolerance*5).map(entry=>String(entry.row._row));session.preview=null;renderPreservingReviewFocus();});document.getElementById("crossRemove")?.addEventListener("click",()=>ReviewCore.accept(issue,{removedRule:issue.ruleId}));document.getElementById("crossAi")?.addEventListener("click",()=>aiExplore(issue,session));}
  return {detect,init,count,unit:"rows",lockedRows,contextColumns:contexts,renderExplore,getFixOptions,reminder,consequence,renderPreview,renderReview,aiExplore,bind};
})();
