// DUP-D-01, DUP-D-02, DUP-D-03: independent key-repeat and trimmed exact-row lenses.
(() => {
  const keyFor = (rows,columns,trim=false) => ReviewPageEngine.frequencies(rows,columns[0],(_,row)=>JSON.stringify(columns.map(column=>trim?String(row[column]??"").trim():row[column]))).filter(group=>group.rows.length>1);
  function build(type) {
    const exact=type==="duplicate-rows";
    function detect(dataset) { const allowed=new Set(state.changes.map(change=>change.treatment?.repeatableColumn).filter(Boolean));if(exact){const groups=keyFor(dataset.rows,dataset.headers,true);return groups.length?[{column:dataset.headers[0],displayColumn:"All columns",reviewType:type,type:"Duplicate rows",label:"Duplicate rows",rows:groups.flatMap(group=>group.rows),recommendation:"duplicates",severity:"medium",summary:"Exact copies after surrounding whitespace is trimmed.",status:"open",unit:"rows",duplicateDefinition:{mode:"exact",columns:dataset.headers,trim:true},count:groups.reduce((sum,group)=>sum+group.rows.length-1,0)}]:[];}return dataset.headers.flatMap(column=>{const present=dataset.rows.filter(row=>String(row[column]??"").trim()),distinct=new Set(present.map(row=>row[column])).size;if(allowed.has(column)||!/(id|code|number|no|email)$/i.test(column)&&distinct/Math.max(1,present.length)<.95)return [];const groups=keyFor(present,[column]);return groups.length?[{column,reviewType:type,type:"Repeated values",label:"Repeated values",rows:groups.flatMap(group=>group.rows),recommendation:"duplicates",severity:"medium",summary:"Review whether these repeated values should be unique.",status:"open",unit:"rows",duplicateDefinition:{mode:"key",columns:[column]},count:groups.reduce((sum,group)=>sum+group.rows.length,0)}]:[];});}
    function groups(issue){const columns=issue.duplicateDefinition.columns,raw=keyFor(state.rows.filter(row=>issue.rows.some(original=>original._row===row._row)),columns,exact);return raw.map(group=>({...group,different:state.headers.filter(column=>new Set(group.rows.map(row=>row[column])).size>1)})).sort((a,b)=>b.different.length-a.different.length);}
    function init(issue,session){if(session.locked===null)session.locked=groups(issue).map(group=>group.value);session.survivors ||= {};session.groupIndex ||= 0;session.visitedGroups ||= [];session.keepRule ||= {column:state.headers.find(column=>column!==issue.column)||issue.column,condition:"nonblank",value:""};if(session.fix==="one-by-one"){const list=groups(issue);list.forEach(group=>{if(session.survivors[group.value]===undefined)session.survivors[group.value]=group.rows[0]._row;});const current=list[session.groupIndex];if(current&&!session.visitedGroups.includes(current.value))session.visitedGroups.push(current.value);}}
    function lockedGroups(issue,session){init(issue,session);return groups(issue).filter(group=>session.locked.includes(group.value));}
    function lockedRows(issue,session){let selected=lockedGroups(issue,session);if(session.fix==="one-by-one"&&session.partialChoices)selected=selected.filter(group=>session.visitedGroups.includes(group.value));return selected.flatMap(group=>group.rows);}
    function count(issue){return exact?groups(issue).reduce((sum,group)=>sum+group.rows.length-1,0):groups(issue).reduce((sum,group)=>sum+group.rows.length,0);}
    function miniTable(issue,group,selection=false){ // DUP-E-05, DUP-F-04
      const columns=[...new Set([issue.column,...group.different,...state.headers.filter(column=>column!==issue.column&&!group.different.includes(column)).slice(0,3)])],session=ReviewCore.data(issue);return `<div class="review-table-scroll"><table><thead><tr><th>Row</th>${columns.map(column=>`<th>${escapeHtml(column)}</th>`).join("")}${selection?"<th>Keep</th>":""}</tr></thead><tbody>${group.rows.map(row=>`<tr class="${selection&&session.survivors[group.value]===row._row?"duplicate-kept":""}"><td>${row._row}</td>${columns.map(column=>`<td class="${group.different.includes(column)?"duplicate-different":""}">${escapeHtml(row[column]||"—")}</td>`).join("")}${selection?`<td><button class="text-button" data-survivor="${row._row}" data-survivor-group="${escapeHtml(group.value)}">Keep this row</button></td>`:""}</tr>`).join("")}</tbody></table></div>`;}
    function groupList(issue,session){return `<div data-ui="${exact?"review.explore.dup-rows.groups":"review.explore.dup-values.groups"}" class="duplicate-group-list">${groups(issue).map((group,index)=>`<details class="duplicate-group" data-ui="review.explore.dup-values.group" data-group="${escapeHtml(group.value)}" ${index<3?"open":""}><summary><input type="checkbox" data-duplicate-group="${escapeHtml(group.value)}" ${session.locked.includes(group.value)?"checked":""}>${exact?`Group ${index+1} · ×${group.rows.length}`:`${escapeHtml(group.rows[0][issue.column])} · ${group.rows.length} rows`} · ${group.different.length?`differs in ${escapeHtml(group.different.slice(0,3).join(", "))}`:"identical"}</summary>${miniTable(issue,group)}</details>`).join("")}</div>`;}
    function renderExplore(issue,session){ // DUP-E-01, DUP-E-02, DUP-E-03, DUP-E-04, DUP-E-06, DUP-E-10, DUP-E-11, DUP-E-12
      init(issue,session);const list=groups(issue),same=list.filter(group=>!group.different.length).length,different=state.headers.map(column=>[column,list.filter(group=>group.different.includes(column)).length]).filter(([,count])=>count).sort((a,b)=>b[1]-a[1]);return `<section class="duplicate-explore" data-ui="${exact?"review.explore.dup-rows":"review.explore.dup-values"}"><h2 data-ui="${exact?"review.explore.dup-rows.count":"review.explore.dup-values.count"}">${exact?`${count(issue)} rows are exact copies, in ${list.length} groups.`:`${list.length} values repeat · ${count(issue)} rows involved`}</h2>${exact?'<button class="secondary" id="duplicateShortcut" data-ui="review.explore.dup-rows.shortcut">Remove all exact copies</button>':`<div class="duplicate-question" data-ui="review.explore.dup-values.question"><p>Can values in ${escapeHtml(issue.column)} repeat?</p><button class="secondary" id="duplicateYes">Yes, that’s normal</button><button class="secondary" id="duplicateNo">No, they should be unique</button></div>`}${exact||session.uniqueConfirmed?`<div class="duplicate-summary" data-ui="review.explore.dup-values.summary"><p>${same} groups identical · ${list.length-same} groups differ in other columns</p><p>Most often different: ${escapeHtml(different.slice(0,3).map(([column,count])=>`${column} (${count})`).join(" · ")||"None")}</p></div>${groupList(issue,session)}${!exact?'<button class="secondary" id="duplicateAiExplore">Are these real duplicates? AI</button>':""}${session.aiRequested?ReviewCore.aiStatus(issue):""}${session.ai?`<p>${escapeHtml(session.ai.note)}</p>`:""}`:""}</section>`;
    }
    function survivor(group,session,key){const complete=row=>state.headers.filter(column=>String(row[column]??"").trim()).length;if(key==="keep-last")return group.rows.at(-1);if(key==="keep-most-complete"||key==="merge")return [...group.rows].sort((a,b)=>complete(b)-complete(a)||a._row-b._row)[0];if(key==="one-by-one")return group.rows.find(row=>row._row===session.survivors[group.value]);if(key==="rule"){const rule=session.keepRule,matching=group.rows.filter(row=>rule.condition==="nonblank"?String(row[rule.column]??"").trim():rule.condition==="equals"?row[rule.column]===rule.value:true);if(["highest","lowest","latest"].includes(rule.condition)){const numeric=ReviewCore.numericType(rule.column);matching.sort((a,b)=>{const av=numeric?Number(a[rule.column]):String(a[rule.column]),bv=numeric?Number(b[rule.column]):String(b[rule.column]);return numeric?av-bv:av.localeCompare(bv);});return rule.condition==="lowest"?matching[0]:matching.at(-1);}return matching[0]||group.rows[0];}return group.rows[0];}
    function hasConflicts(issue,session){return lockedGroups(issue,session).filter(group=>group.different.length).length;}
    function compute(issue,session,key){if(key==="keep-all")return {operation:"retain",interpretation:"legitimate"};const list=lockedGroups(issue,session).filter(group=>!session.partialChoices||session.survivors[group.value]!==undefined),keepAll=list.filter(group=>session.survivors[group.value]==="all").flatMap(group=>group.rows.map(row=>row._row)),selected=list.filter(group=>!keepAll.includes(group.rows[0]._row)).map(group=>survivor(group,session,key)?._row).filter(Boolean);return {operation:key==="merge"?"mergeDuplicates":"deduplicate",survivor:"selected",survivorIds:selected,keepAllRows:keepAll,trimKeys:exact,acknowledgeConflicts:true,requiresConflictAcknowledgement:hasConflicts(issue,session)>0};}
    function ruleParams(issue,session){return `<div class="duplicate-rule-builder"><select id="duplicateRuleColumn" aria-label="Keep rule column">${state.headers.map(column=>`<option ${session.keepRule.column===column?"selected":""}>${escapeHtml(column)}</option>`).join("")}</select><select id="duplicateRuleCondition" aria-label="Keep rule condition">${[["nonblank","is not blank"],["highest","is highest"],["lowest","is lowest"],["latest","is latest"],["equals","equals value"]].map(([value,label])=>`<option value="${value}" ${session.keepRule.condition===value?"selected":""}>${label}</option>`).join("")}</select>${session.keepRule.condition==="equals"?`<input id="duplicateRuleValue" value="${escapeHtml(session.keepRule.value)}" aria-label="Rule value">`:""}<p>${lockedGroups(issue,session).length} groups use this rule; ties keep the first source row.</p></div>`;}
    function getFixOptions(issue,session){init(issue,session);const differing=hasConflicts(issue,session)>0,option=(key,label,more=false)=>({key,label,more,risk:key==="keep-all"?"Doesn't change values":"Removes data",compute:()=>compute(issue,session,key)});return [option(differing?"keep-most-complete":"keep-first",differing?"Keep most complete":"Keep first"),option("keep-last","Keep last"),option(differing?"keep-first":"keep-most-complete",differing?"Keep first":"Keep most complete"),...(!exact?[option("merge","Merge",true)]:[]),{...option("rule","Keep by rule",true),params:ruleParams},option("one-by-one","Choose per group",true),option("keep-all","Keep all")];}
    function reminder(issue,session){return `Fixing: ${lockedGroups(issue,session).length} repeated ${exact?"row":"value"} groups · ${lockedRows(issue,session).length} rows · ${hasConflicts(issue,session)} groups differ`;}
    function consequence(issue,session,preview,option){ // DUP-F-01, DUP-F-02
      const metric=ReviewCore.metricColumn(),removed=ReviewCore.total(preview.removedRows,metric),whole=ReviewCore.total(state.rows,metric),before=ReviewCore.total(state.rows,metric),after=ReviewCore.total(preview.after,metric),changedMetric=lockedGroups(issue,session).filter(group=>metric&&group.different.includes(metric)).length;return {sentence:option.key==="keep-all"?`All ${lockedRows(issue,session).length} repeated records stay in reports.`:`Removes ${preview.removedRows.length} rows holding ${ReviewCore.money(removed,metric)} (${(removed/Math.max(1,whole)*100).toFixed(1)}% of ${metric||"rows"}).`,figures:[{label:metric||"Total rows",before:ReviewCore.money(before,metric),after:ReviewCore.money(after,metric)},{label:"Row count",before:state.rows.length,after:preview.after.length}],reason:changedMetric?`${changedMetric} removed groups differ in ${metric}; totals may change beyond pure duplicate removal.`:"Only the reviewed survivor policy removes records.",detail:option.key==="merge"?`Fills ${preview.patches.length} blank cells from agreeing duplicate values.`:""};}
    function oneByOne(issue,session){ // DUP-F-04
      const list=lockedGroups(issue,session),index=Math.min(session.groupIndex,list.length-1),group=list[index];if(!group)return "<p>No duplicate groups remain.</p>";return `<section class="duplicate-one-by-one" data-ui="review.fix.one-by-one"><h3>Group ${index+1} of ${list.length}</h3>${miniTable(issue,group,true)}<div><button class="text-button" id="duplicatePrevious" ${index===0?'disabled title="This is the first group"':""}>Previous</button><button class="text-button" id="duplicateNext" ${index===list.length-1?'disabled title="This is the last group"':""}>Next</button><button class="text-button" id="duplicateKeepGroup">Keep all in this group</button><button class="secondary" id="duplicateApplyChoices">Apply choices so far</button></div></section>`;}
    function renderPreview(issue,session,preview,option){ // DUP-F-03, DUP-F-05
      return `${option.key==="one-by-one"?oneByOne(issue,session):""}<div class="review-table-scroll"><table><thead><tr><th>Group</th><th>Kept row</th><th>Removed rows</th></tr></thead><tbody>${lockedGroups(issue,session).slice(0,5).map((group,index)=>{const removed=new Set(preview.removedRows.map(row=>row._row)),kept=group.rows.filter(row=>!removed.has(row._row));return `<tr><td>${exact?index+1:escapeHtml(group.rows[0][issue.column])}</td><td>✓ ${kept.map(row=>row._row).join(", ")}</td><td><s>${group.rows.filter(row=>removed.has(row._row)).map(row=>row._row).join(", ")||"No rows"}</s></td></tr>`;}).join("")}</tbody></table></div>${hasConflicts(issue,session)&&option.key!=="keep-all"?`<label class="duplicate-ack"><input id="duplicateConflictAck" type="checkbox" ${session.acknowledgeConflicts?"checked":""}> I reviewed the differing cells and approve this survivor policy.</label>`:""}`;
    }
    function renderReview(issue,decision){const impact=decision.reviewImpact,metric=decision.reviewSpec?.metric||ReviewCore.metricColumn(),removed=decision.removedRows.length,before=impact.beforeRows.length,after=impact.afterRows.length;return `${ReviewCore.metricStrip([{label:"Rows",value:`${before} → ${after}`},{label:"Rows removed",value:removed},{label:"Cells filled by merge",value:decision.patches.length},{label:"Columns added / removed",value:"0 / 0"},{label:metric||"Row total",value:`${ReviewCore.money(ReviewCore.total(impact.beforeRows,metric),metric)} → ${ReviewCore.money(ReviewCore.total(impact.afterRows,metric),metric)}`}])}<figure class="duplicate-row-chart" data-ui="review.review.chart"><figcaption>${removed} repeated rows removed; ${after} records remain.</figcaption><div><span>Before ${before}</span><i style="width:100%"><b style="width:${removed/Math.max(1,before)*100}%"></b></i></div><div><span>After ${after}</span><i style="width:${after/Math.max(1,before)*100}%"></i></div></figure><div data-ui="review.review.sample">${decision.removedRows.slice(0,5).map(row=>`<p>Removed row ${row._row} · ${escapeHtml(row[issue.column])}</p>`).join("")}</div>`;}
    function context(issue,session){return {column:issue.column,type,role:"text",headers:state.headers,meaning:columnPolicy(issue.column).meaning,allowedFixes:["keep-first","keep-last","keep-most-complete","merge","keep-all","one-by-one"],count:state.rows.length,affected:lockedRows(issue,session).length,values:groups(issue).slice(0,20).map(group=>({value:String(group.rows[0][issue.column]),count:group.rows.length,locked:session.locked.includes(group.value)})),samples:[],statistics:{},groups:groups(issue).slice(0,20).map(group=>({label:group.different.join(", ")||"identical",total:group.rows.length,missing:0}))};}
    async function aiExplore(issue,session){await ReviewCore.requestAi(issue,"explore",context(issue,session));}
    async function aiFix(issue,session){const result=await ReviewCore.requestAi(issue,"fix",context(issue,session));if(result?.params?.keepRule){session.keepRule={column:result.params.keepRule.column,condition:result.params.keepRule.condition==="nonblank"?"nonblank":result.params.keepRule.condition==="latest"?"latest":result.params.keepRule.condition,value:result.params.keepRule.value||""};session.aiFixProposal={...result,operation:"rule"};}else if(result?.operation)session.aiFixProposal=result;renderPreservingReviewFocus();}
    function bind(issue,session){init(issue,session);document.getElementById("duplicateYes")?.addEventListener("click",()=>ReviewCore.accept(issue,{repeatableColumn:issue.column}));document.getElementById("duplicateNo")?.addEventListener("click",()=>{session.uniqueConfirmed=true;renderPreservingReviewFocus();});document.getElementById("duplicateShortcut")?.addEventListener("click",()=>{session.fix="keep-first";ReviewCore.switchTab(issue,"fix");});document.querySelectorAll("[data-duplicate-group]").forEach(input=>input.onchange=()=>{const before=lockedRows(issue,session).length,key=input.dataset.duplicateGroup;session.locked=input.checked?session.locked.concat(key):session.locked.filter(value=>value!==key);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});document.getElementById("duplicateConflictAck")?.addEventListener("change",event=>{session.acknowledgeConflicts=event.target.checked;renderPreservingReviewFocus();});[["duplicateRuleColumn","column"],["duplicateRuleCondition","condition"],["duplicateRuleValue","value"]].forEach(([id,key])=>document.getElementById(id)?.addEventListener("change",event=>{session.keepRule[key]=event.target.value;ReviewCore.compute(issue);}));document.querySelectorAll("[data-survivor]").forEach(button=>button.onclick=()=>{session.survivors[button.dataset.survivorGroup]=Number(button.dataset.survivor);ReviewCore.compute(issue);});document.getElementById("duplicatePrevious")?.addEventListener("click",()=>{session.groupIndex--;renderPreservingReviewFocus();});document.getElementById("duplicateNext")?.addEventListener("click",()=>{session.groupIndex++;renderPreservingReviewFocus();});document.getElementById("duplicateKeepGroup")?.addEventListener("click",()=>{session.survivors[lockedGroups(issue,session)[session.groupIndex].value]="all";ReviewCore.compute(issue);});document.getElementById("duplicateApplyChoices")?.addEventListener("click",()=>{session.partialChoices=true;ReviewCore.compute(issue);});document.getElementById("duplicateAiExplore")?.addEventListener("click",()=>aiExplore(issue,session));if(session.tab==="fix"&&hasConflicts(issue,session)&&session.fix!=="keep-all"&&!session.acknowledgeConflicts)document.getElementById("reviewApply").disabled=true;}
    return {detect,init,count,unit:"rows",groups,lockedRows,hasConflicts,renderExplore,getFixOptions,reminder,consequence,renderPreview,renderReview,aiExplore,aiFix,bind};
  }
  ReviewModules["duplicate-values"]=build("duplicate-values");ReviewModules["duplicate-rows"]=build("duplicate-rows");
})();
