// DUP-D-01, DUP-D-02, DUP-D-03: independent key-repeat and trimmed exact-row lenses.
(() => {
  const keyFor = (rows,columns,trim=false) => ReviewPageEngine.frequencies(rows,columns[0],(_,row)=>JSON.stringify(columns.map(column=>trim?String(row[column]??"").trim():row[column]))).filter(group=>group.rows.length>1);
  function build(type) {
    const exact=type==="duplicate-rows";
    function detect(dataset) { const allowed=new Set(state.changes.map(change=>change.treatment?.repeatableColumn).filter(Boolean));if(exact){const groups=keyFor(dataset.rows,dataset.headers,true);return groups.length?[{column:dataset.headers[0],displayColumn:"All columns",reviewType:type,type:"Duplicate rows",label:"Duplicate rows",rows:groups.flatMap(group=>group.rows),recommendation:"duplicates",severity:"medium",summary:"Exact copies after surrounding whitespace is trimmed.",status:"open",unit:"rows",duplicateDefinition:{mode:"exact",columns:dataset.headers,trim:true},count:groups.reduce((sum,group)=>sum+group.rows.length-1,0)}]:[];}return dataset.headers.flatMap(column=>{const present=dataset.rows.filter(row=>String(row[column]??"").trim()),distinct=new Set(present.map(row=>row[column])).size;if(allowed.has(column)||!/(id|code|number|no|email)$/i.test(column)&&distinct/Math.max(1,present.length)<.95)return [];const groups=keyFor(present,[column]);return groups.length?[{column,reviewType:type,type:"Repeated values",label:"Repeated values",rows:groups.flatMap(group=>group.rows),recommendation:"duplicates",severity:"medium",summary:"Review whether these repeated values should be unique.",status:"open",unit:"rows",duplicateDefinition:{mode:"key",columns:[column]},count:groups.reduce((sum,group)=>sum+group.rows.length,0)}]:[];});}
    function groups(issue){const columns=issue.duplicateDefinition.columns,ids=new Set(issue.rows.map(row=>row._row)),raw=keyFor(state.rows.filter(row=>ids.has(row._row)),columns,exact);return raw.map(group=>({...group,different:exact?[]:state.headers.filter(column=>new Set(group.rows.map(row=>row[column])).size>1)})).sort((a,b)=>b.different.length-a.different.length);}
    function init(issue,session){if(session.locked===null)session.locked=groups(issue).map(group=>group.value);session.survivors ||= {};session.groupIndex ||= 0;session.visitedGroups ||= [];session.keepRule ||= {column:state.headers.find(column=>column!==issue.column)||issue.column,condition:"nonblank",value:""};if((session.fix||"").replace(/^ai:/,"")==="one-by-one"){const list=groups(issue).filter(group=>session.locked.includes(group.value));list.forEach(group=>{if(session.survivors[group.value]===undefined)session.survivors[group.value]=group.rows[0]._row;});session.groupIndex=Math.min(session.groupIndex,Math.max(0,list.length-1));const current=list[session.groupIndex];if(current&&!session.visitedGroups.includes(current.value))session.visitedGroups.push(current.value);}}
    function lockedGroups(issue,session){init(issue,session);return groups(issue).filter(group=>session.locked.includes(group.value));}
    function lockedRows(issue,session){let selected=lockedGroups(issue,session);if((session.fix||"").replace(/^ai:/,"")==="one-by-one"&&session.partialChoices)selected=selected.filter(group=>session.visitedGroups.includes(group.value));return selected.flatMap(group=>group.rows);}
    function count(issue){return exact?groups(issue).reduce((sum,group)=>sum+group.rows.length-1,0):groups(issue).reduce((sum,group)=>sum+group.rows.length,0);}
    function ruleMatches(rows,rule) {
      if(rule.condition==="nonblank")return rows.filter(row=>String(row[rule.column]??"").trim());
      if(rule.condition==="equals")return rows.filter(row=>row[rule.column]===rule.value);
      const dated=inferType(rule.column)==="Date",numeric=ReviewCore.numericType(rule.column),entries=rows.flatMap(row=>{try{if(!String(row[rule.column]??"").trim())return [];const value=dated?Date.parse(ReviewPageEngine.dateValue(row[rule.column],reviewDateFormats()[JSON.stringify([row._row,rule.column,row[rule.column]])] || columnPolicy(rule.column).dateFormat)):numeric?CleaningEngine.parseNumber(row[rule.column],columnPolicy(rule.column)):String(row[rule.column]);return [{row,value}];}catch{return [];}}),descending=["highest","latest"].includes(rule.condition);
      entries.sort((a,b)=>((typeof a.value==="number"?a.value-b.value:a.value.localeCompare(b.value))*(descending?-1:1))||a.row._row-b.row._row);
      return entries.length?entries.filter(entry=>entry.value===entries[0].value).map(entry=>entry.row):[];
    }
    function survivor(group,session,key){const complete=row=>state.headers.filter(column=>String(row[column]??"").trim()).length;if(key==="keep-last")return group.rows.at(-1);if(key==="keep-most-complete"||key==="merge")return [...group.rows].sort((a,b)=>complete(b)-complete(a)||a._row-b._row)[0];if(key==="one-by-one")return group.rows.find(row=>row._row===session.survivors[group.value]);if(key==="rule"){const rule=session.keepRule,matching=ruleMatches(group.rows,rule),eligible=matching.length?matching:group.rows;if(rule.tieBreak)return ruleMatches(eligible,rule.tieBreak)[0] || eligible[0];return eligible[0];}return group.rows[0];}
    function hasConflicts(issue,session){return lockedGroups(issue,session).filter(group=>group.different.length).length;}
    function compute(issue,session,key){if(key==="keep-all")return {operation:"retain",interpretation:"legitimate"};const list=lockedGroups(issue,session).filter(group=>key!=="one-by-one"||!session.partialChoices||session.visitedGroups.includes(group.value));if(key==="one-by-one"&&!session.partialChoices&&list.some(group=>!session.visitedGroups.includes(group.value)))throw new Error("Visit every locked group, or choose Apply choices so far.");const keepAll=list.filter(group=>session.survivors[group.value]==="all").flatMap(group=>group.rows.map(row=>row._row)),selected=list.filter(group=>!keepAll.includes(group.rows[0]._row)).map(group=>survivor(group,session,key)?._row).filter(Boolean);return {operation:key==="merge"?"mergeDuplicates":"deduplicate",survivor:"selected",survivorIds:selected,keepAllRows:keepAll,trimKeys:exact,acknowledgeConflicts:true,requiresConflictAcknowledgement:hasConflicts(issue,session)>0};}
    function ruleParams(issue,session){ // DUP-F-03: ties and unmatched groups are counted from the actual rule.
      const list=lockedGroups(issue,session),matches=list.map(group=>ruleMatches(group.rows,session.keepRule).length),clean=matches.filter(count=>count===1).length,ties=matches.filter(count=>count>1).length,none=matches.filter(count=>count===0).length;
      return `<div class="duplicate-rule-builder"><select id="duplicateRuleColumn" aria-label="Keep rule column">${state.headers.map(column=>`<option ${session.keepRule.column===column?"selected":""}>${escapeHtml(column)}</option>`).join("")}</select><select id="duplicateRuleCondition" aria-label="Keep rule condition">${[["nonblank","is not blank"],["highest","is highest"],["lowest","is lowest"],["latest","is latest"],["equals","equals value"]].map(([value,label])=>`<option value="${value}" ${session.keepRule.condition===value?"selected":""}>${label}</option>`).join("")}</select>${session.keepRule.condition==="equals"?`<input id="duplicateRuleValue" value="${escapeHtml(session.keepRule.value)}" aria-label="Rule value">`:""}<p>${list.length} groups use this rule. Applies cleanly to ${clean} groups · ${ties} groups tie → ${session.keepRule.tieBreak?"reviewed tie-break rule":"first kept"}${none?` · ${none} unmatched groups → first kept`:""}.</p></div>`;
    }
    function getFixOptions(issue,session){init(issue,session);const differing=hasConflicts(issue,session)>0,option=(key,label,more=false)=>({key,label,more,risk:key==="keep-all"?"Doesn't change values":"Removes data",compute:()=>compute(issue,session,key)});return [option(differing?"keep-most-complete":"keep-first",differing?"Keep most complete":"Keep first"),option("keep-last","Keep last"),option(differing?"keep-first":"keep-most-complete",differing?"Keep first":"Keep most complete"),...(!exact?[option("merge","Merge",true)]:[]),{...option("rule","Keep by rule",true),params:ruleParams},{...option("one-by-one","Choose per group",true),params:oneByOneContent},option("keep-all","Keep all")];}
    function reminder(issue,session){return `Fixing: ${lockedGroups(issue,session).length} repeated ${exact?"row":"value"} groups · ${lockedRows(issue,session).length} rows · ${hasConflicts(issue,session)} groups differ`;}
    function consequence(issue,session,preview,option){ // DUP-F-01, DUP-F-02
      const metric=ReviewCore.metricColumn(),removed=ReviewCore.total(preview.removedRows,metric),whole=ReviewCore.total(state.rows,metric),before=ReviewCore.total(state.rows,metric),after=ReviewCore.total(preview.after,metric),removedIds=new Set(preview.removedRows.map(row=>row._row));let differentRows=0,extra=0;
      if(metric)for(const group of lockedGroups(issue,session)){const kept=group.rows.find(row=>!removedIds.has(row._row));if(!kept)continue;for(const row of group.rows.filter(row=>removedIds.has(row._row))){try{const a=CleaningEngine.parseNumber(row[metric],columnPolicy(metric)),b=CleaningEngine.parseNumber(kept[metric],columnPolicy(metric));if(a!==b){differentRows++;extra+=a-b;}}catch{}}}
      return {sentence:option.key==="keep-all"?`All ${lockedRows(issue,session).length} repeated records stay in reports.`:`Removes ${preview.removedRows.length} rows holding ${ReviewCore.money(removed,metric)} (${(removed/Math.max(1,whole)*100).toFixed(1)}% of ${metric||"rows"}).`,figures:[{label:metric||"Total rows",before:ReviewCore.money(before,metric),after:ReviewCore.money(after,metric)},{label:"Row count",before:state.rows.length,after:preview.after.length}],reason:differentRows?`${differentRows} removed rows have different ${metric} than the kept row; totals differ by ${ReviewCore.money(extra,metric)} beyond pure duplicates.`:"Only the reviewed survivor policy removes records.",detail:option.key==="merge"?`Fills ${preview.patches.length} blank cells from agreeing duplicate values.`:""};}
    function context(issue,session){const list=groups(issue);return {column:issue.column,type,role:"text",headers:state.headers,columnTypes:Object.fromEntries(cleaningProfile().columns.map(column=>[column.column,column.role])),meaning:columnPolicy(issue.column).meaning,allowedFixes:getFixOptions(issue,session).map(option=>option.key),count:state.rows.length,affected:lockedRows(issue,session).length,values:list.slice(0,20).map(group=>({value:String(group.rows[0][issue.column]),count:group.rows.length,locked:session.locked.includes(group.value)})),samples:[],statistics:{},groups:list.slice(0,20).map(group=>({label:group.different.join(", ")||"identical",total:group.rows.length,missing:0})),exampleGroups:list.slice(0,session.tab==="fix"?3:5).map(group=>({count:group.rows.length,differingColumns:group.different,rows:group.rows.slice(0,3).map(row=>Object.fromEntries([...new Set([issue.column,...group.different.slice(0,3)])].map(column=>[column,String(row[column]??"").slice(0,500)])))}))};}
    async function aiExplore(issue,session){await ReviewCore.requestAi(issue,"explore",context(issue,session));}
    async function aiFix(issue,session){ // DUP-A-01: survivor rules stay proposals until their AI option is selected.
      const result=await ReviewCore.requestAi(issue,"fix",context(issue,session));if(result?.params?.keepRule)session.aiFixProposal={...result,operation:"rule"};else if(result?.operation)session.aiFixProposal=result;renderPreservingReviewFocus();
    }
    function bind(issue,session){init(issue,session);document.getElementById("duplicateYes")?.addEventListener("click",()=>ReviewCore.accept(issue,{repeatableColumn:issue.column}));document.getElementById("duplicateNo")?.addEventListener("click",()=>{session.uniqueConfirmed=true;renderPreservingReviewFocus();});document.getElementById("duplicateShortcut")?.addEventListener("click",()=>{session.fix="keep-first";ReviewCore.switchTab(issue,"fix");});document.querySelectorAll("[data-duplicate-group]").forEach(input=>input.onchange=()=>{const before=lockedRows(issue,session).length,key=input.dataset.duplicateGroup;session.locked=input.checked?session.locked.concat(key):session.locked.filter(value=>value!==key);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});document.getElementById("duplicateConflictAck")?.addEventListener("change",event=>{session.acknowledgeConflicts=event.target.checked;renderPreservingReviewFocus();});[["duplicateRuleColumn","column"],["duplicateRuleCondition","condition"],["duplicateRuleValue","value"]].forEach(([id,key])=>document.getElementById(id)?.addEventListener("change",event=>{session.keepRule[key]=event.target.value;ReviewCore.compute(issue);}));document.querySelectorAll("[data-survivor]").forEach(button=>button.onclick=()=>{session.survivors[button.dataset.survivorGroup]=Number(button.dataset.survivor);ReviewCore.compute(issue);});document.getElementById("duplicatePrevious")?.addEventListener("click",()=>{session.groupIndex--;renderPreservingReviewFocus();});document.getElementById("duplicateNext")?.addEventListener("click",()=>{session.groupIndex++;renderPreservingReviewFocus();});document.getElementById("duplicateKeepGroup")?.addEventListener("click",()=>{session.survivors[lockedGroups(issue,session)[session.groupIndex].value]="all";ReviewCore.compute(issue);});document.getElementById("duplicateApplyChoices")?.addEventListener("click",()=>{session.partialChoices=true;ReviewCore.compute(issue);});document.getElementById("duplicateAiExplore")?.addEventListener("click",()=>aiExplore(issue,session));if(session.tab==="fix"&&hasConflicts(issue,session)&&session.fix!=="keep-all"&&!session.acknowledgeConflicts)document.getElementById("reviewApply").disabled=true;}
    function bindExtras(issue,session){bind(issue,session);document.querySelectorAll("[data-duplicate-more-rows]").forEach(button=>button.onclick=()=>{session.groupRowLimits ||= {};const key=button.dataset.duplicateMoreRows;session.groupRowLimits[key]=(session.groupRowLimits[key] || 50)+50;renderPreservingReviewFocus();});
      const builder=document.querySelector(".duplicate-rule-builder"),tie=session.keepRule.tieBreak;
      if(builder&&tie){const line=document.createElement("p"),remove=document.createElement("button");line.textContent=`Then ${tie.column} ${tie.condition}${tie.condition==="equals"?` ${tie.value}`:""}. Unresolved ties keep the first source row.`;remove.className="text-button";remove.textContent="Remove tie-break rule";remove.onclick=()=>{delete session.keepRule.tieBreak;ReviewCore.compute(issue);};builder.append(line,remove);}
      for(const id of ["duplicatePrevious","duplicateNext"]) {const button=document.getElementById(id);if(button)button.onclick=()=>ReviewCore.compute(issue);}
    }
    function decisionMetadata(issue,session){const chosen=new Set(lockedRows(issue,session).map(row=>row._row));return {duplicateGroups:lockedGroups(issue,session).filter(group=>group.rows.some(row=>chosen.has(row._row))).map(group=>({label:exact?"Exact copy group":String(group.rows[0][issue.column]),rowIds:group.rows.map(row=>row._row)}))};}
    function groupTable(issue,group,{keep=false,preview}={}){
      const fields=[...new Set([issue.column,...group.different,...state.headers.filter(column=>column!==issue.column).slice(0,3)])],removed=new Set(preview?.removedRows.map(row=>row._row)||[]),columns=[{key:"row",label:"Row",numeric:true},...fields.map(column=>({key:column,label:column})),...(keep?[{key:"choice",label:"Keep"}]:[])];
      const rows=group.rows.slice(0,50).map(row=>({row:row._row,...Object.fromEntries(fields.map(column=>[column,{value:row[column]||"—",raw:true,problem:group.different.includes(column),removed:removed.has(row._row)}])),...(keep?{choice:{control:`<button class="text-button" data-survivor="${row._row}" data-survivor-group="${escapeHtml(group.value)}">Keep this row</button>`}}:{})}));
      return ReviewComponents.table({columns,rows,card:false});
    }
    function oneByOneContent(issue,session){ // DUP-F-04 / C7 nested data, not a nested card.
      const list=lockedGroups(issue,session),index=Math.min(session.groupIndex,list.length-1),group=list[index];if(!group)return "No duplicate groups remain.";
      return `<div data-ui="review.fix.one-by-one"><p>Group ${index+1} of ${list.length}</p>${groupTable(issue,group,{keep:true})}${index>0?'<button class="text-button" id="duplicatePrevious">Previous</button>':"First group"} ${index<list.length-1?'<button class="text-button" id="duplicateNext">Next</button>':"Last group"} <button class="text-button" id="duplicateKeepGroup">Keep all in this group</button><button class="text-button" id="duplicateApplyChoices">Apply choices so far</button></div>`;
    }
    function exploreContent(issue,session){ // DUP-E-01…12 / T1 C1 + C3 + C4.
      init(issue,session);const c=ReviewComponents,list=groups(issue),same=list.filter(group=>!group.different.length).length;
      if(!exact&&!session.uniqueConfirmed)return {lead:`Can values in ${issue.column} repeat?`,sub:`${list.length} values repeat across ${count(issue)} ${c.noun()}.`,selection:`<div class="rc-more" data-ui="review.explore.dup-values.question"><button class="text-button" id="duplicateYes">Yes, that's normal</button><button class="text-button" id="duplicateNo">No, they should be unique</button></div>`,evidence:"",selectionTitle:"Decide whether repeats are expected"};
      const items=list.slice(0,200).map((group,index)=>({value:exact?`Copy group ${index+1}`:group.rows[0][issue.column],count:group.rows.length,share:exact?`×${group.rows.length}`:`${(group.rows.length/state.rows.length*100).toFixed(1)}%`,meta:group.different.length?`differs in ${escapeHtml(group.different.slice(0,3).join(", "))}`:"identical",ui:exact?"review.explore.dup-rows.group":"review.explore.dup-values.group",attrs:{"data-group":group.value},control:`<input type="checkbox" data-duplicate-group="${escapeHtml(group.value)}" ${session.locked.includes(group.value)?"checked":""} aria-label="Select this duplicate group">`,details:groupTable(issue,group),open:index<3}));
      return {lead:exact?`Which of these ${count(issue)} exact copies should be removed?`:`Which repeated ${issue.column} values refer to the same ${c.noun()}?`,sub:`${same} groups identical; ${list.length-same} groups differ in other columns.`,selection:c.selection(items,{ui:exact?"review.explore.dup-rows.groups":"review.explore.dup-values.groups",total:`${lockedRows(issue,session).length} rows selected`,ai:exact?"":`<button class="text-button" id="duplicateAiExplore">Are these real duplicates? AI</button>${session.aiRequested?ReviewCore.aiStatus(issue):""}${session.ai?`<p>${c.text(session.ai.note)}</p>`:""}`}),evidence:exact?'<button class="text-button" id="duplicateShortcut">Remove all exact copies</button>':c.headline("Review differing cells before choosing which copy to keep."),evidenceTitle:"Compare the copies"};
    }
    function fixContent(issue,session,preview,option){ // DUP-F-05 / C6: changed row counts, no redundant chart.
      return {metrics:[{label:"Rows",value:`${state.rows.length} → ${preview.after.length}`},{label:"Rows removed",value:preview.removedRows.length},{label:"Cells merged",value:preview.patches.length}],examples:lockedGroups(issue,session).slice(0,5).map(group=>groupTable(issue,group,{preview})).join(""),text:option.key==="keep-all"?"No values or rows change.":"Removed copies are struck through; all other values stay in the kept copy."};
    }
    function reviewContent(issue,decision){ // DUP-R-01…03 / C6 + C4
      const before=decision.reviewImpact.beforeRows,after=decision.reviewImpact.afterRows,removed=new Set(decision.removedRows.map(row=>row._row)),list=decision.reviewSpec.duplicateGroups||[],metric=decision.reviewSpec.metric;
      const rows=list.slice(0,5).map(group=>({group:{value:group.label,raw:true},kept:group.rowIds.filter(id=>!removed.has(id)).join(", "),removed:{value:group.rowIds.filter(id=>removed.has(id)).join(", ")||"None",removed:true}}));
      return {lead:`${decision.removedRows.length} repeated ${ReviewComponents.noun()} removed.`,sub:`${decision.reviewSpec.label} · ${new Date(decision.createdAt).toLocaleTimeString()} · ${decision.note||"No note"}`,count:decision.rows.length,change:{metrics:[{label:"Rows",value:`${before.length} → ${after.length}`},{label:"Groups resolved",value:list.length},{label:"Cells merged",value:decision.patches.length},{label:metric||"Row total",value:`${ReviewCore.money(ReviewCore.total(before,metric),metric)} → ${ReviewCore.money(ReviewCore.total(after,metric),metric)}`}]},examples:ReviewComponents.table({columns:[{key:"group",label:"Group"},{key:"kept",label:"Kept rows"},{key:"removed",label:"Removed rows"}],rows,ui:"review.review.sample"})};
    }
    return {detect,init,count,unit:"rows",groups,lockedRows,hasConflicts,exploreContent,fixContent,reviewContent,renderExplore:(issue,session)=>ReviewComponents.explore(issue,exploreContent(issue,session)),getFixOptions,reminder,consequence,aiExplore,aiFix,decisionMetadata,bind:bindExtras};
  }
  ReviewModules["duplicate-values"]=build("duplicate-values");ReviewModules["duplicate-rows"]=build("duplicate-rows");
})();
