// FMT-D-01, FMT-D-02, FMT-D-03, FMT-D-04, FMT-D-05: independent pattern/type/scale contracts.
(() => {
  const datePatterns=value=>{const v=String(value).trim();return /^\d{4}-\d{2}-\d{2}T/.test(v)?"ISO with time":/^\d{4}\/\d{2}\/\d{2}$/.test(v)?"YYYY/MM/DD":/^\d{1,2}-[A-Za-z]{3}-\d{4}$/.test(v)?"D-Mon-YYYY":/^[A-Za-z]+ \d{1,2}, \d{4}$/.test(v)?"Mon D, YYYY":/^\d{5}$/.test(v)&&Number(v)>=20000&&Number(v)<=60000?"Excel serial":ReviewPageEngine.pattern(v,true);};
  const numberPatterns=value=>{const v=String(value).trim();return /^[+-]?\d+(?:\.\d+)?e[+-]?\d+$/i.test(v)?"scientific":/\d\s*(?:kg|k|M)$/.test(v)?"with unit suffix":/[$€£¥]/.test(v)?"with currency symbol":/\d\.\d{3},\d+|^\d+,\d{1,2}$/.test(v)?"decimal comma":/\d,\d{3}/.test(v)?"thousands separator":/%$/.test(v)?"with %":(()=>{try{CleaningEngine.parseNumber(v);return "plain";}catch{return "text";}})();};
  function parseDate(value,source="mdy"){const v=String(value).trim();try{if(v.includes("T")){const [head,time]=v.split("T"),day=ReviewPageEngine.dateValue(head,source),parsed=Date.parse(`${day}T${time}`);if(!Number.isFinite(parsed))throw new Error("invalid time");return new Date(parsed).toISOString();}return ReviewPageEngine.dateValue(v,source);}catch{throw new Error("not a real date");}}
  function parseNumber(value,percent=true){const pattern=numberPatterns(value),v=String(value).trim();if(pattern==="with unit suffix"){const match=/^([+-]?\d+(?:\.\d+)?)\s*(kg|k|M)$/.exec(v);if(!match)throw new Error("cannot read this number");return Number(match[1])*({kg:1,k:1000,M:1000000})[match[2]];}const parsed=CleaningEngine.parseNumber(v,{numberFormat:pattern==="decimal comma"||/\d\.\d{3},\d+/.test(v)?"decimalComma":pattern==="scientific"?"plain":"decimalPoint",currency:true,percentage:true});return parsed*(pattern==="with %"&&!percent?100:1);}
  function scaleClusters(rows,column){const entries=rows.flatMap(row=>{try{const value=CleaningEngine.parseNumber(row[column]);return value>0?[{row,value}]:[];}catch{return [];}}).sort((a,b)=>a.value-b.value);let largest=0,index=-1;for(let i=1;i<entries.length;i++){const gap=Math.log10(entries[i].value)-Math.log10(entries[i-1].value);if(gap>largest){largest=gap;index=i;}}if(index<1||largest<1.3)return null;const groups=[entries.slice(0,index),entries.slice(index)],medians=groups.map(group=>CleaningEngine.stats(group.map(entry=>entry.value)).median),ratio=medians[1]/medians[0],factor=Math.abs(Math.log10(ratio)-2)<=.35?100:Math.abs(Math.log10(ratio)-3)<=.35?1000:null;if(!factor)return null;return {groups:groups.map((group,index)=>({key:index===0?"low":"high",rows:group.map(entry=>entry.row),stats:CleaningEngine.stats(group.map(entry=>entry.value))})),factor,minority:groups[0].length<=groups[1].length?"low":"high"};}
  function build(type){
    function date(issue){return issue.date||cleaningProfile().columns.find(profile=>profile.column===issue.column)?.role==="date";}
    function detect(dataset){return dataset.headers.flatMap(column=>{const profile=dataset.profile.columns.find(profile=>profile.column===column),present=dataset.rows.filter(row=>String(row[column]??"").trim()),isDate=profile.role==="date"||/date|timestamp|dob/i.test(column)&&present.some(row=>datePatterns(row[column])!=="text"),numeric=["number","integer"].includes(profile.role),shapes=ReviewPageEngine.frequencies(present,column,value=>isDate?datePatterns(value):numberPatterns(value));if(type==="scale"){if(!numeric||!/pct|percent|rate|ratio|ctr|usd|price|amount|cents/i.test(column))return [];const scale=scaleClusters(present,column);if(!scale)return [];const cells=scale.groups.find(group=>group.key===scale.minority).rows;return [{column,reviewType:type,type:"Mixed units / scale",label:"Mixed units / scale",rows:cells,recommendation:"manual",status:"open",severity:"medium",summary:"Two magnitude clusters may use different scales.",scale,date:false,unit:"cells"}];}if(type==="format"){const readable=shapes.filter(group=>group.value!=="text");if(readable.length<2||!isDate&&!numeric&&!readable.some(group=>group.value!=="plain"))return [];return [{column,reviewType:type,type:"Format mismatch",label:"Format mismatch",rows:present,recommendation:"manual",status:"open",severity:"medium",summary:"The same kind of value is written in different shapes.",date:isDate,unit:"cells"}];}const parsed=present.filter(row=>{try{isDate?parseDate(row[column]):parseNumber(row[column]);return true;}catch{return false;}});if(parsed.length/Math.max(1,present.length)<.9||parsed.length===present.length)return [];const ids=new Set(parsed.map(row=>row._row));return [{column,reviewType:type,type:"Wrong type",label:"Wrong type",rows:present.filter(row=>!ids.has(row._row)),recommendation:"manual",status:"open",severity:"medium",summary:"These cells do not fit the column’s dominant type.",date:isDate,unit:"cells"}];});}
    function patterns(issue){return ReviewPageEngine.frequencies(state.rows.filter(row=>String(row[issue.column]??"").trim()),issue.column,value=>date(issue)?datePatterns(value):numberPatterns(value));}
    const targetFormats={"YYYY-MM-DD":"iso","M/D/YYYY":"mdy","D/M/YYYY":"dmy","DD.MM.YYYY":"dotted","D-Mon-YYYY":"mon","Mon D, YYYY":"long","YYYY/MM/DD":"ymdSlash","ISO with time":"iso","Excel serial":"excel"};
    function init(issue,session){
      if(session.locked===null){
        if(type==="scale")session.locked=issue.scale?[issue.scale.minority]:[];
        else{
          const list=patterns(issue),readable=list.filter(group=>group.value!=="text");
          session.target=readable[0]?.value||list[0]?.value||"";
          // FMT-E-02: the selected pattern and conversion target describe the same output.
          session.targetFormat=date(issue)?targetFormats[session.target]||"iso":"number";
          session.locked=list.filter(group=>group.value!==session.target||group.value==="text").map(group=>group.value);
          if(type==="type-mismatch")session.locked=[...new Set(issue.rows.map(row=>date(issue)?datePatterns(row[issue.column]):numberPatterns(row[issue.column])))];
        }
      }
      if(!session.sourceDate){const mdy=state.rows.filter(row=>/^\d{1,2}[/-]\d{1,2}[/-]\d{4}$/.test(row[issue.column])&&Number(row[issue.column].split(/[/-]/)[1])>12).length,dmy=state.rows.filter(row=>/^\d{1,2}[/-]\d{1,2}[/-]\d{4}$/.test(row[issue.column])&&Number(row[issue.column].split(/[/-]/)[0])>12).length;session.sourceDate=dmy>mdy?"dmy":"mdy";}
      if(session.percent===undefined)session.percent=true;session.excludeParsed ||= [];session.keepTime ??= patterns(issue).some(group=>group.value==="ISO with time");
    }
    function exploreRows(issue,session){init(issue,session);if(type==="scale")return (issue.scale?.groups||[]).filter(group=>session.locked.includes(group.key)).flatMap(group=>group.rows);const eligible=type==="type-mismatch"?new Set(issue.rows.map(row=>row._row)):null;return state.rows.filter(row=>(!eligible||eligible.has(row._row))&&session.locked.includes(date(issue)?datePatterns(row[issue.column]):numberPatterns(row[issue.column])));}
    function unreadable(issue,session){return exploreRows(issue,session).filter(row=>{try{date(issue)?parseDate(row[issue.column],session.sourceDate):parseNumber(row[issue.column],session.percent);return false;}catch{return true;}});}
    function lockedRows(issue,session){const rows=exploreRows(issue,session),key=(session.fix||"").replace(/^ai:/,"");if(["set-missing","ai-parse"].includes(key)){const bad=unreadable(issue,session);return key==="ai-parse"&&session.parsedMapping?bad.filter(row=>Object.hasOwn(session.parsedMapping,row[issue.column])&&!session.excludeParsed.includes(row[issue.column])):bad;}return rows;}
    function count(issue){return type==="scale"?issue.scale?.groups.find(group=>group.key===issue.scale.minority)?.rows.length || issue.rows.length:issue.rows.length;}
    function ambiguities(issue){return date(issue)?state.rows.filter(row=>{const value=String(row[issue.column]);if(!/^\d{1,2}[/-]\d{1,2}[/-]\d{4}$/.test(value))return false;try{CleaningEngine.parseDate(value,"mdy");CleaningEngine.parseDate(value,"dmy");return true;}catch{return false;}}):[];}
    function conversion(issue,session){const mapping=Object.create(null),blocked=[];for(const row of lockedRows(issue,session)){const raw=row[issue.column];try{if(date(issue)){const iso=parseDate(raw,session.sourceDate),day=iso.slice(0,10),time=session.keepTime?iso.slice(10):"";mapping[raw]=session.targetFormat==="iso"?(session.keepTime?iso:day):ReviewPageEngine.renderDate(day,session.targetFormat)+time;}else mapping[raw]=String(parseNumber(raw,session.percent));}catch(error){blocked.push({rowId:row._row,reason:error.message});}}return {operation:"valueMap",mapping,parseBlocked:blocked,...(date(issue)?{convertedDates:true,targetFormat:session.targetFormat,sourceDate:session.sourceDate,roleOverride:"date"}:{roleOverride:"number"})};}
    function getFixOptions(issue,session){
      init(issue,session);
      if(type==="scale")return [{key:"to-majority",label:"Match the majority scale",risk:"Estimates values",compute:()=>({operation:"valueMap",mapping:Object.fromEntries(exploreRows(issue,session).map(row=>[row[issue.column],issue.scale.groups.find(group=>group.key===issue.scale.minority).rows.some(member=>member._row===row._row)?String(Number((CleaningEngine.parseNumber(row[issue.column],columnPolicy(issue.column))*(issue.scale.minority==="low"?issue.scale.factor:1/issue.scale.factor)).toFixed(ReviewCore.precision(issue.column)))):row[issue.column]])),roleOverride:"number"})},{key:"custom-factor",label:"Multiply by…",risk:"Estimates values",params:()=>`<input id="formatFactor" type="number" step="any" value="${escapeHtml(session.factor??1)}" aria-label="Scaling factor">`,compute:()=>{if(!String(session.factor??1).trim())throw new Error("Enter a finite scaling factor.");return {operation:"scale",factor:String(session.factor??1)};}},{key:"keep",label:"Keep as is",risk:"Doesn't change values",compute:()=>({operation:"retain",interpretation:"legitimate"})}];
      const standard={key:date(issue)?"to-target":"to-number",label:date(issue)?`Convert to ${session.targetFormat==="iso"?"YYYY-MM-DD":session.targetFormat}`:"Convert to plain number",risk:"Doesn't invent information",params:()=>date(issue)?`<label>Ambiguous source dates<select id="formatSource"><option value="mdy" ${session.sourceDate==="mdy"?"selected":""}>Month first</option><option value="dmy" ${session.sourceDate==="dmy"?"selected":""}>Day first</option></select></label>${patterns(issue).some(group=>group.value==="ISO with time")?`<label><input id="formatKeepTime" type="checkbox" ${session.keepTime?"checked":""}> Keep time part</label>`:""}`:`<label><input id="formatPercent" type="checkbox" ${session.percent?"checked":""}> Divide percent signs by 100</label>`,compute:()=>conversion(issue,session)};
      return [standard,...(ambiguities(issue).length?[{key:"assume-mdy",label:"Ambiguous: month first",risk:"Estimates values",compute:()=>{session.sourceDate="mdy";return conversion(issue,session);}},{key:"assume-dmy",label:"Ambiguous: day first",risk:"Estimates values",compute:()=>{session.sourceDate="dmy";return conversion(issue,session);}}]:[]),{key:"ai-parse",label:"Read the rest with AI",risk:"Estimates values",compute:async()=>{if(!session.parsedMapping&&!session.parseRequested){session.parseRequested=true;await aiFix(issue,session);}return {operation:"valueMap",mapping:Object.fromEntries(Object.entries(session.parsedMapping||{}).filter(([value])=>!session.excludeParsed.includes(value))),...(date(issue)?{convertedDates:true,targetFormat:"iso",roleOverride:"date"}:{roleOverride:"number"})};}},{key:"set-missing",label:"Unreadable → missing",risk:"Doesn't invent information",compute:()=>({operation:"missing",interpretation:"missing"})},{key:date(issue)?"keep":"keep-as-text",label:date(issue)?"Keep as is":"Keep as text",risk:"Doesn't change values",compute:()=>({operation:date(issue)?"retain":"toText",interpretation:"legitimate",...(date(issue)?{}:{roleOverride:"text"})})}];
    }
    function reminder(issue,session){return `Fixing: ${lockedRows(issue,session).length} ${date(issue)?"dates":"values"} in ${issue.column} → ${session.targetFormat||"majority scale"}`;}
    function consequence(issue,session,preview,option){ // FMT-F-01
      const before=CleaningEngine.stats(ReviewCharts.numeric(state.rows,issue.column)),after=CleaningEngine.stats(ReviewCharts.numeric(preview.after,issue.column)),key=option.key.replace(/^ai:/,"");
      if(date(issue)) {const old=monthRows(state.rows,issue.column,true),next=monthRows(preview.after,issue.column),a=new Map(ReviewPageEngine.frequencies(old,issue.column).map(group=>[group.value,group.rows.length])),b=new Map(ReviewPageEngine.frequencies(next,issue.column).map(group=>[group.value,group.rows.length])),months=[...new Set([...a.keys(),...b.keys()])].filter(month=>(a.get(month)||0)!==(b.get(month)||0));return {sentence:key==="set-missing"?`${preview.patches.length} unreadable dates become missing.`:`${preview.patches.length} dates become ${session.targetFormat||"YYYY-MM-DD"}; ${preview.blocked.length} unreadable values stay unchanged.`,figures:[{label:"Countable dates",before:old.length,after:next.length}],detail:months.slice(0,3).map(month=>`${month}: ${a.get(month)||0} → ${b.get(month)||0} countable records`).join(" · "),reason:key.startsWith("assume")?"Ambiguous day and month are interpreted by your explicit choice.":"Changes representation without inventing an observation."};}
      return {sentence:key==="set-missing"?`${preview.patches.length} unreadable values become missing.`:key==="keep-as-text"?"Keeps the source representations and treats this column as text.":type==="scale"?`${preview.patches.length} values match the selected scale.`:`${preview.patches.length} values become numbers; formerly unreadable values remain blocked.`,figures:[{label:"Mean",before:ReviewCore.format(before.mean,issue.column),after:ReviewCore.format(after.mean,issue.column)},{label:"Column sum",before:ReviewCore.format(ReviewCore.total(state.rows,issue.column),issue.column),after:ReviewCore.format(ReviewCore.total(preview.after,issue.column),issue.column)}],reason:key==="ai-parse"?"AI reads uncertain strings; low-confidence proposals are left unchanged.":"Only the locked patterns or magnitude cluster are converted."};}
    function monthRows(rows,column,accepted=false,policy=columnPolicy(column)){return rows.flatMap(row=>{try{const format=reviewDateFormats()[JSON.stringify([row._row,column,row[column]])],value=accepted?(format?ReviewPageEngine.dateValue(row[column],format):CleaningEngine.parseDate(row[column],policy.dateFormat)):parseDate(row[column]);return [{...row,[column]:value.slice(0,7)}];}catch{return [];}});}
    function context(issue,session){const unreadable=patterns(issue).find(group=>group.value==="text");return {column:issue.column,type,role:date(issue)?"date":"number",headers:state.headers,meaning:columnPolicy(issue.column).meaning,allowedFixes:getFixOptions(issue,session).map(option=>option.key),count:state.rows.length,affected:lockedRows(issue,session).length,values:ReviewPageEngine.frequencies(unreadable?.rows||lockedRows(issue,session),issue.column).slice(0,200).map(group=>({value:group.value,count:group.rows.length,locked:true})),samples:state.rows.filter(row=>date(issue)?datePatterns(row[issue.column])!=="text":numberPatterns(row[issue.column])!=="text").slice(0,10).map(row=>String(row[issue.column])),statistics:{},groups:[],today:new Date().toISOString().slice(0,10),targetFormat:session.targetFormat};}
    async function aiExplore(issue,session){ // FMT-A-02: scale advice receives the actual two-cluster summaries.
      const summary=context(issue,session);if(type==="scale"){summary.values=[];summary.samples=[];summary.groups=issue.scale.groups.map(group=>({label:`${group.key} cluster · factor ${issue.scale.factor}`,total:group.rows.length,missing:0,statistics:group.stats}));}
      await ReviewCore.requestAi(issue,"explore",summary);
    }
    async function aiFix(issue,session){const result=await ReviewCore.requestAi(issue,"parse",context(issue,session));if(result?.mapping){session.parsedMapping=result.mapping;session.parsedConfidence=result.confidences || {};session.parseRequested=true;session.aiFixProposal={...result,operation:"ai-parse",reason:"Read uncertain strings with AI"};renderPreservingReviewFocus();}}
    function bind(issue,session){document.querySelectorAll("[data-format-pattern]").forEach(input=>input.onchange=()=>{const before=lockedRows(issue,session).length,value=input.dataset.formatPattern;session.locked=input.checked?session.locked.concat(value):session.locked.filter(current=>current!==value);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});document.querySelectorAll("[data-target-pattern]").forEach(input=>input.onchange=()=>{session.target=input.dataset.targetPattern;session.locked=patterns(issue).filter(group=>group.value!==session.target).map(group=>group.value);session.preview=null;renderPreservingReviewFocus();});document.querySelectorAll("[data-scale-cluster]").forEach(input=>input.onchange=()=>{session.locked=input.checked?session.locked.concat(input.dataset.scaleCluster):session.locked.filter(value=>value!==input.dataset.scaleCluster);session.preview=null;renderPreservingReviewFocus();});document.getElementById("formatTarget")?.addEventListener("change",event=>{session.targetFormat=event.target.value;session.preview=null;renderPreservingReviewFocus();});document.getElementById("formatSource")?.addEventListener("change",event=>{session.sourceDate=event.target.value;ReviewCore.compute(issue);});document.getElementById("formatPercent")?.addEventListener("change",event=>{session.percent=event.target.checked;ReviewCore.compute(issue);});document.getElementById("formatFactor")?.addEventListener("change",event=>{session.factor=event.target.value;ReviewCore.compute(issue);});document.getElementById("formatScaleAi")?.addEventListener("click",()=>aiExplore(issue,session));document.querySelectorAll("[data-ai-parsed]").forEach(input=>input.onchange=()=>{const value=input.dataset.aiParsed;session.excludeParsed=input.checked?session.excludeParsed.filter(current=>current!==value):session.excludeParsed.concat(value);ReviewCore.compute(issue);});}
    function invalidate(session){session.parsedMapping=null;session.parsedConfidence=null;session.parseRequested=false;}
    const typedDetect=dataset=>detect(dataset).filter(issue=>{const policy=dataset.profile.columns.find(column=>column.column===issue.column)?.policy;return !["text","category","identifier","boolean"].includes(policy?.role);});
    function exploreContent(issue,session){ // FMT-E-01…07 / C3 selection + C5 target + C4 evidence.
      init(issue,session);const c=ReviewComponents,list=patterns(issue),selectionRows=type==="scale"?issue.scale.groups.map(group=>({value:`${ReviewCore.format(group.stats.min,issue.column)}–${ReviewCore.format(group.stats.max,issue.column)}`,count:group.rows.length,share:`${(group.rows.length/state.rows.length*100).toFixed(1)}%`,meta:`median ${ReviewCore.format(group.stats.median,issue.column)}`,control:`<input type="checkbox" data-scale-cluster="${group.key}" ${session.locked.includes(group.key)?"checked":""}>`,ui:"review.explore.scale.clusters"})):list.map(group=>({value:group.value,count:group.rows.length,share:`${(group.rows.length/state.rows.length*100).toFixed(1)}%`,control:`<input type="checkbox" data-format-pattern="${escapeHtml(group.value)}" ${session.locked.includes(group.value)?"checked":""}>`,extra:`<span>${escapeHtml(group.rows.slice(0,3).map(row=>row[issue.column]).join(" · "))}</span>`,meta:type==="type-mismatch"?"review the value":`<label><input type="radio" name="formatTargetPattern" data-target-pattern="${escapeHtml(group.value)}" ${session.target===group.value?"checked":""}>Target</label>`,ui:"review.explore.format.pattern",attrs:{"data-pattern":group.value}}));
      const target=date(issue)?[["iso","YYYY-MM-DD"],["mdy","MM/DD/YYYY"],["dmy","DD/MM/YYYY"],["mon","DD-Mon-YYYY"],["ymdSlash","YYYY/MM/DD"],["dotted","DD.MM.YYYY"],["long","Mon D, YYYY"],["excel","Excel serial"]]:[["number","Plain number"]];
      const controls=type==="scale"?'<button class="text-button" id="formatScaleAi">Which scale is right? AI</button>':`<select id="formatTarget" aria-label="Target format">${target.map(([value,label])=>`<option value="${value}" ${session.targetFormat===value?"selected":""}>${label}</option>`).join("")}</select>`;
      const examples=type==="type-mismatch"?issue.rows.slice(0,5):unreadable(issue,session).slice(0,200),columns=[{key:"row",label:"Row",numeric:true},{key:"value",label:"Source value"}];
      const ambiguous=ambiguities(issue),mdy=state.rows.filter(row=>/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(row[issue.column])&&Number(row[issue.column].split("/")[1])>12).length;
      const headlineText=type==="scale"?`The two clusters are about ×${issue.scale.factor} apart; review which scale matches the column's meaning.`:ambiguous.length?`${ambiguous.length} dates could mean month/day or day/month; ${mdy} values with a day above 12 support month-first reading.`:`${examples.length} source values cannot be read confidently; inspect them before choosing a conversion.`;
      let visual="";if(type==="scale"){const values=issue.scale.groups.flatMap(group=>group.rows.map(row=>CleaningEngine.parseNumber(row[issue.column]))),min=Math.log10(Math.min(...values)),max=Math.log10(Math.max(...values));visual=`<svg viewBox="0 0 600 100" role="img" aria-label="Scale clusters on a log axis">${issue.scale.groups.map((group,index)=>group.rows.map(row=>`<circle cx="${30+(Math.log10(CleaningEngine.parseNumber(row[issue.column]))-min)/(max-min||1)*540}" cy="${index?60:30}" r="3" fill="${group.key===issue.scale.minority?"#E07B39":"#C9CFD8"}"/>`).join("")).join("")}</svg>`;}
      return {lead:type==="scale"?`Which scale should these ${count(issue)} values use?`:`How should the values in ${issue.column} be written?`,sub:`${ReviewCore.count(count(issue),"values")} need review.`,controls:type==="scale"?"":c.toolbar("Target format",controls),controlsTitle:"Choose the intended format",selection:c.selection(selectionRows,{ui:type==="scale"?"review.explore.scale.clusters":"review.explore.format.patterns",total:`${exploreRows(issue,session).length} values selected`,ai:session.aiRequested?ReviewCore.aiStatus(issue):""}),evidence:(type==="scale"?c.toolbar("Scale",controls):"")+c.headline(headlineText)+(type==="scale"?c.change({visual}):c.table({columns,rows:examples.map(row=>({row:row._row,value:{value:row[issue.column],raw:true,problem:true}})),ui:type==="type-mismatch"?"review.explore.type.values":"review.explore.format.unparseable",empty:ambiguous.length?"Choose the month/day interpretation in the selected conversion option.":"Every selected value has a readable pattern."})),evidenceTitle:type==="scale"?"Inspect the scale gap":"Values that need a closer look"};
    }
    function fixContent(issue,session,preview,option){ // FMT-F-02, FMT-F-03 / C6 example pairs.
      const rows=patterns(issue).flatMap(group=>{const patch=preview.patches.find(patch=>group.rows.some(row=>row._row===patch.rowId));return patch?[{pattern:group.value,before:{value:patch.before,raw:true},after:{value:patch.after,raw:true}}]:[];});
      const controls=option.key.replace(/^ai:/,"")==="ai-parse"?Object.entries(session.parsedMapping||{}).map(([value,after])=>`<label><input type="checkbox" data-ai-parsed="${escapeHtml(value)}" ${session.excludeParsed.includes(value)?"":"checked"}>${escapeHtml(value)} → ${escapeHtml(after)} · AI ${session.parsedConfidence?.[value]??"confidence unavailable"}%</label>`).join(""):"";
      return {examples:ReviewComponents.table({columns:[{key:"pattern",label:"Pattern"},{key:"before",label:"Before"},{key:"after",label:"After"}],rows,card:false,empty:"No values change for this option."})+controls};
    }
    function reviewContent(issue,decision){ // FMT-R-01…03 / approved snapshot data, shared T3.
      const impact=decision.reviewImpact,a=impact.beforeRows,b=impact.afterRows,dated=decision.reviewSpec.targetRole==="date"||issue.date,shape=value=>dated?datePatterns(value):numberPatterns(value),patternsCount=rows=>ReviewPageEngine.frequencies(rows.filter(row=>String(row[issue.column]??"").trim()),issue.column,shape).length;
      const rows=decision.patches.slice(0,5).map(patch=>({row:patch.rowId,before:{value:patch.before,raw:true},after:{value:patch.after||"(blank)",raw:true}}));
      return {lead:`${decision.patches.length} values converted in ${issue.column}.`,sub:`${decision.reviewSpec.label} · ${new Date(decision.createdAt).toLocaleTimeString()} · ${decision.note||"No note"}`,count:decision.rows.length,change:{metrics:[{label:"Values converted",value:decision.patches.filter(patch=>patch.after.trim()).length},{label:"Values made blank",value:decision.patches.filter(patch=>!patch.after.trim()).length},{label:"Patterns",value:`${patternsCount(a)} → ${patternsCount(b)}`},{label:"Blocked values",value:decision.treatment.parseBlocked?.length||0}],visual:dated?ReviewCharts.categories(issue.column,monthRows(a,issue.column,true,decision.reviewSpec.targetPolicy),monthRows(b,issue.column),{changedOnly:true,title:"Monthly counts for the dates that became readable"}):ReviewCharts.histogram(issue.column,a,b,{patches:decision.patches,missingBefore:new Set(impact.beforeExcludedIds),missingAfter:new Set(impact.afterExcludedIds),snapshot:true,policy:decision.reviewSpec.targetPolicy})},examples:ReviewComponents.table({columns:[{key:"row",label:"Row",numeric:true},{key:"before",label:"Before"},{key:"after",label:"After"}],rows,ui:"review.review.sample"})};
    }
    function bindContent(issue,session){bind(issue,session);document.getElementById("formatKeepTime")?.addEventListener("change",event=>{session.keepTime=event.target.checked;ReviewCore.compute(issue);});const target=document.getElementById("formatTarget");if(target)target.onchange=()=>{session.targetFormat=target.value;session.target=patterns(issue).find(group=>date(issue)?targetFormats[group.value]===session.targetFormat:group.value==="plain")?.value||"";session.locked=patterns(issue).filter(group=>group.value!==session.target||group.value==="text").map(group=>group.value);session.preview=null;renderPreservingReviewFocus();};document.querySelectorAll("[data-target-pattern]").forEach(input=>input.addEventListener("change",()=>{session.targetFormat=date(issue)?targetFormats[input.dataset.targetPattern]||"iso":"number";session.preview=null;renderPreservingReviewFocus();}));}
    return {detect:typedDetect,init,count,unit:"cells",lockedRows,exploreRows,exploreContent,fixContent,reviewContent,renderExplore:(issue,session)=>ReviewComponents.explore(issue,exploreContent(issue,session)),getFixOptions,reminder,consequence,aiExplore,aiFix,invalidate,bind:bindContent,restoreMetadata:(issue,rows)=>{if(type==="scale"&&!issue.scale)issue.scale=scaleClusters(rows,issue.column);}};
  }
  ["format","type-mismatch","scale"].forEach(type=>{ReviewModules[type]=build(type);});
})();
