// LBL-D-01, LBL-D-02, LBL-D-03, LBL-D-04: deterministic equivalence and bounded spelling hypotheses.
ReviewModules["category-variants"] = (() => {
  const normalize=value=>String(value).normalize("NFD").replace(/\p{M}/gu,"").trim().toLowerCase().replace(/[_\-.,'\s]+/g,"");
  function distance(a,b){const table=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)table[i][0]=i;for(let j=0;j<=b.length;j++)table[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++){table[i][j]=Math.min(table[i-1][j]+1,table[i][j-1]+1,table[i-1][j-1]+(a[i-1]===b[j-1]?0:1));if(i>1&&j>1&&a[i-1]===b[j-2]&&a[i-2]===b[j-1])table[i][j]=Math.min(table[i][j],table[i-2][j-2]+1);}return table[a.length][b.length];}
  function clusters(rows,column){const values=ReviewPageEngine.frequencies(rows.filter(row=>String(row[column]??"").trim()),column),buckets=new Map();values.forEach(group=>{const key=normalize(group.value);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(group);});const groups=[...buckets].filter(([,values])=>values.length>1).map(([key,values])=>({key:`normal:${key}`,source:"same when normalized",canonical:values[0].value,values})),included=new Set(groups.flatMap(group=>group.values.map(value=>value.value)));for(const value of values){if(included.has(value.value))continue;const norm=normalize(value.value),match=values.find(other=>other.rows.length>value.rows.length && other.value!==value.value && !(normalize(other.value).replace(/\d/g,"")===norm.replace(/\d/g,"")&&/\d/.test(norm)) && distance(norm,normalize(other.value))<=Math.min(2,Math.floor(Math.max(norm.length,normalize(other.value).length)*.2)));if(match){let group=groups.find(group=>group.values.some(value=>value.value===match.value));if(!group){group={key:`near:${normalize(match.value)}`,source:"near match",canonical:match.value,values:[match]};groups.push(group);}group.values.push(value);included.add(value.value);included.add(match.value);}}return groups;}
  function detect(dataset){return dataset.headers.flatMap(column=>{const profile=dataset.profile.columns.find(profile=>profile.column===column),values=ReviewPageEngine.frequencies(dataset.rows,column);if(["number","integer","date","identifier"].includes(profile.role)||values.length>200&&values.length/dataset.rows.length>.2)return [];const groups=clusters(dataset.rows,column);if(!groups.length)return [];const changed=groups.flatMap(group=>group.values.filter(value=>value.value!==group.canonical).flatMap(value=>value.rows));return [{column,reviewType:"category-variants",type:"Inconsistent labels",label:"Inconsistent labels",rows:groups.flatMap(group=>group.values.flatMap(value=>value.rows)),recommendation:"manual",status:"open",severity:"medium",summary:"Equivalent spellings and possible near matches need a canonical name.",count:changed.length,unit:"cells"}];});}
  function list(issue,session){
    const base=clusters(state.rows,issue.column),ai=(session.aiClusters||[]).map((values,index)=>{const groups=ReviewPageEngine.frequencies(state.rows.filter(row=>values.includes(row[issue.column])),issue.column);return {key:`ai:${index}`,source:"AI synonym",canonical:session.aiCanon?.[index]||groups[0]?.value,reason:session.aiClusterReasons?.[index] || "",values:groups};}),frequencies=new Map(ReviewPageEngine.frequencies(state.rows,issue.column).map(group=>[group.value,group]));
    return base.concat(ai).map(group=>{const values=group.values.filter(value=>!session.detached?.includes(value.value)&&(!session.memberOverrides?.[value.value]||session.memberOverrides[value.value]===group.key)).concat(Object.entries(session.memberOverrides||{}).filter(([value,key])=>key===group.key&&!group.values.some(member=>member.value===value)).map(([value])=>frequencies.get(value)).filter(Boolean)).sort((a,b)=>b.rows.length-a.rows.length);return {...group,values,canonical:values.some(value=>value.value===group.canonical)?group.canonical:values[0]?.value};}).filter(group=>group.values.length>1);
  }
  function init(issue,session){session.detached ||= [];if(session.locked===null)session.locked=list(issue,session).filter(group=>group.source==="same when normalized").map(group=>group.key);session.canonical ||= {};}
  function lockedRows(issue,session){init(issue,session);if(["case-lower","case-title","case-upper","trim"].includes(session.fix.replace(/^ai:/,"")))return state.rows.filter(row=>String(row[issue.column]??"").trim());const values=new Set(list(issue,session).filter(group=>session.locked.includes(group.key)).flatMap(group=>group.values.map(value=>value.value)));return state.rows.filter(row=>values.has(row[issue.column]));}
  function count(issue){return list(issue,ReviewCore.data(issue)).reduce((sum,group)=>sum+group.values.filter(value=>value.value!==group.canonical).reduce((sum,value)=>sum+value.rows.length,0),0);}
  function renderExplore(issue,session){ // LBL-E-01, LBL-E-02, LBL-E-03, LBL-E-04, LBL-E-05
    init(issue,session);const groups=list(issue,session),all=ReviewPageEngine.frequencies(state.rows,issue.column);
    return `<section class="labels-explore" data-ui="review.explore.labels"><h2>${escapeHtml(issue.column)} · ${groups.length} groups of similar labels · ${count(issue)} cells</h2><button class="secondary" id="labelsAi" data-ui="review.explore.labels.ai">Find synonyms with AI</button>${session.aiRequested?ReviewCore.aiStatus(issue):""}<div class="labels-clusters" data-ui="review.explore.labels.clusters">${ReviewCore.limitedItems(session,"label-clusters",groups).map(group=>`<div class="labels-cluster" data-ui="review.explore.labels.cluster" data-group="${escapeHtml(group.key)}"><label><input type="checkbox" data-label-cluster="${escapeHtml(group.key)}" ${session.locked.includes(group.key)?"checked":""}><input data-label-canonical="${escapeHtml(group.key)}" aria-label="Canonical label" value="${escapeHtml(session.canonical[group.key]??group.canonical)}"></label><div class="labels-variant-chips">${group.values.map(value=>`<span draggable="true" data-label-variant="${escapeHtml(value.value)}">${escapeHtml(value.value)} <b>${value.rows.length}</b></span>`).join("")}</div><small>${escapeHtml(group.source)}${group.reason?` · ${escapeHtml(group.reason)}`:""}</small></div>`).join("")}${ReviewCore.showAllHtml(session,"label-clusters",groups.length)}</div><div class="labels-drag-out" id="labelsNotSame">Drop a variant here if it does not mean the same thing.</div><details data-ui="review.explore.labels.all"><summary>All labels (${all.length})</summary>${ReviewCore.limitedItems(session,"all-labels",all).map(group=>`<p>${escapeHtml(group.value || "(blank)")} · ${group.rows.length}</p>`).join("")}${ReviewCore.showAllHtml(session,"all-labels",all.length)}</details></section>`;
  }
  function mapping(issue,session){const result=Object.create(null);list(issue,session).filter(group=>session.locked.includes(group.key)).forEach(group=>group.values.forEach(value=>{const target=session.mapping[value.value]??session.canonical[group.key]??group.canonical;if(!String(target??"").trim())throw new Error("Enter a canonical name for each locked group.");if(Object.hasOwn(result,value.value)&&result[value.value]!==target)throw new Error("A value belongs to conflicting locked groups. Move or exclude one variant before applying.");result[value.value]=target;}));return result;}
  function getFixOptions(issue,session){ // LBL-F-01…03: case options explicitly cover the whole column, mapping stays cluster-scoped.
    const fullColumn=parameters=>{issue.rows=state.rows.filter(row=>String(row[issue.column]??"").trim());return parameters;};
    return [{key:"map-to-canonical",label:"Use one name per group",risk:"Doesn't invent information",compute:()=>({operation:"map",mapping:mapping(issue,session)})},...[["case-lower","Lowercase","lowercase"],["case-title","Title case","titlecase"],["case-upper","Uppercase","uppercase"]].map(([key,label,operation])=>({key,label,risk:"Doesn't invent information",compute:()=>fullColumn({operation})})),{key:"trim",label:"Trim spaces",risk:"Doesn't invent information",more:true,compute:()=>fullColumn({operation:"cleanCharacters",characterTypes:["leading / trailing spaces","double spaces"]})},{key:"keep",label:"Keep as is",risk:"Doesn't change values",more:true,compute:()=>({operation:"retain",interpretation:"legitimate"})}];
  }
  function reminder(issue,session){return `Fixing: ${["case-lower","case-title","case-upper","trim"].includes(session.fix.replace(/^ai:/,""))?"all nonblank labels":`${session.locked.length} label groups`} in ${issue.column} · ${lockedRows(issue,session).length} cells`;}
  function consequence(issue,session,preview,option){ // LBL-F-01, LBL-F-02, LBL-F-03
    const old=ReviewPageEngine.frequencies(state.rows,issue.column),next=ReviewPageEngine.frequencies(preview.after,issue.column),metric=ReviewCore.metricColumn(),targets=[...new Set(preview.patches.map(patch=>patch.after))].slice(0,3),detail=targets.map(value=>{const before=ReviewCore.total(state.rows.filter(row=>row[issue.column]===value),metric),after=ReviewCore.total(preview.after.filter(row=>row[issue.column]===value),metric);return `${value}: ${ReviewCore.money(before,metric)} → ${ReviewCore.money(after,metric)} (${ReviewCore.money(after-before,metric)} from merged variants)`;}).join(" · ");return {sentence:`${issue.column} groups ${old.length} → ${next.length}; ${preview.patches.length} cells use the reviewed label choices.`,figures:[{label:"Distinct labels",before:old.length,after:next.length}],reason:option.key==="keep"?"Names stay distinct in group-by reports.":"Unifies representations without assigning records to a different real group.",detail};}
  function renderPreview(issue,session,preview){ // LBL-F-01, LBL-F-03: mapping is editable; effects are counted once per changing representation.
    const mapped=session.fix.replace(/^ai:/,"")==="map-to-canonical",effects=ReviewPageEngine.frequencies(preview.patches,"before",(_,patch)=>JSON.stringify([patch.before,patch.after]));
    return `${mapped?`<div data-ui="review.fix.mapping" class="labels-mapping">${Object.entries(mapping(issue,session)).map(([before,after])=>`<label><code>${escapeHtml(before)}</code><span>${state.rows.filter(row=>row[issue.column]===before).length} cells</span><input data-label-map="${escapeHtml(before)}" aria-label="Map ${escapeHtml(before)}" value="${escapeHtml(after)}"><button class="text-button" data-remove-label-map="${escapeHtml(before)}">Remove</button></label>`).join("")}</div>`:""}<div class="labels-changing">${effects.map(group=>`<p>${escapeHtml(group.rows[0].before)} ${group.rows.length} → ${escapeHtml(group.rows[0].after)}</p>`).join("") || "<p>No labels change for this choice.</p>"}</div>`;
  }
  function renderReview(issue,decision){ // LBL-R-01, LBL-R-02, LBL-R-03
    const before=decision.reviewImpact.beforeRows,after=decision.reviewImpact.afterRows,metric=decision.reviewSpec?.metric || ReviewCore.metricColumn(),targets=[...new Set(decision.patches.map(patch=>patch.after))].slice(0,3);
    return `${ReviewCore.metricStrip([{label:"Cells changed",value:decision.patches.length},{label:"Rows removed",value:0},{label:"Columns added / removed",value:"0 / 0"},{label:"Distinct labels",value:`${new Set(before.map(row=>row[issue.column])).size} → ${new Set(after.map(row=>row[issue.column])).size}`}])}<div data-ui="review.review.chart">${ReviewCharts.categories(issue.column,before,after,{changedOnly:true,metric,keys:targets,title:`${targets.length} reviewed canonical groups receive the merged ${metric || "row counts"}`})}</div>${ReviewCore.sampleTable(issue,decision.patches)}`;
  }
  function context(issue,session){return {column:issue.column,type:"category-variants",role:"text",headers:state.headers,meaning:columnPolicy(issue.column).meaning,allowedFixes:["map-to-canonical","case-lower","case-title","case-upper","trim","keep"],count:state.rows.length,affected:lockedRows(issue,session).length,values:ReviewPageEngine.frequencies(state.rows,issue.column).slice(0,300).map(group=>({value:group.value,count:group.rows.length,locked:true})),samples:[],statistics:{},groups:[]};}
  async function aiExplore(issue,session){ // LBL-A-01: synonym proposals remain unlocked until the analyst confirms them.
    const result=await ReviewCore.requestAi(issue,"explore",context(issue,session));if(result?.clusters){session.aiClusters=result.clusters;session.aiCanon=result.clusterDetails?.map(group=>group.canonical);session.aiClusterReasons=result.clusterDetails?.map(group=>group.reason);renderPreservingReviewFocus();}
  }
  async function aiFix(issue,session){ // LBL-A-02: proposed names become an explicit AI fix option.
    const summary={...context(issue,session),values:ReviewPageEngine.frequencies(lockedRows(issue,session),issue.column).slice(0,300).map(group=>({value:group.value,count:group.rows.length,locked:true}))},submitted=new Set(summary.values.map(value=>value.value));
    summary.labelClusters=list(issue,session).filter(group=>session.locked.includes(group.key)).slice(0,100).map(group=>({canonical:session.canonical[group.key]??group.canonical,values:group.values.map(value=>value.value).filter(value=>submitted.has(value))})).filter(group=>group.values.length);
    const result=await ReviewCore.requestAi(issue,"fix",summary);if(result?.operation){session.aiFixProposal=result;renderPreservingReviewFocus();}
  }
  function bindMembership(issue,session) {
    bind(issue,session);
    document.querySelectorAll(".labels-cluster").forEach(cluster=>cluster.ondrop=event=>{
      event.preventDefault();
      const value=event.dataTransfer?.getData("text/plain");if(!value)return;
      session.memberOverrides ||= {};session.memberOverrides[value]=cluster.dataset.group;session.detached=session.detached.filter(member=>member!==value);delete session.mapping[value];session.preview=null;renderPreservingReviewFocus();
    });
    document.querySelectorAll("[data-label-variant]").forEach(chip=>chip.addEventListener("dragstart",event=>event.dataTransfer?.setData("text/plain",chip.dataset.labelVariant)));
    document.querySelectorAll(".labels-mapping > label").forEach(label=>{
      if(label.querySelector("span"))return;
      const source=label.querySelector("input")?.dataset.labelMap, count=state.rows.filter(row=>row[issue.column]===source).length,span=document.createElement("span");span.textContent=`${count} cells`;label.querySelector("code")?.after(span);
    });
  }
  function bind(issue,session){document.querySelectorAll("[data-label-cluster]").forEach(input=>input.onchange=()=>{const before=lockedRows(issue,session).length,key=input.dataset.labelCluster;session.locked=input.checked?session.locked.concat(key):session.locked.filter(value=>value!==key);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});document.querySelectorAll("[data-label-canonical]").forEach(input=>input.oninput=()=>{session.canonical[input.dataset.labelCanonical]=input.value;session.preview=null;});let dragged;document.querySelectorAll("[data-label-variant]").forEach(chip=>chip.ondragstart=()=>{dragged=chip.dataset.labelVariant;});const out=document.getElementById("labelsNotSame");if(out){out.ondragover=event=>event.preventDefault();out.ondrop=event=>{event.preventDefault();if(!dragged)return;session.detached.push(dragged);delete session.mapping[dragged];session.preview=null;renderPreservingReviewFocus();};}document.querySelectorAll(".labels-cluster").forEach(cluster=>{cluster.ondragover=event=>event.preventDefault();cluster.ondrop=event=>{event.preventDefault();if(!dragged)return;session.detached=session.detached.filter(value=>value!==dragged);const target=list(issue,session).find(group=>group.key===cluster.dataset.group);session.mapping[dragged]=session.canonical[target.key]||target.canonical;session.preview=null;renderPreservingReviewFocus();};});document.getElementById("labelsAi")?.addEventListener("click",()=>aiExplore(issue,session));document.querySelectorAll("[data-label-map]").forEach(input=>input.onchange=()=>{session.mapping[input.dataset.labelMap]=input.value;ReviewCore.compute(issue);});document.querySelectorAll("[data-remove-label-map]").forEach(button=>button.onclick=()=>{session.detached.push(button.dataset.removeLabelMap);delete session.mapping[button.dataset.removeLabelMap];ReviewCore.compute(issue);});}
  return {detect,init,count,unit:"cells",lockedRows,renderExplore,getFixOptions,reminder,consequence,renderPreview,renderReview,aiExplore,aiFix,bind:bindMembership,clusters};
})();
