// ZERO-D-01, ZERO-D-02: shorter codes are candidates; measurements are not padded implicitly.
ReviewModules["leading-zeros"] = (() => {
  function lengths(rows,column){return ReviewPageEngine.frequencies(rows.filter(row=>String(row[column]??"").trim()),column,value=>String(value).trim().length);}
  function detect(dataset){return dataset.headers.flatMap(column=>{const present=dataset.rows.filter(row=>String(row[column]??"").trim()),digits=present.every(row=>/^\d+$/.test(String(row[column]).trim()));if(!present.length||!/zip|postal|postcode|code|account|acct|phone|sku|id/i.test(column)&&!digits)return [];const distribution=lengths(present,column),dominant=distribution[0];if(dominant.rows.length/present.length<.7)return [];const target=Number(dominant.value),rows=present.filter(row=>String(row[column]).trim().length<target);return rows.length?[{column,reviewType:"leading-zeros",type:"Lost leading zeros / IDs as numbers",label:"Lost leading zeros / IDs as numbers",rows,recommendation:"manual",status:"open",severity:"medium",summary:"Some codes are shorter than the dominant code length; only digit-only codes can be padded.",targetLength:target,width:target,unit:"values"}]:[];});}
  function init(issue,session){session.targetLength??=issue.targetLength||issue.width;if(session.locked===null)session.locked=lengths(state.rows,issue.column).filter(group=>Number(group.value)<session.targetLength).map(group=>String(group.value));}
  function lockedRows(issue,session){init(issue,session);return state.rows.filter(row=>String(row[issue.column]??"").trim()&&session.locked.includes(String(String(row[issue.column]??"").trim().length)));}
  function count(issue){const target=ReviewCore.data(issue).targetLength || issue.targetLength || issue.width;return state.rows.filter(row=>String(row[issue.column]??"").trim()&&String(row[issue.column]).trim().length<target).length;}
  function renderExplore(issue,session){ // ZERO-E-01, ZERO-E-02, ZERO-E-03
    init(issue,session);const example=lockedRows(issue,session)[0];return `<section class="zeros-explore" data-ui="review.explore.zeros"><h2>Check the missing leading zeros</h2><label data-ui="review.explore.zeros.target">Target length<input id="zerosTarget" type="number" min="1" max="100" value="${session.targetLength}"></label><div class="zeros-lengths" data-ui="review.explore.zeros.lengths">${lengths(state.rows,issue.column).map(group=>`<label data-ui="review.explore.zeros.length" data-length="${group.value}">${Number(group.value)<session.targetLength?`<input type="checkbox" data-zero-length="${group.value}" ${session.locked.includes(String(group.value))?"checked":""}>`:""}<b>${group.value} digits</b> · ${group.rows.length} (${(group.rows.length/state.rows.length*100).toFixed(1)}%) · <code>${escapeHtml(group.rows.slice(0,3).map(row=>row[issue.column]).join(" · "))}</code></label>`).join("")}</div><p>${example?`Values like “${escapeHtml(example[issue.column])}” are probably “${escapeHtml(String(example[issue.column]).trim().padStart(session.targetLength,"0"))}” with the leading zero lost.`:"No shorter lengths are locked. Choose a target length or lock a shorter group to prepare a fix."}</p></section>`;}
  function getFixOptions(issue,session){return [{key:"pad-zeros",label:"Add leading zeros",risk:"Estimates values",compute:()=>({operation:"padZeros",width:session.targetLength,roleOverride:"text"})},{key:"to-text",label:"Store as text only",risk:"Doesn't change values",compute:()=>({operation:"toText",interpretation:"legitimate",roleOverride:"text"})},{key:"keep",label:"Keep as is",risk:"Doesn't change values",compute:()=>({operation:"retain",interpretation:"legitimate"})}];}
  function reminder(issue,session){return `Fixing: ${lockedRows(issue,session).length} shorter ${issue.column} codes → ${session.targetLength} digits`;}
  function consequence(issue,session,preview,option){ // ZERO-F-01, ZERO-F-02: text-role decisions are reversible, and CSV values remain quoted.
    return {sentence:option.key==="pad-zeros"?`${preview.patches.length} codes padded to ${session.targetLength} digits; these rows can now match lookups against a ${session.targetLength}-digit code list.`:option.key==="to-text"?"Keeps the codes and stores the column as text without guessing missing digits.":"Keeps the original codes and their current definition.",figures:[{label:"Target length",before:"mixed",after:session.targetLength}],reason:option.key==="pad-zeros"?"Restores the suspected representation; confirm the intended code length.":"The existing characters are preserved."};}
  function renderPreview(issue,session,preview){return ReviewCore.sampleTable(issue,preview.patches);}
  function renderReview(issue,decision){ // ZERO-R-01, ZERO-R-02
    return `${ReviewCore.metricStrip([{label:"Values changed",value:decision.patches.length},{label:"Rows removed",value:0},{label:"Columns added / removed",value:"0 / 0"},{label:"Lengths",value:`${lengths(decision.reviewImpact.beforeRows,issue.column).length} → ${lengths(decision.reviewImpact.afterRows,issue.column).length}`}])}${ReviewCore.sampleTable(issue,decision.patches,[],5,decision.reviewImpact.afterRows)}`;}
  function bind(issue,session){document.getElementById("zerosTarget")?.addEventListener("change",event=>{const target=Number(event.target.value);if(!Number.isInteger(target)||target<1||target>100){notify("Target length must be an integer from 1 to 100.");event.target.value=session.targetLength;return;}const before=lockedRows(issue,session).length;session.targetLength=target;session.locked=lengths(state.rows,issue.column).filter(group=>Number(group.value)<target).map(group=>String(group.value));issue.rows=state.rows.filter(row=>String(row[issue.column]??"").trim()&&String(row[issue.column]).trim().length<target);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});document.querySelectorAll("[data-zero-length]").forEach(input=>input.onchange=()=>{const before=lockedRows(issue,session).length;session.locked=input.checked?session.locked.concat(input.dataset.zeroLength):session.locked.filter(value=>value!==input.dataset.zeroLength);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});
    // ZERO-E-04: a mixed-character code is not presented as a definitely recoverable zero.
    const example=lockedRows(issue,session).find(row=>!/^\d+$/.test(String(row[issue.column]).trim())),section=document.querySelector('[data-ui="review.explore.zeros"]');if(example&&section){const paragraph=section.querySelector("p");if(paragraph)paragraph.textContent="Some shorter codes contain letters or symbols. Numeric codes can be padded; mixed-character values require source review.";}
  }
  return {detect,init,count,unit:"values",lockedRows,renderExplore,getFixOptions,reminder,consequence,renderPreview,renderReview,bind};
})();
