// ZERO-D-01, ZERO-D-02: shorter codes are candidates; measurements are not padded implicitly.
ReviewModules["leading-zeros"] = (() => {
  function lengths(rows,column){return ReviewPageEngine.frequencies(rows.filter(row=>String(row[column]??"").trim()),column,value=>String(value).trim().length);}
  function detect(dataset){return dataset.headers.flatMap(column=>{const present=dataset.rows.filter(row=>String(row[column]??"").trim()),digits=present.every(row=>/^\d+$/.test(String(row[column]).trim()));if(!present.length||!/zip|postal|postcode|code|account|acct|phone|sku|id/i.test(column)&&!digits)return [];const distribution=lengths(present,column),dominant=distribution[0];if(dominant.rows.length/present.length<.7)return [];const target=Number(dominant.value),rows=present.filter(row=>String(row[column]).trim().length<target);return rows.length?[{column,reviewType:"leading-zeros",type:"Lost leading zeros / IDs as numbers",label:"Lost leading zeros / IDs as numbers",rows,recommendation:"manual",status:"open",severity:"medium",summary:"Some codes are shorter than the dominant code length; only digit-only codes can be padded.",targetLength:target,width:target,unit:"values"}]:[];});}
  function init(issue,session){session.targetLength??=issue.targetLength||issue.width;if(session.locked===null)session.locked=lengths(state.rows,issue.column).filter(group=>Number(group.value)<session.targetLength).map(group=>String(group.value));}
  function lockedRows(issue,session){init(issue,session);return state.rows.filter(row=>String(row[issue.column]??"").trim()&&session.locked.includes(String(String(row[issue.column]??"").trim().length)));}
  function count(issue){const target=ReviewCore.data(issue).targetLength || issue.targetLength || issue.width;return state.rows.filter(row=>String(row[issue.column]??"").trim()&&String(row[issue.column]).trim().length<target).length;}
  function getFixOptions(issue,session){return [{key:"pad-zeros",label:"Add leading zeros",risk:"Estimates values",params:()=>`<input id="zerosTarget" type="number" min="1" max="100" aria-label="Target code length" value="${session.targetLength}">`,compute:()=>({operation:"padZeros",width:session.targetLength,roleOverride:"text"})},{key:"to-text",label:"Store as text only",risk:"Doesn't change values",compute:()=>({operation:"toText",interpretation:"legitimate",roleOverride:"text"})},{key:"keep",label:"Keep as is",risk:"Doesn't change values",compute:()=>({operation:"retain",interpretation:"legitimate"})}];}
  function reminder(issue,session){return `Fixing: ${lockedRows(issue,session).length} shorter ${issue.column} codes → ${session.targetLength} digits`;}
  function consequence(issue,session,preview,option){ // ZERO-F-01, ZERO-F-02: text-role decisions are reversible, and CSV values remain quoted.
    return {sentence:option.key==="pad-zeros"?`${preview.patches.length} codes padded to ${session.targetLength} digits; these rows can now match lookups against a ${session.targetLength}-digit code list.`:option.key==="to-text"?"Keeps the codes and stores the column as text without guessing missing digits.":"Keeps the original codes and their current definition.",figures:[{label:"Target length",before:"mixed",after:session.targetLength}],reason:option.key==="pad-zeros"?"Restores the suspected representation; confirm the intended code length.":"The existing characters are preserved."};}
  function bind(issue,session){document.getElementById("zerosTarget")?.addEventListener("change",event=>{const target=Number(event.target.value);if(!Number.isInteger(target)||target<1||target>100){notify("Target length must be an integer from 1 to 100.");event.target.value=session.targetLength;return;}const before=lockedRows(issue,session).length;session.targetLength=target;session.locked=lengths(state.rows,issue.column).filter(group=>Number(group.value)<target).map(group=>String(group.value));issue.rows=state.rows.filter(row=>String(row[issue.column]??"").trim()&&String(row[issue.column]).trim().length<target);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});document.querySelectorAll("[data-zero-length]").forEach(input=>input.onchange=()=>{const before=lockedRows(issue,session).length;session.locked=input.checked?session.locked.concat(input.dataset.zeroLength):session.locked.filter(value=>value!==input.dataset.zeroLength);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});
    // ZERO-E-04: a mixed-character code is not presented as a definitely recoverable zero.
    const example=lockedRows(issue,session).find(row=>!/^\d+$/.test(String(row[issue.column]).trim())),section=document.querySelector('[data-ui="review.explore.zeros"]');if(example&&section){const paragraph=section.querySelector("p");if(paragraph)paragraph.textContent="Some shorter codes contain letters or symbols. Numeric codes can be padded; mixed-character values require source review.";}
  }
  function exploreContent(issue,session){ // ZERO-E-01…04 / C3 + C5 + C4
    init(issue,session);const c=ReviewComponents,items=lengths(state.rows,issue.column).map(group=>({value:`${group.value} digits`,count:group.rows.length,share:`${(group.rows.length/state.rows.length*100).toFixed(1)}%`,control:Number(group.value)<session.targetLength?`<input type="checkbox" data-zero-length="${group.value}" ${session.locked.includes(String(group.value))?"checked":""}>`:"",extra:`<span>${escapeHtml(group.rows.slice(0,3).map(row=>row[issue.column]).join(" · "))}</span>`,ui:"review.explore.zeros.length",attrs:{"data-length":group.value},meta:Number(group.value)<session.targetLength?"shorter code":"current target length"})),examples=lockedRows(issue,session).slice(0,5).map(row=>({row:row._row,before:{value:row[issue.column],raw:true,problem:true},after:{value:/^\d+$/.test(row[issue.column].trim())?row[issue.column].trim().padStart(session.targetLength,"0"):"Needs source review",raw:true}}));
    return {lead:`Do these ${count(issue)} shorter codes need leading zeros?`,sub:`The target is ${session.targetLength} characters; confirm it matches the intended code list.`,controls:c.toolbar("Target length",`<input id="zerosTarget" type="number" min="1" max="100" value="${session.targetLength}" aria-label="Target length">`),controlsTitle:"Set the intended code length",selection:c.selection(items,{ui:"review.explore.zeros.lengths",total:`${lockedRows(issue,session).length} codes selected`}),evidence:c.table({columns:[{key:"row",label:"Row",numeric:true},{key:"before",label:"Source code"},{key:"after",label:"Possible padded code"}],rows:examples}),evidenceTitle:"Inspect shorter codes"};
  }
  function fixContent(issue,session,preview){return {examples:ReviewComponents.table({columns:[{key:"row",label:"Row",numeric:true},{key:"before",label:"Before"},{key:"after",label:"After"}],rows:preview.patches.slice(0,5).map(patch=>({row:patch.rowId,before:{value:patch.before,raw:true},after:{value:patch.after,raw:true}})),card:false,empty:"No characters change for this method."})};}
  function reviewContent(issue,decision){ // ZERO-R-01…02
    return {lead:`${decision.patches.length} codes updated in ${issue.column}.`,sub:`${decision.reviewSpec.label} · ${new Date(decision.createdAt).toLocaleTimeString()} · ${decision.note||"No note"}`,count:decision.rows.length,change:{metrics:[{label:"Codes changed",value:decision.patches.length},{label:"Distinct lengths",value:`${lengths(decision.reviewImpact.beforeRows,issue.column).length} → ${lengths(decision.reviewImpact.afterRows,issue.column).length}`}],text:"The column is stored as text so the exported codes retain their leading zeros."},examples:fixContent(issue,{}, {patches:decision.patches}).examples};
  }
  function bindContent(issue,session){bind(issue,session);document.getElementById("zerosTarget")?.addEventListener("change",()=>{if(session.tab==="fix")ReviewCore.compute(issue);});}
  return {detect,init,count,unit:"values",lockedRows,exploreContent,fixContent,reviewContent,renderExplore:(issue,session)=>ReviewComponents.explore(issue,exploreContent(issue,session)),getFixOptions,reminder,consequence,bind:bindContent};
})();
