// MISS: candidate meanings, real rows around gaps, bounded estimates, and reporting consequences.
ReviewModules.missing = (() => {
  const nullLike = /^(null|n\/?a|none|nan|--?|\?|#n\/a|missing|unknown|not available)$/i;
  const sentinels = new Set([0,-1,-99,-999,99,999,9999,99999]);
  const canonical = value => String(value ?? "").trim() ? String(value) : "";
  function candidates(dataset,column) { // MISS-D-01, MISS-D-02, MISS-D-03: screening never makes a sentinel physically missing.
    const groups=ReviewPageEngine.frequencies(dataset.rows,column,canonical), profile=dataset.profile.columns.find(profile=>profile.column===column), numeric=["number","integer"].includes(profile.role), parsed=groups.flatMap(group=>{try{return [{group,value:CleaningEngine.parseNumber(group.value,profile.policy)}];}catch{return [];}}).sort((a,b)=>a.value-b.value), reviewed=new Map((dataset.classifications||[]).map(entry=>[`${entry.rowId}:${entry.column}`,entry]));
    return groups.filter(group=>{
      if (!group.value || nullLike.test(group.value.trim())) return group.rows.some(row=>{const entry=reviewed.get(`${row._row}:${column}`);return !entry || entry.value!==row[column] || !["legitimate","not_applicable","resolved"].includes(entry.meaning);});
      if (!numeric) return false;
      const index=parsed.findIndex(entry=>entry.group===group), value=parsed[index]?.value;
      if (!sentinels.has(value)) return false;
      const neighbours=[parsed[index-1],parsed[index+1]].filter(Boolean), other=parsed.filter(entry=>entry.value!==value);
      const peak=neighbours.length && neighbours.every(entry=>group.rows.length>=3*entry.group.rows.length), outside=other.length && (value<other[0].value || value>other.at(-1).value);
      return Boolean(peak || outside) && group.rows.some(row=>!reviewed.has(`${row._row}:${column}`) || reviewed.get(`${row._row}:${column}`).value!==row[column]);
    });
  }
  function detect(dataset) { return dataset.headers.flatMap(column=>{const representations=candidates(dataset,column);if (!representations.length)return [];const rows=representations.flatMap(group=>group.rows), role=dataset.profile.columns.find(profile=>profile.column===column).role;return [{column,columnRole:role,date:role==="date",reviewType:"missing",type:"Missing values",label:"Missing values",recommendation:["number","integer"].includes(role)?"impute":"keep",severity:"medium",summary:"Candidate missing representations. Only explicitly locked values enter a treatment.",rows,status:"open",representations:representations.map(group=>({value:group.value,count:group.rows.length})),count:representations.filter(group=>!group.value).reduce((sum,group)=>sum+group.rows.length,0),unit:"cells"}];}); }
  function groups(issue) { return candidates({rows:state.rows,profile:cleaningProfile(),classifications:effectiveClassifications()},issue.column); }
  function init(issue,session) { if (session.locked===null) session.locked=groups(issue).filter(group=>!group.value).map(group=>group.value); if (session.value==="")session.value=ReviewCore.numericType(issue.column)?"0":ReviewCore.moduleFor(issue).isDate(issue)?"":"Unknown"; }
  function lockedRows(issue,session) { init(issue,session);const locked=new Set(session.locked);return state.rows.filter(row=>locked.has(canonical(row[issue.column]))); }
  function count(issue) { return lockedRows(issue,ReviewCore.data(issue)).length; } // MISS-D-02
  function isDate(issue) { return issue.date || cleaningProfile().columns.find(profile=>profile.column===issue.column)?.role==="date"; }
  function contextColumns(issue,session) { // MISS-E-18: Cliff's delta / existing category gaps, never a new association measure.
    return [...new Set([...(session.comparison?.results||[]).map(result=>result.column).filter(column=>!CleaningEngine.isIdentifier(column)),...state.headers.filter(column=>column!==issue.column && !CleaningEngine.isIdentifier(column))])].filter(column=>column!==issue.column && !session.locks.includes(column)).slice(0,4).concat(session.extraColumns||[]).filter((column,index,array)=>array.indexOf(column)===index);
  }
  async function compare(issue,session) { const signature=JSON.stringify([state.datasetRevision,session.locked]);if(session.compareKey===signature || session.comparePending)return;session.comparePending=true;const source=state.original;try{const classifications=effectiveClassifications().concat(lockedRows(issue,session).map(row=>({rowId:row._row,column:issue.column,value:row[issue.column],meaning:"missing"})));const result=await analyticalTask("compare",issue.column,{options:{...analyticalOptions(),classifications}});if(source!==state.original || signature!==JSON.stringify([state.datasetRevision,session.locked]))return;session.comparison=result;session.compareKey=signature;}catch{session.compareKey=signature;}finally{session.comparePending=false;if(state.screen==="issues" && state.selectedIssue===issue.id)renderPreservingReviewFocus();} }
  function grouped(issue,session,rows = state.rows,columns = session.locks) { if(!columns.length)return [{label:"All rows",rows}];const banding=Object.fromEntries(columns.map(column=>[column,{mode:"quantiles",k:5,minCategoryCount:5,...session.banding[column]}])), result=CapabilitiesEngine.bandGroups(state.headers,rows,issue.column,{holdColumns:columns,banding},{...analyticalOptions()});return result.groups.map(group=>({label:group.label,rows:group.indices.map(index=>rows[index])})); }
  function formatted(value,column) { if(value===null || value===undefined || !String(value).trim())return "not recorded";if(ReviewCore.numericType(column)){try{return ReviewCore.format(CleaningEngine.parseNumber(value,columnPolicy(column)),column);}catch{}}return String(value); }
  // MISS-E-18: context dots explain the actual cohort difference, not just a generic association.
  function contextTooltip(issue,session,column) { const ids=new Set(lockedRows(issue,session).map(row=>row._row)),missing=state.rows.filter(row=>ids.has(row._row)),present=state.rows.filter(row=>!ids.has(row._row));if(ReviewCore.numericType(column)){const old=CleaningEngine.stats(ReviewCharts.numeric(missing,column)).median,next=CleaningEngine.stats(ReviewCharts.numeric(present,column)).median;return `Missing rows: median ${ReviewCore.format(old,column)} vs ${ReviewCore.format(next,column)} in present rows.`;}const top=ReviewPageEngine.frequencies(missing,column)[0];if(!top)return "No missing-row comparison is available.";const other=present.filter(row=>row[column]===top.value).length;return `Missing rows here are mostly ${top.value || "unrecorded"} (${Math.round(top.rows.length/Math.max(1,missing.length)*100)}% vs ${Math.round(other/Math.max(1,present.length)*100)}%).`; }
  function rowTable(issue,session,rows,missing,context,key) { // MISS-E-16, MISS-E-20: all gaps first, five real complete rows for contrast.
    const absent=rows.filter(row=>missing.has(row._row)), present=rows.filter(row=>!missing.has(row._row)), shownMissing=session.showRows[`${key}:missing`]?absent:absent.slice(0,20), near=present.sort((a,b)=>{const numericLock=session.locks.find(column=>ReviewCore.numericType(column));if(!numericLock || !absent.length)return a._row-b._row;const distance=row=>Math.min(...absent.map(other=>Math.abs(Number(row[numericLock])-Number(other[numericLock]))));return distance(a)-distance(b)||a._row-b._row;}), shownPresent=session.showRows[`${key}:present`]?near:near.slice(0,5), columns=[issue.column,...session.locks,...context], shown=shownMissing.concat(shownPresent);
    return `<div class="review-sheet-table"><table><thead><tr><th>Row</th>${columns.map((column,index)=>`<th class="${index===0?"pinned-target":""}">${escapeHtml(column)}${context.includes(column)?'<span class="review-diff-dot" title="This column differs between missing and present rows" aria-label="differs"></span>':""}</th>`).join("")}</tr></thead><tbody>${shown.map(row=>`<tr class="${missing.has(row._row)?"gap-row":"contrast-row"}"><td>${row._row}</td>${columns.map((column,index)=>`<td class="${index===0?"pinned-target":""} ${column===issue.column && missing.has(row._row)?"locked-gap":""}">${column===issue.column && !canonical(row[column]) ? '<span aria-label="missing">—</span>' : escapeHtml(formatted(row[column],column))}</td>`).join("")}</tr>`).join("")}</tbody></table></div>${absent.length>shownMissing.length?`<button class="text-button" data-more-gap="${escapeHtml(key)}">${absent.length-shownMissing.length} more missing · show</button>`:""}${present.length>shownPresent.length?`<button class="text-button" data-more-present="${escapeHtml(key)}">${present.length} present · show all</button>`:""}`;
  }
  function sheet(issue,session) { // MISS-E-10, MISS-E-11, MISS-E-12, MISS-E-13, MISS-E-14, MISS-E-15, MISS-E-16, MISS-E-17, MISS-E-18, MISS-E-19, MISS-E-20, MISS-E-21, MISS-E-22
    const missing=new Set(lockedRows(issue,session).map(row=>row._row)), overall=missing.size/Math.max(1,state.rows.length), context=contextColumns(issue,session), visible=grouped(issue,session).map(group=>({...group,n:group.rows.filter(row=>missing.has(row._row)).length})).filter(group=>session.showAll || group.n).sort((a,b)=>b.n/b.rows.length-a.n/a.rows.length), top=visible[0], headline=session.locks.length?(top && top.n/top.rows.length-overall>.03?`Gaps are most common in ${top.label} (${(top.n/top.rows.length*100).toFixed(1)}% vs ${(overall*100).toFixed(1)}% overall).`:`Gaps are spread evenly across ${session.locks[0]} groups (all within ±3 points of ${(overall*100).toFixed(1)}%).`):"Read the missing rows beside similar complete rows. Lock a column to arrange them into groups.";
    const tree=(rows,depth,path=[])=>{if(depth===session.locks.length)return rowTable(issue,session,rows,missing,context,JSON.stringify(path));const col=session.locks[depth], list=grouped(issue,session,rows,[col]).map(group=>({...group,n:group.rows.filter(row=>missing.has(row._row)).length})).filter(group=>session.showAll || group.n).sort((a,b)=>b.n/b.rows.length-a.n/a.rows.length);return list.map((group,index)=>{const id=JSON.stringify(path.concat(group.label)), open=session.openGroups[id] ?? index<3;return `<details class="review-gap-group" data-ui="review.explore.missing.group" data-group="${escapeHtml(id)}" ${open?"open":""}><summary><span>${escapeHtml(group.label || `(blank ${col})`)} · ${group.rows.length} rows · ${group.n} missing (${(group.n/group.rows.length*100).toFixed(1)}%)</span><span class="review-gap-rate"><i style="width:${group.n/group.rows.length*100}%"></i><em style="left:${overall*100}%"></em></span></summary>${open?tree(group.rows,depth+1,path.concat(group.label)):""}</details>`;}).join("");};
    return `<section class="review-gap-sheet" data-ui="review.explore.missing.sheet"><div class="review-sheet-heading"><h3>Rows around the gaps</h3><button class="text-button" id="missingColumns" data-ui="review.explore.missing.columns">+ columns</button></div><div class="review-lock-controls" data-ui="review.explore.missing.locks">${session.locks.map((column,index)=>`<div class="review-lock-chip" draggable="true" data-lock-chip="${index}"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M5 3h1m4 0h1M5 8h1m4 0h1M5 13h1m4 0h1" stroke="currentColor" stroke-width="2"/></svg><b>${escapeHtml(column)}</b>${ReviewCore.numericType(column)?`<select data-ui="review.explore.missing.bands" data-missing-band="${escapeHtml(column)}" aria-label="Bands for ${escapeHtml(column)}"><option value="quantiles" ${(session.banding[column]?.mode||"quantiles")==="quantiles"?"selected":""}>5 quantiles</option><option value="fixedWidth" ${session.banding[column]?.mode==="fixedWidth"?"selected":""}>Fixed width</option><option value="custom" ${session.banding[column]?.mode==="custom"?"selected":""}>Custom edges</option></select>${session.banding[column]?.mode==="fixedWidth"||session.banding[column]?.mode==="custom"?`<input data-missing-edges="${escapeHtml(column)}" aria-label="Width or edges for ${escapeHtml(column)}" value="${escapeHtml(session.banding[column].width || session.banding[column].edges?.join(", ") || "")}">`:""}`:""}<button class="text-button" data-remove-lock="${index}" aria-label="Remove ${escapeHtml(column)}">×</button></div>`).join("")}${session.locks.length<3?`<select id="missingAddLock" aria-label="Add a lock column"><option value="">+ add lock column</option>${state.headers.filter(column=>column!==issue.column && !CleaningEngine.isIdentifier(column) && !session.locks.includes(column)).map(column=>`<option>${escapeHtml(column)}</option>`).join("")}</select>`:""}<label><input id="missingShowAll" type="checkbox" ${session.showAll?"checked":""}> show groups with no gaps</label></div><p class="review-gap-headline" data-ui="review.explore.missing.headline">${escapeHtml(headline)}</p>${session.pickColumns?`<div class="review-column-picker">${state.headers.filter(column=>column!==issue.column && !session.locks.includes(column)).map(column=>`<label><input type="checkbox" data-context-column="${escapeHtml(column)}" ${context.includes(column)?"checked":""}>${escapeHtml(column)}</label>`).join("")}</div>`:""}<div class="review-gap-scroll">${session.locks.length?tree(state.rows,0):rowTable(issue,session,state.rows,missing,context,"flat")}</div></section>`;
  }
  function renderExplore(issue,session) {
    // MISS-D-04, MISS-E-01, MISS-E-02, MISS-E-03, MISS-E-04, MISS-E-05, MISS-E-06, MISS-E-07, MISS-E-08
    init(issue,session);const list=groups(issue), total=lockedRows(issue,session).length, onlyBlank=list.length===1 && !list[0].value;
    return `<section class="missing-explore" data-ui="review.explore.missing"><div class="review-representation-header"><h2>Values that may mean missing</h2><span>${ReviewCore.count(total,"cells")}</span></div><div class="review-missing-overview ${onlyBlank?"blank-only":""}"><div class="review-missing-values" data-ui="review.explore.missing.values">${list.slice(0,200).map((group,index)=>{const assessment=session.ai?.assessments?.find(entry=>entry.value===group.value);return `<button id="missingValue${index}" class="review-missing-value ${session.locked.includes(group.value)?"locked":""}" data-ui="review.explore.missing.value" data-value="${escapeHtml(group.value)}" aria-pressed="${session.locked.includes(group.value)}"><span class="review-lock-square">${session.locked.includes(group.value)?"✓":""}</span><code>${escapeHtml(group.value || "(blank)")}</code><b>${group.rows.length}</b><span>${(group.rows.length/state.rows.length*100).toFixed(1)}%</span><small data-ui="review.explore.missing.confidence">${!group.value?"missing":assessment?`AI ${Math.round(assessment.confidence)}%`:session.aiStatus==="pending"?"AI …":"unreviewed"}</small></button>`;}).join("")}</div>${onlyBlank?`<p class="review-empty-copy" data-ui="review.explore.missing.only-blanks">Only blank cells found (${list[0].rows.length}, ${(list[0].rows.length/state.rows.length*100).toFixed(1)}%), treated as missing. Nothing for AI to judge.</p>`:`<aside class="review-missing-ai" data-ui="review.explore.missing.ai">${ReviewCore.aiStatus(issue)}${session.ai?`<p>${escapeHtml(session.ai.note)}</p><button class="secondary" id="missingAiPicks">Lock AI picks</button>`:""}<button class="text-button" id="missingRefreshAi">Refresh</button></aside>`}</div><p class="review-locked-total" data-ui="review.explore.missing.total">Locked: ${ReviewCore.count(total,"cells")}${state.issues.some(item=>item.column===issue.column && item.reviewType==="constant")?' <button class="text-button" id="missingDropLink">This column is almost empty: consider dropping it →</button>':""}</p>${sheet(issue,session)}</section>`;
  }
  function getFixOptions(issue,session) { // MISS-F-01, MISS-F-02, MISS-F-03
    const numeric=ReviewCore.numericType(issue.column), date=isDate(issue), dateColumn=state.headers.find(column=>column!==issue.column && inferType(column)==="Date"), groupedLabel=session.locks.join(" + "), constantRisk=session=>numeric?(session.blankMeansValue?"Doesn't invent information":"Estimates values"):date?"Estimates values":/^(unknown|unassigned|not recorded|missing)$/i.test(session.value.trim())?"Doesn't invent information":"Invents information", constant={key:"constant",label:numeric?"Fill with value":date?"Fill with date":`Fill “${session.value || "Unknown"}”`,risk:constantRisk,params:()=>`<input id="missingConstant" aria-label="Fill value" type="${numeric?"number":date?"date":"text"}" step="any" value="${escapeHtml(session.value)}"><label class="review-inline-check"><input id="missingBlankMeans" type="checkbox" ${session.blankMeansValue?"checked":""}> Blank means this value</label>`,compute:()=>({operation:"constant",value:session.value})}, leave={key:"leave",label:"Leave missing",risk:"Doesn't change values",compute:()=>({operation:"leaveMissing",interpretation:"missing"})}, drop={key:"drop-rows",label:"Remove these rows",risk:"Removes data",more:true,compute:()=>({operation:"remove"})};
    if(date)return [leave,constant,...(dateColumn?[{key:"previous-value",label:"Carry forward",risk:"Estimates values",more:true,compute:()=>({operation:"previous",orderColumn:dateColumn})},{key:"next-value",label:"Carry back",risk:"Estimates values",more:true,compute:()=>({operation:"next",orderColumn:dateColumn})}]:[]),drop];
    if(!numeric)return [constant,{key:"mode-by-group",label:`Most common by ${groupedLabel || "group"}`,risk:"Invents information",disabled:session.locks.length?"":"Add a lock column in Explore",compute:()=>({operation:"groupMode",groupColumns:session.locks,groupBanding:session.banding})},leave,{key:"mode",label:"Most common overall",risk:"Invents information",more:true,compute:()=>({operation:"mode"})},drop];
    return [{key:"median",label:"Median",risk:"Estimates values",compute:()=>({operation:"median"})},{key:"median-by-group",label:`Median by ${groupedLabel || "group"}`,risk:"Estimates values",disabled:session.locks.length?"":"Add a lock column in Explore",compute:()=>({operation:"groupwise",similar:{columns:session.locks,statistic:"median",minObserved:5,k:7,banding:session.banding}})},constant,leave,{key:"mean",label:"Mean",risk:"Estimates values",more:true,compute:()=>({operation:"mean"})},{key:"knn",label:"Similar rows",risk:"Estimates values",more:true,compute:()=>({operation:"knn",similar:{columns:(session.comparison?.results||[]).filter(result=>!CleaningEngine.isIdentifier(result.column)).slice(0,3).map(result=>result.column),statistic:"median",minObserved:5,k:7,banding:{}}})},...(dateColumn?[{key:"previous-value",label:"Carry forward",risk:"Estimates values",more:true,compute:()=>({operation:"previous",orderColumn:dateColumn})},{key:"next-value",label:"Carry back",risk:"Estimates values",more:true,compute:()=>({operation:"next",orderColumn:dateColumn})},{key:"interpolate",label:"Interpolate",risk:"Estimates values",more:true,compute:()=>({operation:"interpolate",orderColumn:dateColumn})}]:[]),drop];
  }
  function reminder(issue,session) { return `Fixing: ${session.locked.map(value=>value || "(blank)").join(" + ")} in ${issue.column} · ${lockedRows(issue,session).length} cells${session.locks.length?` · grouped by ${session.locks.join(" + ")}`:""}`; }
  function consequence(issue,session,preview,option) { // MISS-F-04, MISS-F-05, MISS-F-06
    const carrying=ReviewCore.measure(issue), label=carrying.metric || "row count", amount=ReviewCore.money(carrying.carry,carrying.metric), whole=ReviewCore.total(preview.after,carrying.metric), numeric=ReviewCore.numericType(issue.column), current=ReviewCore.total(state.rows,carrying.metric), basic=`These ${carrying.rows.length} rows hold ${amount} (${carrying.share.toFixed(1)}% of ${label}).`, figures=[];let sentence=basic,reason="",detail="";
    if(option.key==="drop-rows"){sentence=`Removes ${preview.removedRows.length} rows and ${amount} from all totals.`;figures.push({label:label,before:ReviewCore.money(current,carrying.metric),after:ReviewCore.money(whole,carrying.metric)},{label:"Rows",before:state.rows.length,after:preview.after.length});}
    else if(option.key==="leave"){sentence=`These ${carrying.rows.length} rows stay out of ${numeric?"averages":"per-group totals"} (${amount} not attributed).`;reason="The gaps remain visible; no values are assigned.";}
    else if(numeric){figures.push({label:"Median",before:ReviewCore.format(preview.beforeStats.median,issue.column),after:ReviewCore.format(preview.afterStats.median,issue.column)},{label:"Mean",before:ReviewCore.format(preview.beforeStats.mean,issue.column),after:ReviewCore.format(preview.afterStats.mean,issue.column)});const std=values=>{const stats=CleaningEngine.stats(values);return stats.count?Math.sqrt(values.reduce((sum,value)=>sum+(value-stats.mean)**2,0)/stats.count):null;}, before=ReviewCharts.numeric(state.rows,issue.column,new Set(lockedRows(issue,session).map(row=>row._row))),after=ReviewCharts.numeric(preview.after,issue.column);figures.push({label:"Standard deviation",before:ReviewCore.format(std(before),issue.column),after:ReviewCore.format(std(after),issue.column)});if(carrying.metric===issue.column){figures.pop();figures.push({label:"Total",before:ReviewCore.money(current,carrying.metric),after:ReviewCore.money(whole,carrying.metric)});}reason=option.key==="constant" && session.blankMeansValue?"Uses your confirmed meaning of the blank; it is not a statistical guess.":"Replaces unknown observations with reviewed estimates.";if(option.key==="median-by-group"){const groups=grouped(issue,session).flatMap(group=>{const values=preview.patches.filter(patch=>group.rows.some(row=>row._row===patch.rowId)).map(patch=>Number(patch.after));return values.length?[`${group.label} ${ReviewCore.format(CleaningEngine.stats(values).median,issue.column)}`]:[];});detail=groups.slice(0,4).join(" · ");const fallback=new Set((preview.fillMetadata?.fills||[]).filter(fill=>["widened","global"].includes(fill.source)).map(fill=>fill.bandLabel||"overall"));if(fallback.size)detail+=` · ${fallback.size} groups used fallback`;}}
    else{const values=[...new Set(preview.patches.map(patch=>patch.after))], destination=values.slice(0,2).join(" / ") || session.value, old=state.rows.filter(row=>values.includes(row[issue.column])).length,next=preview.after.filter(row=>values.includes(row[issue.column])).length;sentence=`${carrying.rows.length} rows holding ${amount} will appear as “${destination}” in ${issue.column} reports.`;figures.push({label:`${destination} rows`,before:old,after:next},{label:"Attributed rows",before:state.rows.length-preview.beforeMissing,after:preview.after.length-preview.afterMissing});reason=["mode","mode-by-group"].includes(option.key)||!/^unknown|unassigned|not recorded|missing$/i.test(destination)?"Assigns records to a real category or person without knowing that attribution.":"Keeps the lack of information explicit instead of naming a real person or category.";}
    return {sentence,figures,reason,detail};
  }
  function renderPreview(issue,session,preview,option) { // MISS-F-07, MISS-F-08, CORE-33
    if(option.key==="leave")return '<p>No values change.</p>';
    if(option.key==="drop-rows")return `<p>${preview.removedRows.length} rows will be removed; no cell values are filled.</p>`;
    if(!ReviewCore.numericType(issue.column)){const before=ReviewPageEngine.frequencies(state.rows,issue.column,canonical),after=ReviewPageEngine.frequencies(preview.after,issue.column,canonical), old=new Map(before.map(group=>[group.value,group.rows.length])),next=new Map(after.map(group=>[group.value,group.rows.length])), keys=[...new Set([...old.keys(),...next.keys()])],changed=keys.filter(value=>(old.get(value)||0)!==(next.get(value)||0));return `<div class="review-text-effects">${changed.map(value=>`<p><b>${escapeHtml(value||"(blank)")}</b> ${old.get(value)||0} → ${next.get(value)||0}</p>`).join("")}<p>${keys.length-changed.length} others unchanged</p></div>`;}
    return `${session.locks.length?`<label class="review-chart-toggle" data-ui="review.fix.preview.by-group"><input id="missingPreviewGroups" type="checkbox" ${session.byGroup?"checked":""}> By group</label>`:""}${renderHistograms(issue,session,state.rows,preview.after,preview.patches,true)}`;
  }
  function renderHistograms(issue,session,before,after,patches,compact=false) { const missing=new Set(lockedRows(issue,session).map(row=>row._row));if(!session.byGroup || !session.locks.length)return ReviewCharts.histogram(issue.column,before,after,{missingBefore:missing,patches,compact});const groups=grouped(issue,session,before).sort((a,b)=>b.rows.length-a.rows.length),top=groups.slice(0,4),other=groups.slice(4).flatMap(group=>group.rows);if(other.length)top.push({label:"Other",rows:other});return `<div class="review-small-multiples">${top.map(group=>{const ids=new Set(group.rows.map(row=>row._row));return `<section><h4>${escapeHtml(group.label)}</h4>${ReviewCharts.histogram(issue.column,group.rows,after.filter(row=>ids.has(row._row)),{missingBefore:missing,patches:patches.filter(patch=>ids.has(patch.rowId)),compact:true,ymax:1})}</section>`;}).join("")}</div>`; }
  function renderReview(issue,decision) { // MISS-R-01, MISS-R-02, MISS-R-03, MISS-R-04
    const session=ReviewCore.data(issue), impact=decision.reviewImpact, before=impact.beforeRows, after=impact.afterRows, integer=ReviewCore.numericType(issue.column), metrics=[{label:"Cells filled",value:decision.patches.length},{label:"Rows removed",value:decision.removedRows.length},{label:"Columns added / removed",value:`${decision.structure?.addedColumns.length||0} / ${decision.structure?.removedColumns.length||0}`},{label:"Missing",value:`${impact.beforeMissing} (${(impact.beforeMissing/before.length*100).toFixed(1)}%) → ${impact.afterMissing}`}];if(integer)metrics.push({label:"Median",value:`${ReviewCore.format(impact.beforeStats.median,issue.column)} → ${ReviewCore.format(impact.afterStats.median,issue.column)}`},{label:"Mean",value:`${ReviewCore.format(impact.beforeStats.mean,issue.column)} → ${ReviewCore.format(impact.afterStats.mean,issue.column)}`});else metrics.push({label:"Distinct labels",value:`${new Set(before.map(row=>row[issue.column])).size} → ${new Set(after.map(row=>row[issue.column])).size}`});return `${ReviewCore.metricStrip(metrics)}${session.locks.length?`<label data-ui="review.review.by-group"><input id="missingReviewGroups" type="checkbox" ${session.byGroup?"checked":""}> By group</label>`:""}<div data-ui="review.review.chart">${integer?renderHistograms(issue,session,before,after,decision.patches):ReviewCharts.categories(issue.column,before,after)}</div>${ReviewCore.sampleTable(issue,decision.patches,session.locks)}`; }
  function aiContext(issue,session) { const candidates=groups(issue), ids=new Set(lockedRows(issue,session).map(row=>row._row));return {column:issue.column,type:"missing",role:ReviewCore.numericType(issue.column)?"number":isDate(issue)?"date":"text",headers:state.headers,meaning:columnPolicy(issue.column).meaning,allowedFixes:getFixOptions(issue,session).filter(option=>!option.disabled).map(option=>option.key),count:state.rows.length,affected:ids.size,values:candidates.slice(0,20).map(group=>({value:group.value,count:group.rows.length,locked:session.locked.includes(group.value)})),samples:state.rows.filter(row=>!ids.has(row._row) && canonical(row[issue.column])).slice(0,20).map(row=>String(row[issue.column]).slice(0,160)),statistics:ReviewCore.numericType(issue.column)?cleaningProfile().columns.find(profile=>profile.column===issue.column).statistics:{},groups:grouped(issue,session).slice(0,20).map(group=>({label:group.label,total:group.rows.length,missing:group.rows.filter(row=>ids.has(row._row)).length}))}; }
  async function aiExplore(issue,session) { // MISS-A-01, MISS-E-06…08: blank-only is intentionally not sent.
    if(groups(issue).every(group=>!group.value) || session.aiRequested)return;const result=await ReviewCore.requestAi(issue,"explore",aiContext(issue,session));if(result && !result.assessments)result.assessments=(result.locks||[]).map(value=>({value,confidence:100,reason:"AI recommends treating this representation as missing."})); }
  async function aiFix(issue,session) { const result=await ReviewCore.requestAi(issue,"fix",aiContext(issue,session));if(!result?.operation)return;const allowed=getFixOptions(issue,session).find(option=>option.key===result.operation);if(!allowed)return;session.aiFixProposal=result;renderPreservingReviewFocus(); }
  function bind(issue,session) {
    document.querySelectorAll(".review-diff-dot").forEach(dot=>{dot.title=contextTooltip(issue,session,dot.closest("th").textContent.trim());});
    document.querySelectorAll('[data-ui="review.explore.missing.value"]').forEach(button=>button.onclick=()=>{const before=lockedRows(issue,session).length,value=button.dataset.value;session.locked=session.locked.includes(value)?session.locked.filter(entry=>entry!==value):session.locked.concat(value);ReviewCore.lockChanged(issue,before);session.compareKey="";renderPreservingReviewFocus();});
    document.getElementById("missingAiPicks")?.addEventListener("click",()=>{const before=lockedRows(issue,session).length;session.locked=(session.ai.assessments||[]).filter(entry=>entry.confidence>=70).map(entry=>entry.value);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});
    document.getElementById("missingRefreshAi")?.addEventListener("click",()=>{session.aiRequested=false;aiExplore(issue,session);});document.getElementById("missingDropLink")?.addEventListener("click",()=>ReviewCore.select(state.issues.find(item=>item.column===issue.column && item.reviewType==="constant").id));
    document.getElementById("missingAddLock")?.addEventListener("change",event=>{if(!event.target.value)return;session.locks.push(event.target.value);session.banding[event.target.value]={mode:"quantiles",k:5,minCategoryCount:5};session.preview=null;renderPreservingReviewFocus();});document.querySelectorAll("[data-remove-lock]").forEach(button=>button.onclick=()=>{session.locks.splice(Number(button.dataset.removeLock),1);session.preview=null;renderPreservingReviewFocus();});
    document.querySelectorAll("[data-missing-band]").forEach(input=>input.onchange=()=>{const column=input.dataset.missingBand,stats=cleaningProfile().columns.find(profile=>profile.column===column).statistics;session.banding[column]={mode:input.value,k:5,minCategoryCount:5,width:Math.max((stats.max-stats.min)/5||1,Number.EPSILON),edges:[0,5,10,20,50]};session.preview=null;renderPreservingReviewFocus();});document.querySelectorAll("[data-missing-edges]").forEach(input=>input.onchange=()=>{const band=session.banding[input.dataset.missingEdges],previous=structuredClone(band);if(band.mode==="fixedWidth")band.width=Number(input.value);else band.edges=input.value.split(",").map(Number);try{grouped(issue,session);session.preview=null;renderPreservingReviewFocus();}catch(error){Object.assign(band,previous);notify(error.message);}});
    document.getElementById("missingShowAll")?.addEventListener("change",event=>{session.showAll=event.target.checked;renderPreservingReviewFocus();});document.getElementById("missingColumns")?.addEventListener("click",()=>{session.pickColumns=!session.pickColumns;renderPreservingReviewFocus();});document.querySelectorAll("[data-context-column]").forEach(input=>input.onchange=()=>{session.extraColumns=[...document.querySelectorAll("[data-context-column]:checked")].map(input=>input.dataset.contextColumn);renderPreservingReviewFocus();});
    document.querySelectorAll("[data-ui='review.explore.missing.group']").forEach(group=>{const initial=group.open;group.addEventListener("toggle",()=>{if(!group.isConnected)return;const previous=session.openGroups[group.dataset.group] ?? initial;session.openGroups[group.dataset.group]=group.open;if(previous!==group.open)renderPreservingReviewFocus();});});document.querySelectorAll("[data-more-gap],[data-more-present]").forEach(button=>button.onclick=()=>{const type=button.hasAttribute("data-more-gap")?"missing":"present",key=button.dataset.moreGap||button.dataset.morePresent;session.showRows[`${key}:${type}`]=true;renderPreservingReviewFocus();});
    let dragged=null;document.querySelectorAll("[data-lock-chip]").forEach(chip=>{chip.ondragstart=()=>{dragged=Number(chip.dataset.lockChip);};chip.ondragover=event=>event.preventDefault();chip.ondrop=event=>{event.preventDefault();if(dragged===null)return;const target=Number(chip.dataset.lockChip),[column]=session.locks.splice(dragged,1);session.locks.splice(target,0,column);session.preview=null;renderPreservingReviewFocus();};});
    document.getElementById("missingConstant")?.addEventListener("change",event=>{session.value=event.target.value;ReviewCore.compute(issue);});document.getElementById("missingBlankMeans")?.addEventListener("change",event=>{session.blankMeansValue=event.target.checked;ReviewCore.compute(issue);});["missingPreviewGroups","missingReviewGroups"].forEach(id=>document.getElementById(id)?.addEventListener("change",event=>{session.byGroup=event.target.checked;renderPreservingReviewFocus();}));
    if(session.tab==="explore"){if(!session.comparePending && session.compareKey!==JSON.stringify([state.datasetRevision,session.locked]))setTimeout(()=>compare(issue,session),0);if(!session.aiRequested && groups(issue).some(group=>group.value))setTimeout(()=>{if(state.selectedIssue===issue.id && session.tab==="explore")aiExplore(issue,session);},0);}
  }
  return {detect,unit:"cells",count,groups,init,lockedRows,isDate,contextColumns,grouped,renderExplore,getFixOptions,reminder,consequence,renderPreview,renderReview,aiExplore,aiFix,bind};
})();
