// MULTI-D-01, MULTI-D-02: bounded separator evidence, never a free-text split by default.
ReviewModules["multi-value"] = (() => {
  const separators = [";", "|", ",", " / ", " & ", " + "];
  const parts = (value, separator) => String(value ?? "").split(separator).map(part => part.trim()).filter(Boolean);
  function facts(rows, column, separator) {
    const selected = rows.filter(row => parts(row[column], separator).length >= 2), counts = new Map(), frequencies = new Map();
    for (const row of selected) { const length = parts(row[column], separator).length; counts.set(length, (counts.get(length) || 0) + 1); }
    for (const row of rows) for (const part of parts(row[column], separator)) frequencies.set(part, (frequencies.get(part) || 0) + 1);
    return {selected, counts:[...counts].sort((a,b) => a[0]-b[0]), frequencies:[...frequencies].sort((a,b) => b[1]-a[1]), max:Math.max(0, ...counts.keys())};
  }
  function detect(dataset) {
    return dataset.headers.flatMap(column => {
      if (["number", "integer", "date"].includes(dataset.profile.columns.find(profile => profile.column === column)?.role)) return [];
      const medianLength = CleaningEngine.stats(dataset.rows.filter(row=>String(row[column]??"").trim()).map(row => String(row[column]).length)).median;
      const candidates = separators.filter(separator => separator !== "," || medianLength <= 40).map(separator => ({separator, ...facts(dataset.rows, column, separator)})).sort((a,b) => b.selected.length-a.selected.length);
      const dominant=candidates[0],detected=dominant&&dominant.selected.length/dataset.rows.length>=.02&&dominant.selected.length/dataset.rows.length<=.6?dominant:null;
      return detected ? [{column, reviewType:"multi-value", type:"Multiple values in one cell", label:"Multiple values in one cell", rows:detected.selected, separator:detected.separator, recommendation:"manual", status:"open", severity:"medium", summary:"Several categories are packed into the same cell."}] : [];
    });
  }
  function init(issue, session) { session.separator ??= issue.separator;session.originalRowIds ||= issue.rows.map(row=>row._row); }
  function lockedRows(issue, session) { init(issue, session); return facts(state.rows, issue.column, session.separator).selected; }
  function count(issue) { return lockedRows(issue, ReviewCore.data(issue)).length; }
  function getFixOptions(issue, session) {
    init(issue, session); const info = facts(state.rows, issue.column, session.separator);
    return [{key:"split-to-rows",label:"One row per value",risk:"Changes structure",compute:() => ({operation:"splitRows",separator:session.separator})}, {key:"split-to-columns",label:"One column per position",risk:"Changes structure",compute:() => ({operation:"splitColumns",separator:session.separator})}, {key:"to-flags",label:"One yes/no column per value",risk:"Changes structure",disabled:info.frequencies.length > 20 ? "Flags require at most 20 distinct values" : "",compute:() => ({operation:"splitFlags",separator:session.separator})}, {key:"keep-first",label:"Keep first value only",risk:"Removes data",compute:() => ({operation:"firstValue",separator:session.separator})}, {key:"keep",label:"Keep as is",risk:"Doesn't change values",more:true,compute:() => ({operation:"retain",interpretation:"legitimate"})}];
  }
  function reminder(issue, session) { return `Fixing: ${lockedRows(issue,session).length} cells in ${issue.column} · separated by “${session.separator}”`; }
  function consequence(issue, session, preview, option) { // MULTI-F-01
    const added = (preview.addedRows || []).length, addedColumns = (preview.addedColumns || []).length, metric = ReviewCore.metricColumn(), extra = ReviewCore.total(preview.addedRows || [],metric);
    return {sentence:option.key === "split-to-rows" ? `Rows ${state.rows.length.toLocaleString()} → ${(state.rows.length+added).toLocaleString()}. ${added} copied rows let each value be counted separately.` : option.key === "keep-first" ? `${preview.patches.length} cells keep their first value; every later part is discarded.` : option.key === "keep" ? "Keeps the combined values and the dataset structure." : `Adds ${addedColumns} columns; original ${issue.column} cells are preserved.`, figures:[{label:"Rows",before:state.rows.length,after:preview.after.length},{label:"Columns",before:state.headers.length,after:state.headers.length+addedColumns}], reason:option.key === "split-to-rows" ? "Other columns are copied into each new row." : option.key === "keep-first" ? "The discarded categories will no longer be counted." : "Source values remain available.", detail:option.key === "split-to-rows" ? metric ? `Warning: totals of ${metric} will double-count for split rows (${ReviewCore.money(extra,metric)} counted extra) — use for counting categories, not for summing money.` : "Warning: copied rows increase record counts. Use for counting categories, not for counting original records." : ""};
  }
  function sample(issue, session, beforeRows, afterRows, structure = {}) { // MULTI-F-02, MULTI-R-03
    const examples = beforeRows.filter(row => parts(row[issue.column],session.separator).length >= 2).slice(0,3), columns = structure.addedColumns || [], lineage = structure.rowLineage || [];
    return `<div class="review-table-scroll" data-ui="review.review.sample"><table><thead><tr><th>Row</th><th>Before</th><th>After</th></tr></thead><tbody>${examples.map(row => { const after = afterRows.find(record => record._row === row._row); const children = lineage.filter(trace => trace.sourceRowId === row._row).map(trace => afterRows.find(record => record._row === trace.rowId)?.[issue.column]); const result = columns.length ? columns.map(column => `${column}: ${after?.[column] ?? "(blank)"}`).join(" · ") : [after?.[issue.column], ...children].join(" · "); return `<tr><td>${row._row}</td><td>${escapeHtml(row[issue.column])}</td><td>${escapeHtml(result)}</td></tr>`; }).join("")}</tbody></table></div>`;
  }
  async function aiExplore(issue, session) { // MULTI-A-01: on-request, bounded examples; suggestions never change the separator automatically.
    const candidates=state.rows.filter(row=>separators.some(separator=>parts(row[issue.column],separator).length>=2)),examples=[...new Set([...separators.map(separator=>candidates.find(row=>parts(row[issue.column],separator).length>=2)).filter(Boolean),...candidates])].slice(0,30);
    const result = await ReviewCore.requestAi(issue,"explore",{column:issue.column,type:"multi-value",role:"text",headers:state.headers,meaning:columnPolicy(issue.column).meaning,allowedFixes:getFixOptions(issue,session).filter(option=>!option.disabled).map(option => option.key),count:state.rows.length,affected:lockedRows(issue,session).length,values:ReviewPageEngine.frequencies(candidates,issue.column).slice(0,20).map(group => ({value:group.value,count:group.rows.length,locked:true})),samples:examples.map(row=>String(row[issue.column]).slice(0,500)),groups:[],statistics:{}});
    if (result) renderPreservingReviewFocus();
  }
  function changeSeparator(issue, session, separator) { const before = lockedRows(issue,session).length; session.separator = separator; issue.rows = lockedRows(issue,session); ReviewCore.lockChanged(issue,before); renderPreservingReviewFocus(); }
  function bind(issue, session) { document.getElementById("multiSeparator")?.addEventListener("change",event => changeSeparator(issue,session,event.target.value)); document.getElementById("multiAi")?.addEventListener("click",() => aiExplore(issue,session)); document.getElementById("multiUseSeparator")?.addEventListener("click",() => changeSeparator(issue,session,session.ai.separator));
    const examples=document.querySelector('[data-ui="review.explore.multi.examples"]');if(examples&&!lockedRows(issue,session).length)examples.innerHTML='<p>No cells have two parts with this separator. Choose another separator to inspect examples.</p>';
    if(!lockedRows(issue,session).length&&document.getElementById("reviewAccept"))document.getElementById("reviewAccept").onclick=()=>{const ids=new Set(session.originalRowIds);issue.rows=state.rows.filter(row=>ids.has(row._row));ReviewCore.accept(issue);};
    const area=document.querySelector('[data-ui="review.explore.multi"]');if(area&&session.ai?.separators?.length){const line=document.createElement("p");line.textContent=`AI suggested separators: ${session.ai.separators.map(separator=>`“${separator}”`).join(", ")}. Review each separator's scope before splitting.`;area.append(line);for(const separator of session.ai.separators){const button=document.createElement("button");button.className="text-button";button.textContent=`Use separator “${separator}”`;button.onclick=()=>changeSeparator(issue,session,separator);area.append(button);}}
  }
   function exploreContent(issue,session){ // MULTI-E-01…05 / C3 + one C5 + C4
     init(issue,session);const c=ReviewComponents,info=facts(state.rows,issue.column,session.separator),items=info.counts.map(([length,n])=>({value:`${length} values per cell`,count:n,share:`${(n/state.rows.length*100).toFixed(1)}%`,meta:"selected for splitting"})),examples=info.selected.slice(0,10).map(row=>({row:row._row,source:{value:row[issue.column],raw:true,problem:true},parts:{value:parts(row[issue.column],session.separator).join(" · "),raw:true}}));
     return {lead:`How should these ${info.selected.length} combined values be counted?`,sub:`Splitting reveals ${info.frequencies.length} distinct values; up to ${info.max} occur in one cell.`,selection:c.selection(items,{ui:"review.explore.multi.parts",total:`${info.selected.length} cells selected`,ai:separators.filter(separator=>facts(state.rows,issue.column,separator).selected.length).length>1?`<button class="text-button" id="multiAi">How should these split? AI</button>${session.aiRequested?ReviewCore.aiStatus(issue):""}${session.ai?`<p>${c.text(session.ai.note)}</p>`:""}`:""}),evidence:c.toolbar("Separator",`<select id="multiSeparator">${separators.map(separator=>`<option value="${escapeHtml(separator)}" ${separator===session.separator?"selected":""}>${escapeHtml(separator.trim())}</option>`).join("")}</select>`,"review.explore.multi.separator")+c.table({columns:[{key:"row",label:"Row",numeric:true},{key:"source",label:"Source value"},{key:"parts",label:"Separate parts"}],rows:examples,ui:"review.explore.multi.examples"}),evidenceTitle:"Inspect the parts"};
   }
   function examplePairs(issue,session,a,b,structure){
     const rows=a.filter(row=>parts(row[issue.column],session.separator).length>=2).slice(0,3).map(row=>{const after=b.find(record=>record._row===row._row),children=(structure.rowLineage||[]).filter(trace=>trace.sourceRowId===row._row).map(trace=>b.find(record=>record._row===trace.rowId)?.[issue.column]),values=structure.addedColumns?.length?structure.addedColumns.map(column=>`${column}: ${after?.[column]||"(blank)"}`).join(" · "):[after?.[issue.column],...children].join(" · ");return {row:row._row,before:{value:row[issue.column],raw:true},after:{value:values,raw:true}};});
     return ReviewComponents.table({columns:[{key:"row",label:"Row",numeric:true},{key:"before",label:"Before"},{key:"after",label:"After"}],rows,card:false,ui:"review.review.sample"});
   }
   function fixContent(issue,session,preview,option){ // MULTI-F-01…02
     return {metrics:[{label:"Rows",value:`${state.rows.length} → ${preview.after.length}`},{label:"Columns",value:`${state.headers.length} → ${state.headers.length+preview.addedColumns.length}`}],text:consequence(issue,session,preview,option).detail,examples:examplePairs(issue,session,state.rows,preview.after,preview)};
   }
   function reviewContent(issue,decision){ // MULTI-R-01…03
     const impact=decision.reviewImpact,counts=new Map(),separator=decision.treatment.separator;
     for(const row of impact.afterRows){const values=decision.treatment.operation==="splitColumns"?decision.structure.addedColumns.map(column=>row[column]).filter(Boolean):decision.treatment.operation==="splitFlags"?decision.structure.addedColumns.filter(column=>row[column]==="1").map(column=>column.slice(issue.column.length+1)):parts(row[issue.column],separator);for(const value of values)counts.set(value,(counts.get(value)||0)+1);}
     const top=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,10),max=Math.max(1,...top.map(([,n])=>n)),visual=top.map(([value,n])=>`<div class="rc-label-change"><code>${escapeHtml(value)}</code><span><i class="rc-after-bar" style="width:${n/max*100}%"></i></span><span class="rc-num">${n}</span></div>`).join("");
     return {lead:`${decision.rows.length} combined cells split in ${issue.column}.`,sub:`${decision.reviewSpec.label} · ${new Date(decision.createdAt).toLocaleTimeString()} · ${decision.note||"No note"}`,count:decision.rows.length,change:{metrics:[{label:"Rows",value:`${impact.beforeRows.length} → ${impact.afterRows.length}`},{label:"Columns",value:`${impact.beforeHeaders.length} → ${impact.afterHeaders.length}`},{label:"Cells split",value:decision.rows.length}],visual},examples:examplePairs(issue,{separator},impact.beforeRows,impact.afterRows,decision.structure)};
   }
   return {detect,init,lockedRows,count,unit:"cells",exploreContent,fixContent,reviewContent,renderExplore:(issue,session)=>ReviewComponents.explore(issue,exploreContent(issue,session)),getFixOptions,reminder,consequence,aiExplore,bind,facts};
})();
