// OUT: unusual is not automatically incorrect. Rules, point locks, and reporting impact stay explicit.
ReviewModules.outlier = (() => {
  // OUT-D-01, OUT-D-02, OUT-D-03
  function detect(dataset) { return dataset.baseline.filter(issue=>{const column=dataset.profile.columns.find(profile=>profile.column===issue.column);return issue.reviewType==="outlier"&&["number","integer"].includes(column?.role)&&!CleaningEngine.isIdentifier(issue.column)&&column.statistics.count>=20&&(issue.outlierDefinition?.method!=="iqr" || column.statistics.q3>column.statistics.q1);}).map(issue=>({...issue,unit:"values"})); }
  function init(issue,session) { session.unlocked ||= [];session.selectedPoints ||= [];session.x ||= "";if(session.logY===undefined)session.logY=ReviewCharts.skew(ReviewCharts.numeric(state.rows,issue.column))>2; }
  function profile(issue) {const rule=outlierDraft(issue),result=previewOutlier(issue);let error="";if(rule.method==="iqr"&&(!Number.isFinite(Number(rule.multiplier))||Number(rule.multiplier)<.5||Number(rule.multiplier)>5))error="IQR multiplier must be between 0.5 and 5.";if(rule.method==="zscore"&&(!Number.isFinite(Number(rule.zScore))||Number(rule.zScore)<1||Number(rule.zScore)>6))error="Z threshold must be between 1 and 6.";if(rule.method==="percentile"&&(Number(rule.low)<0||Number(rule.low)>10||Number(rule.high)<90||Number(rule.high)>100))error="Use lower percentiles 0–10 and upper percentiles 90–100.";return error?{...result,rows:[],error,note:error}:result;}
  function count(issue) { return profile(issue).rows.length; }
  function lockedRows(issue,session) { init(issue,session);const fine=new Set(session.unlocked),typos=(session.fix || "").replace(/^ai:/,"")==="ai-typos",corrections=new Set((session.outlierAssessment?.values || []).filter(value=>value.classification==="likely-error"&&value.correction!==undefined&&!session.excludeCorrections?.includes(value.value)).map(value=>value.value));return profile(issue).rows.filter(row=>!fine.has(row._row)&&(!typos||corrections.has(row[issue.column]))); }
  function contexts(issue,session) { return (session.comparison?.results||[]).map(result=>result.column).filter(column=>column!==issue.column&&!CleaningEngine.isIdentifier(column)).slice(0,2).concat(state.headers.filter(column=>column!==issue.column&&!CleaningEngine.isIdentifier(column))).filter((column,index,array)=>array.indexOf(column)===index).slice(0,2); }
  async function comparison(issue,session) {const key=JSON.stringify([state.datasetRevision,outlierDraft(issue)]);if(session.compareKey===key||session.comparePending)return;session.comparePending=true;try{const ids=new Set(profile(issue).rows.map(row=>row._row)),classifications=effectiveClassifications().concat(state.rows.filter(row=>ids.has(row._row)).map(row=>({rowId:row._row,column:issue.column,value:row[issue.column],meaning:"missing"}))),result=await analyticalTask("compare",issue.column,{options:{...analyticalOptions(),classifications}});if(key===JSON.stringify([state.datasetRevision,outlierDraft(issue)])){session.comparison=result;session.compareKey=key;}}catch{session.compareKey=key;}finally{session.comparePending=false;if(state.screen==="issues"&&state.selectedIssue===issue.id)renderPreservingReviewFocus();} }
  function ruleHtml(issue) { // OUT-E-01, OUT-E-02, OUT-E-03
    const rule=outlierDraft(issue),p=profile(issue),limits={multiplier:[.5,5],zScore:[1,6],low:[0,10],high:[90,100]},field=(name,key,type="number")=>`<label>${name}<input id="outlier-${key}" data-outlier-param="${key}" type="${type}" step="${limits[key]?".1":"any"}" ${limits[key]?`min="${limits[key][0]}" max="${limits[key][1]}"`:""} value="${escapeHtml(rule[key])}"></label>`;
    return `<div class="outlier-rule-controls"><label data-ui="review.explore.outlier.rule">Rule<select id="outlierRule">${[["iqr","IQR"],["zscore","Z-score"],["percentile","Percentile"],["threshold","Fixed range"]].map(([key,label])=>`<option value="${key}" ${rule.method===key?"selected":""}>${label}</option>`).join("")}</select></label><div data-ui="review.explore.outlier.threshold" class="outlier-threshold">${["iqr","zscore"].includes(rule.method)?`<label>${rule.method==="iqr"?"Multiplier":"Z threshold"}<input id="outlierSlider" type="range" min="${rule.method==="iqr"?.5:1}" max="${rule.method==="iqr"?5:6}" step=".1" value="${rule.method==="iqr"?rule.multiplier:rule.zScore}"></label>${field("Value",rule.method==="iqr"?"multiplier":"zScore")}`:rule.method==="percentile"?`<label>Lower percentile<input id="outlierLowSlider" type="range" min="0" max="10" step=".1" value="${rule.low}"></label>${field("Lower","low")}<label>Upper percentile<input id="outlierHighSlider" type="range" min="90" max="100" step=".1" value="${rule.high}"></label>${field("Upper","high")}`:`${field("Minimum","lower")}${field("Maximum","upper")}`}</div><p data-ui="review.explore.outlier.bounds">bounds: ${Number.isFinite(p.lower)?ReviewCore.format(p.lower,issue.column):"open"} – ${Number.isFinite(p.upper)?ReviewCore.format(p.upper,issue.column):"open"}</p></div>`;
  }
  function scatter(issue,session,rows=state.rows,options={}) { // OUT-E-05, OUT-F-03, OUT-R-02; all comparisons share axes and bounds.
    const p=options.rule||profile(issue),flagged=new Set(options.changedIds||p.rows?.map(row=>row._row)||[]),fine=new Set(session.unlocked),numeric=(value,column)=>{try{return CleaningEngine.parseNumber(value,options.policy&&column===issue.column?options.policy:columnPolicy(column));}catch{return null;}},xvalue=row=>{try{return !session.x?row._row:inferType(session.x)==="Date"?Date.parse(ReviewPageEngine.dateValue(row[session.x],reviewDateFormats()[JSON.stringify([row._row,session.x,row[session.x]])] || columnPolicy(session.x).dateFormat)):numeric(row[session.x],session.x);}catch{return null;}},points=rows.flatMap(row=>{const y=numeric(row[issue.column],issue.column),x=xvalue(row);return x!==null&&Number.isFinite(x)&&y!==null?[{row,x,y}]:[];}),all=(options.domainRows||state.rows).flatMap(row=>{const x=xvalue(row),y=numeric(row[issue.column],issue.column);return Number.isFinite(x)&&y!==null?[{x,y}]:[];}),xs=all.map(point=>point.x),ys=all.map(point=>point.y).concat([p.lower,p.upper].filter(Number.isFinite)),xmin=xs.length?Math.min(...xs):0,xmax=xs.length?Math.max(...xs):1,ymin=Math.min(...ys,0),ymax=Math.max(...ys,1),transform=value=>session.logY?Math.sign(value)*Math.log1p(Math.abs(value)):value,low=transform(ymin),high=transform(ymax),zoom=session.zoom||1,pan=session.pan||0,px=value=>42+(((value-xmin)/(xmax-xmin||1)-.5)*zoom+.5+pan)*650,py=value=>29+(.5-((transform(value)-low)/(high-low||1)-.5)*zoom+(session.panY||0))*145;
    if(!points.length)return '<p class="review-empty-copy">No usable value pairs are available for this axis. Choose row order or another column.</p>';
    return `<svg class="outlier-scatter" ${options.interactive?'id="outlierPlot"':""} viewBox="0 0 730 210" role="img" aria-label="${escapeHtml(options.title||`${issue.column}: ${p.rows?.length||0} flagged values`)}"><defs><clipPath id="outlierClip${options.part||"explore"}"><rect x="42" y="20" width="650" height="157"/></clipPath></defs><g clip-path="url(#outlierClip${options.part||"explore"})">${points.map(point=>`<circle cx="${px(point.x)}" cy="${py(point.y)}" r="${flagged.has(point.row._row)?3.5:2}" fill="${flagged.has(point.row._row)?fine.has(point.row._row)?"white":"#E07B39":"#9AA3AE"}" stroke="${flagged.has(point.row._row)?"#E07B39":"none"}" ${options.interactive&&flagged.has(point.row._row)?`data-outlier-point="${point.row._row}" tabindex="0" role="button" aria-label="Select row ${point.row._row}, ${ReviewCore.format(point.y,issue.column)}"`:""}><title>Row ${point.row._row}: ${ReviewCore.format(point.y,issue.column)}</title></circle>`).join("")}</g>${[p.lower,p.upper].filter(Number.isFinite).map(value=>`<line x1="42" x2="692" y1="${py(value)}" y2="${py(value)}" stroke="#E07B39" stroke-dasharray="4 3"/><text x="690" y="${py(value)-4}" text-anchor="end">${ReviewCore.format(value,issue.column)}</text>`).join("")}<text x="42" y="196">${session.x&&inferType(session.x)==="Date"?new Date(xmin).toISOString().slice(0,10):ReviewCore.format(xmin,session.x)}</text><text x="692" y="196" text-anchor="end">${session.x&&inferType(session.x)==="Date"?new Date(xmax).toISOString().slice(0,10):ReviewCore.format(xmax,session.x)}</text><text x="9" y="31">${ReviewCore.format(ymax,issue.column)}</text><text x="9" y="175">${ReviewCore.format(ymin,issue.column)}</text></svg>`;
  }
  function valueList(issue,session) { // OUT-E-08, OUT-E-09
    const p=profile(issue),context=contexts(issue,session),distance=row=>{const value=CleaningEngine.parseNumber(row[issue.column],columnPolicy(issue.column));return value<p.lower?p.lower-value:value-p.upper;},rows=[...p.rows].sort((a,b)=>distance(b)-distance(a)), impossible=new Set(state.issues.filter(item=>item.column===issue.column&&item.reviewType==="invalid").flatMap(item=>item.rows.map(row=>row._row)));
    return `<div class="outlier-value-list" data-ui="review.explore.outlier.list">${rows.slice(0,session.showAllValues?rows.length:200).map(row=>{const ai=session.outlierAssessment?.values?.find(value=>value.value===row[issue.column]);return `<div id="outlierRow${row._row}" class="outlier-value ${session.selectedPoints.includes(row._row)?"selected":""}" data-ui="review.explore.outlier.value" data-row="${row._row}"><label><input type="checkbox" data-outlier-lock="${row._row}" ${session.unlocked.includes(row._row)?"":"checked"}><b>${ReviewCore.format(CleaningEngine.parseNumber(row[issue.column],columnPolicy(issue.column)),issue.column)}</b></label><span>row ${row._row}</span>${context.map(column=>`<small>${escapeHtml(column)}: ${escapeHtml(row[column])}</small>`).join("")}${impossible.has(row._row)?'<small class="outlier-badge">also impossible</small>':""}${ai?.classification==="likely-error"?`<small class="outlier-badge" title="${escapeHtml(ai.reason)}">AI: likely typo${ai.correction!==undefined?` → ${escapeHtml(ai.correction)}`:""}</small>`:session.unlocked.includes(row._row)?'<small class="outlier-badge">fine</small>':""}</div>`;}).join("")}${rows.length>200&&!session.showAllValues?'<button class="text-button" id="outlierShowAll">Show all flagged values</button>':""}</div>`;
  }
  function renderExplore(issue,session) {init(issue,session);const p=profile(issue);return `<section class="outlier-explore" data-ui="review.explore.outlier">${ruleHtml(issue)}<p data-ui="review.explore.outlier.count">${ReviewCore.count(p.rows.length,"values")} flagged · ${session.unlocked.filter(id=>p.rows.some(row=>row._row===id)).length} unlocked as fine</p>${!p.rows.length?'<p class="review-empty-copy">No values outside these bounds. Loosen the rule to inspect the tails.</p>':""}<div class="outlier-explore-grid"><section><div class="outlier-axis-controls"><label>X: <select id="outlierX" data-ui="review.explore.outlier.x"><option value="">Row order</option>${state.headers.filter(column=>column!==issue.column&&(ReviewCore.numericType(column)||inferType(column)==="Date")).map(column=>`<option ${session.x===column?"selected":""}>${escapeHtml(column)}</option>`).join("")}</select></label><label><input id="outlierLog" type="checkbox" ${session.logY?"checked":""}> log y-scale</label><button class="text-button" id="outlierReset">Reset</button></div><p class="review-chart-takeaway">${p.rows.length} values fall outside the current ${outlierDraft(issue).method} bounds${session.logY?" · log scale":""}.</p><div data-ui="review.explore.outlier.scatter">${scatter(issue,session,state.rows,{interactive:true})}</div><p class="review-empty-copy">Wheel: zoom · drag: pan · Shift-drag: box-select</p><div data-ui="review.explore.outlier.hist" class="outlier-mini-hist">${ReviewCharts.histogram(issue.column,state.rows,state.rows,{compact:true,title:"Inspect the tails relative to the rule bounds"})}</div></section><section class="outlier-list-section">${valueList(issue,session)}<button class="secondary" id="outlierAi">Which look like errors? AI</button>${session.aiRequested?ReviewCore.aiStatus(issue):""}${session.ai?`<p>${escapeHtml(session.ai.note)}</p>`:""}</section></div></section>`;}
  function getFixOptions(issue,session) { // OUT-F-03, OUT-F-04: excluded corrections stay untouched, with exact stored bounds for every decision.
    const options=[{key:"keep",label:"Keep as is",risk:"Doesn't change values",compute:()=>({operation:"retain",interpretation:"legitimate"})},{key:"cap",label:"Cap to bounds",risk:"Estimates values",compute:()=>{const p=profile(issue);return {operation:"cap",lower:Number.isFinite(p.lower)?String(p.lower):"",upper:Number.isFinite(p.upper)?String(p.upper):""};}},{key:"replace-median",label:"Replace with median",risk:"Estimates values",compute:()=>({operation:"constant",value:String(CleaningEngine.stats(ReviewCharts.numeric(state.rows,issue.column)).median)})},{key:"set-missing",label:"Mark as missing",risk:"Doesn't invent information",compute:()=>({operation:"missing",interpretation:"missing"})},{key:"fixed-cap",label:"Cap to…",risk:"Estimates values",more:true,params:()=>`<label>Minimum<input id="outlierCapLow" type="number" step="any" value="${escapeHtml(session.capLow||"")}"></label><label>Maximum<input id="outlierCapHigh" type="number" step="any" value="${escapeHtml(session.capHigh||"")}"></label>`,compute:()=>({operation:"cap",lower:session.capLow||"",upper:session.capHigh||""})},...(session.outlierAssessment?.values?.some(value=>value.classification==="likely-error"&&value.correction!==undefined)?[{key:"ai-typos",label:"Fix likely typos (AI)",risk:"Estimates values",compute:()=>({operation:"valueMap",mapping:Object.fromEntries(session.outlierAssessment.values.filter(value=>value.classification==="likely-error"&&value.correction!==undefined&&!session.excludeCorrections?.includes(value.value)).map(value=>[value.value,String(value.correction)]))})}]:[]),{key:"drop-rows",label:"Remove rows",risk:"Removes data",more:true,compute:()=>({operation:"remove"})},{key:"log-transform",label:"Add log column",risk:"Changes structure",more:true,compute:()=>({operation:"log",logOffset:1})}];
    return options.map(option=>({...option,compute:async()=>({...await option.compute(),exploreBounds:{lower:profile(issue).lower,upper:profile(issue).upper},reviewedOutlierRule:structuredClone(outlierDraft(issue))})}));
  }
  function reminder(issue,session){const p=profile(issue);return `Fixing: ${lockedRows(issue,session).length} values above ${Number.isFinite(p.upper)?ReviewCore.format(p.upper,issue.column):"the open upper end"} or below ${Number.isFinite(p.lower)?ReviewCore.format(p.lower,issue.column):"the open lower end"} in ${issue.column} (${outlierDraft(issue).method})`;}
  function consequence(issue,session,preview,option){ // OUT-F-01, OUT-F-02
    const carrying=ReviewCore.measure(issue),before=ReviewCharts.numeric(state.rows,issue.column),after=ReviewCharts.numeric(preview.after,issue.column),old=CleaningEngine.stats(before),next=CleaningEngine.stats(after),sum=values=>values.reduce((total,value)=>total+value,0);let sentence=`These ${carrying.rows.length} rows hold ${ReviewCore.money(carrying.carry,carrying.metric)} (${carrying.share.toFixed(1)}% of ${carrying.metric||"row count"}).`,reason="";
    let effect="";const key=option.key.replace(/^ai:/,"");
    if(key==="keep"){const retained=new Set(carrying.rows.map(row=>row._row)),without=CleaningEngine.stats(ReviewCharts.numeric(state.rows.filter(row=>!retained.has(row._row)),issue.column));effect=`Average stays at ${ReviewCore.format(old.mean,issue.column)} (would be ${ReviewCore.format(without.mean,issue.column)} without these ${carrying.rows.length} values).`;}
    if(key==="set-missing")effect=`Creates ${preview.patches.length} new missing cells in ${issue.column}; a Missing values issue will open for them.`;
    if(key==="log-transform")effect=`Adds ${issue.column}_log = ln(1 + x) for usable values across the column. The original values and their reported totals stay unchanged.${preview.derivedUnavailable?.length?` ${preview.derivedUnavailable.length} other values have no valid log result and stay empty in the new column.`:""}`;
    if(option.key==="drop-rows")reason=`Removes ${preview.removedRows.length} rows from every report, not just this average.`;
    const figures=[{label:"Mean",before:ReviewCore.format(old.mean,issue.column),after:ReviewCore.format(next.mean,issue.column)},{label:"Median",before:ReviewCore.format(old.median,issue.column),after:ReviewCore.format(next.median,issue.column)},{label:"Target total",before:ReviewCore.format(sum(before),issue.column),after:ReviewCore.format(sum(after),issue.column)}];
    return {sentence,effect,figures,reason,detail:carrying.metric&&carrying.metric!==issue.column?`${carrying.metric} total: ${ReviewCore.money(ReviewCore.total(state.rows))} → ${ReviewCore.money(ReviewCore.total(preview.after))}`:""};
  }
  function renderPreview(issue,session,preview,option){const ids=preview.patches.filter(patch=>patch.column===issue.column).map(patch=>patch.rowId),rule=profile(issue),domain=state.rows.concat(preview.after),key=option.key.replace(/^ai:/,"");if(key==="keep")return '<p>No values change. The unusual values remain in totals and averages.</p>';return `<div class="outlier-scatter-pair"><section><h4>Before</h4>${scatter(issue,session,state.rows,{rule,domainRows:domain,part:"before"})}</section><section><h4>After</h4>${scatter(issue,session,preview.after,{rule,changedIds:ids,domainRows:domain,part:"after"})}</section></div>${key==="ai-typos"?(session.outlierAssessment?.values||[]).filter(value=>value.correction!==undefined).map(value=>`<label><input type="checkbox" data-outlier-correction="${escapeHtml(value.value)}" ${session.excludeCorrections?.includes(value.value)?"":"checked"}>${escapeHtml(value.value)} → ${escapeHtml(value.correction)} · ${escapeHtml(value.reason)}</label>`).join(""):""}${key==="log-transform"?ReviewCore.sampleTable(issue,preview.patches):""}`;}
  function renderReview(issue,decision){ // OUT-R-01, OUT-R-02, OUT-R-03
    const session=ReviewCore.data(issue),impact=decision.reviewImpact,before=ReviewCharts.numeric(impact.beforeRows,issue.column,new Set(impact.beforeExcludedIds||[]),{snapshot:true,policy:decision.reviewSpec?.targetPolicy}),after=ReviewCharts.numeric(impact.afterRows,issue.column,new Set(impact.afterExcludedIds||[]),{snapshot:true,policy:decision.reviewSpec?.targetPolicy}),old=CleaningEngine.stats(before),next=CleaningEngine.stats(after),rule={lower:decision.treatment.exploreBounds?.lower??(decision.treatment.lower===""?-Infinity:Number(decision.treatment.lower)),upper:decision.treatment.exploreBounds?.upper??(decision.treatment.upper===""?Infinity:Number(decision.treatment.upper))},outside=values=>values.filter(value=>value<rule.lower||value>rule.upper).length,domain=impact.beforeRows.concat(impact.afterRows);
    const ids=decision.patches.filter(patch=>patch.column===issue.column).map(patch=>patch.rowId),policy=decision.reviewSpec?.targetPolicy;
    return `${ReviewCore.metricStrip([{label:"Values changed",value:decision.patches.length},{label:"Rows removed",value:decision.removedRows.length},{label:"Columns added / removed",value:`${decision.structure.addedColumns.length} / ${decision.structure.removedColumns.length}`},{label:"Minimum",value:`${ReviewCore.format(old.min,issue.column)} → ${ReviewCore.format(next.min,issue.column)}`},{label:"Maximum",value:`${ReviewCore.format(old.max,issue.column)} → ${ReviewCore.format(next.max,issue.column)}`},{label:"Outside bounds",value:`${outside(before)} → ${outside(after)}`},{label:"Mean",value:`${ReviewCore.format(old.mean,issue.column)} → ${ReviewCore.format(next.mean,issue.column)}`},{label:"Median",value:`${ReviewCore.format(old.median,issue.column)} → ${ReviewCore.format(next.median,issue.column)}`}])}<div data-ui="review.review.chart"><p class="review-chart-takeaway">${decision.patches.length} reviewed values changed; maximum ${ReviewCore.format(old.max,issue.column)} → ${ReviewCore.format(next.max,issue.column)}.</p><div class="outlier-scatter-pair"><section><h4>Before</h4>${scatter(issue,session,impact.beforeRows,{rule,policy,changedIds:decision.rows.map(row=>row._row),domainRows:domain,part:"reviewBefore"})}</section><section><h4>After</h4>${scatter(issue,session,impact.afterRows,{rule,policy,changedIds:ids,domainRows:domain,part:"reviewAfter"})}</section></div></div>${ReviewCore.sampleTable(issue,decision.patches,contexts(issue,session),5,impact.afterRows)}`;
  }
  function context(issue,session){ // OUT-A-01, OUT-A-02: bounded flagged values include two actual context fields; Fix retains the assessment.
    const contextColumns=contexts(issue,session),p=profile(issue),ids=new Set(p.rows.map(row=>row._row));
    return {column:issue.column,type:"outlier",role:"number",headers:state.headers,meaning:columnPolicy(issue.column).meaning,allowedFixes:getFixOptions(issue,session).map(option=>option.key),count:state.rows.length,affected:lockedRows(issue,session).length,values:ReviewPageEngine.frequencies(p.rows,issue.column).slice(0,200).map(group=>({value:group.value,count:group.rows.length,locked:group.rows.some(row=>!session.unlocked.includes(row._row)),context:Object.fromEntries(contextColumns.map(column=>[column,String(group.rows[0][column]??"").slice(0,500)]))})),samples:state.rows.filter(row=>!ids.has(row._row)&&observationState(row,issue.column)==="present").slice(0,20).map(row=>row[issue.column]),statistics:cleaningProfile().columns.find(profile=>profile.column===issue.column).statistics,groups:[],rule:{...outlierDraft(issue),lower:Number.isFinite(p.lower)?p.lower:null,upper:Number.isFinite(p.upper)?p.upper:null},assessments:session.outlierAssessment?.values || []};
  }
  async function aiExplore(issue,session){const result=await ReviewCore.requestAi(issue,"outlier-assess",context(issue,session));if(result){session.outlierAssessment=result;renderPreservingReviewFocus();}}
  async function aiFix(issue,session){const result=await ReviewCore.requestAi(issue,"fix",context(issue,session));if(result?.operation){session.aiFixProposal=result;renderPreservingReviewFocus();}}
  function bind(issue,session) { // OUT-E-04, OUT-E-06, OUT-E-09, OUT-E-10
    init(issue,session);const oldCount=session.lastLockedCount ?? lockedRows(issue,session).length;
    const replot=()=>renderPreservingReviewFocus(),ruleChanged=()=>{session.outlierAssessment=null;session.aiFixProposal=null;session.aiController?.abort();session.ai=null;session.aiStatus="idle";session.comparison=null;session.compareKey="";ReviewCore.lockChanged(issue,oldCount);replot();};
    document.getElementById("outlierRule")?.addEventListener("change",event=>{outlierDraft(issue).method=event.target.value;session.unlocked=[];ruleChanged();});
    const schedule=()=>{clearTimeout(session.ruleTimer);session.ruleTimer=setTimeout(ruleChanged,150);};
    document.querySelectorAll("[data-outlier-param]").forEach(input=>input.oninput=()=>{outlierDraft(issue)[input.dataset.outlierParam]=input.value;schedule();});
    [["outlierSlider",outlierDraft(issue).method==="iqr"?"multiplier":"zScore"],["outlierLowSlider","low"],["outlierHighSlider","high"]].forEach(([id,key])=>document.getElementById(id)?.addEventListener("input",event=>{outlierDraft(issue)[key]=event.target.value;document.getElementById(`outlier-${key}`).value=event.target.value;schedule();}));
    document.getElementById("outlierX")?.addEventListener("change",event=>{session.x=event.target.value;session.zoom=1;session.pan=0;session.panY=0;replot();});
    document.getElementById("outlierLog")?.addEventListener("change",event=>{session.logY=event.target.checked;replot();});
    document.getElementById("outlierReset")?.addEventListener("click",()=>{session.zoom=1;session.pan=0;session.panY=0;replot();});
    const toggle=id=>{const before=lockedRows(issue,session).length;session.unlocked=session.unlocked.includes(id)?session.unlocked.filter(value=>value!==id):session.unlocked.concat(id);ReviewCore.lockChanged(issue,before);replot();};
    document.querySelectorAll("[data-outlier-lock]").forEach(input=>input.onchange=()=>toggle(Number(input.dataset.outlierLock)));
    document.querySelectorAll("[data-outlier-point]").forEach(point=>{point.onclick=()=>{const id=Number(point.dataset.outlierPoint);session.selectedPoints=[id];session.showAllValues=true;toggle(id);document.getElementById(`outlierRow${id}`)?.scrollIntoView({block:"nearest"});};point.onkeydown=event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();point.onclick();}};});
    const plot=document.getElementById("outlierPlot");
    if(plot) {
      plot.onwheel=event=>{event.preventDefault();session.zoom=Math.max(1,Math.min(20,(session.zoom||1)*(event.deltaY<0?1.2:.8)));replot();};let start;
      plot.onpointerdown=event=>{if(event.target.dataset.outlierPoint)return;start={x:event.clientX,y:event.clientY,box:event.shiftKey};plot.setPointerCapture(event.pointerId);};
      plot.onpointerup=event=>{if(!start)return;if(start.box){const lowX=Math.min(start.x,event.clientX),highX=Math.max(start.x,event.clientX),lowY=Math.min(start.y,event.clientY),highY=Math.max(start.y,event.clientY);session.selectedPoints=[...plot.querySelectorAll("[data-outlier-point]")].filter(point=>{const rect=point.getBoundingClientRect();return rect.x>=lowX&&rect.x<=highX&&rect.y>=lowY&&rect.y<=highY;}).map(point=>Number(point.dataset.outlierPoint));session.showAllValues=true;}else{session.pan=(session.pan||0)+(event.clientX-start.x)/plot.getBoundingClientRect().width;session.panY=(session.panY||0)+(event.clientY-start.y)/plot.getBoundingClientRect().height;}start=null;replot();};
      plot.onpointercancel=()=>{start=null;};
    }
    document.getElementById("outlierAi")?.addEventListener("click",()=>aiExplore(issue,session));
    const aiButton=document.getElementById("outlierAi");if(aiButton&&!profile(issue).rows.length){aiButton.disabled=true;aiButton.title="There are no flagged values to assess";}
    const mini=document.querySelector('[data-ui="review.explore.outlier.hist"]');if(mini){const p=profile(issue);mini.innerHTML=ReviewCharts.histogram(issue.column,state.rows,state.rows,{compact:true,range:{min:Number.isFinite(p.lower)?p.lower:"",max:Number.isFinite(p.upper)?p.upper:""},title:"Inspect the tails relative to the shaded rule bounds"});}
    if(session.outlierAssessment){const section=document.querySelector(".outlier-list-section"),copy=section?.querySelector("p:not(.review-ai-status)");if(copy)copy.textContent=`AI · ${session.aiProvider || "configured provider"}: ${session.outlierAssessment.note}`;}
    if(profile(issue).error)document.querySelector(".outlier-explore")?.insertAdjacentHTML("afterbegin",`<p class="workspace-error" role="alert">${escapeHtml(profile(issue).note)}</p>`);
    document.getElementById("outlierShowAll")?.addEventListener("click",()=>{session.showAllValues=true;replot();});
    [["outlierCapLow","capLow"],["outlierCapHigh","capHigh"]].forEach(([id,key])=>document.getElementById(id)?.addEventListener("change",event=>{session[key]=event.target.value;ReviewCore.compute(issue);}));
    document.querySelectorAll("[data-outlier-correction]").forEach(input=>input.onchange=()=>{session.excludeCorrections ||= [];const value=input.dataset.outlierCorrection;session.excludeCorrections=input.checked?session.excludeCorrections.filter(item=>item!==value):session.excludeCorrections.concat(value);ReviewCore.compute(issue);});
    session.lastLockedCount=lockedRows(issue,session).length;
    if(session.tab==="explore"&&!session.comparePending&&session.compareKey!==JSON.stringify([state.datasetRevision,outlierDraft(issue)]))setTimeout(()=>comparison(issue,session),0);
  }
  function invalidate(session){session.outlierAssessment=null;session.compareKey="";session.comparison=null;}
  return {detect,init,count,unit:"values",lockedRows,exploreRows:(issue,session)=>profile(issue).rows.filter(row=>!session.unlocked.includes(row._row)),contextColumns:contexts,renderExplore,getFixOptions,reminder,consequence,renderPreview,renderReview,aiExplore,aiFix,invalidate,bind};
})();
