// WS-D-01, WS-D-02, WS-D-03: visible characters and their hidden group-by impact.
ReviewModules.whitespace = (() => {
  const types=["leading / trailing spaces","double spaces","non-breaking spaces","line breaks / tabs","zero-width characters","broken encoding"];
  const visible=value=>String(value).replace(/ /g,"␣").replace(/\u00a0/g,"·").replace(/\t/g,"→").replace(/[\r\n]/g,"↵").replace(/[\u200b-\u200d\ufeff]/g,"⌀");
  function repaired(value){const row={_row:1,value:String(value)},preview=CleaningEngine.treatment(["value"],[row],[1],"value",{operation:"cleanCharacters",scope:{mode:"selected",rowIds:[1]},decimals:2},CleaningEngine.defaultPolicy("value"),[],{});return preview.patches[0]?.after??String(value);}
  function detect(dataset){return dataset.headers.flatMap(column=>{if(["number","integer","date"].includes(dataset.profile.columns.find(profile=>profile.column===column).role))return [];const rows=dataset.rows.filter(row=>ReviewPageEngine.whitespaceTypes(row[column]).length);return rows.length?[{column,reviewType:"whitespace",type:"Hidden spaces & characters",label:"Hidden spaces & characters",rows,recommendation:"manual",severity:"medium",summary:"Invisible representation differences can break grouping and joins.",status:"open",unit:"cells"}]:[];});}
  function init(issue,session){if(session.locked===null)session.locked=types.filter(type=>state.rows.some(row=>ReviewPageEngine.whitespaceTypes(row[issue.column]).includes(type)));}
  function lockedRows(issue,session){init(issue,session);return state.rows.filter(row=>ReviewPageEngine.whitespaceTypes(row[issue.column]).some(type=>session.locked.includes(type)));}
  function count(issue){return issue.rows.length;}
  function hiddenGroups(issue){return ReviewPageEngine.frequencies(state.rows,issue.column,value=>repaired(value)).map(group=>({...group,variants:ReviewPageEngine.frequencies(group.rows,issue.column)})).filter(group=>group.variants.length>1);}
  function renderExplore(issue,session){ // WS-E-01, WS-E-02, WS-E-03, WS-E-04
    init(issue,session);return `<section class="whitespace-explore" data-ui="review.explore.whitespace"><h2>${escapeHtml(issue.column)} · ${count(issue)} cells with hidden characters</h2><div class="whitespace-types" data-ui="review.explore.whitespace.types">${types.flatMap(type=>{const rows=state.rows.filter(row=>ReviewPageEngine.whitespaceTypes(row[issue.column]).includes(type));if(!rows.length)return [];return [`<label data-ui="review.explore.whitespace.type" data-type="${escapeHtml(type)}"><input type="checkbox" data-whitespace-type="${escapeHtml(type)}" ${session.locked.includes(type)?"checked":""}><b>${escapeHtml(type)}</b><span>${rows.length}</span><code>${escapeHtml(rows.slice(0,3).map(row=>type==="broken encoding"?`${visible(row[issue.column])} → ${visible(repaired(row[issue.column]))}`:visible(row[issue.column])).join(" · "))}</code></label>`];}).join("")}</div><div class="whitespace-impact" data-ui="review.explore.whitespace.impact">${hiddenGroups(issue).slice(0,5).map(group=>`<p>“${escapeHtml(visible(group.variants[0].value))}” and “${escapeHtml(visible(group.variants[1].value))}” are counted as ${group.variants.length} different ${escapeHtml(issue.column)} values (${group.rows.length} rows).</p>`).join("")||"<p>No additional hidden duplicate labels were found.</p>"}</div></section>`;
  }
  function getFixOptions(issue,session){return [{key:"clean-all",label:"Clean all locked problems",risk:"Doesn't invent information",compute:()=>({operation:"cleanCharacters",characterTypes:session.locked})},{key:"trim",label:"Trim ends",risk:"Doesn't invent information",compute:()=>({operation:"trimEnds"})},{key:"collapse-spaces",label:"Single spaces",risk:"Doesn't invent information",compute:()=>({operation:"collapseSpaces"})},{key:"remove-hidden",label:"Remove invisible characters",risk:"Doesn't invent information",compute:()=>({operation:"stripInvisible"})},{key:"fix-encoding",label:"Repair encoding",risk:"Estimates values",more:true,compute:()=>({operation:"fixEncoding"})},{key:"keep",label:"Keep as is",risk:"Doesn't change values",more:true,compute:()=>({operation:"retain",interpretation:"legitimate"})}];}
  function reminder(issue,session){return `Fixing: ${session.locked.join(" + ")} in ${issue.column} · ${lockedRows(issue,session).length} cells`;}
  function consequence(issue,session,preview){ // WS-F-01
    const old=new Set(state.rows.map(row=>row[issue.column])).size,next=new Set(preview.after.map(row=>row[issue.column])).size,merge=hiddenGroups(issue)[0];return {sentence:`${preview.patches.length} cells cleaned · ${issue.column} groups ${old} → ${next}${merge?` (“${visible(merge.variants[0].value)}” and “${visible(merge.variants[1].value)}” merge: ${merge.rows.length} rows)`:""}.`,figures:[{label:"Distinct groups",before:old,after:next}],reason:"Restores readable representations; no real group or person is assigned."};}
  function renderPreview(issue,session,preview){return `<div class="whitespace-examples">${preview.patches.slice(0,10).map(patch=>`<p>Row ${patch.rowId} <code>${escapeHtml(visible(patch.before))} → ${escapeHtml(visible(patch.after))}</code></p>`).join("")||"<p>No values change for this choice.</p>"}</div>`;}
  function renderReview(issue,decision){ // WS-R-01, WS-R-02, WS-R-03
    const before=decision.reviewImpact.beforeRows,after=decision.reviewImpact.afterRows,targets=[...new Set(decision.patches.map(patch=>patch.after))];
    return `${ReviewCore.metricStrip([{label:"Cells cleaned",value:decision.patches.length},{label:"Rows removed",value:0},{label:"Columns added / removed",value:"0 / 0"},{label:"Distinct values",value:`${new Set(before.map(row=>row[issue.column])).size} → ${new Set(after.map(row=>row[issue.column])).size}`}])}<div data-ui="review.review.chart">${targets.slice(0,5).map(value=>`<p>${escapeHtml(visible(value))}: ${before.filter(row=>row[issue.column]===value).length} → ${after.filter(row=>row[issue.column]===value).length} rows in the cleaned group.</p>`).join("")}</div><div data-ui="review.review.sample">${decision.patches.slice(0,5).map(patch=>`<p>Row ${patch.rowId} <code>${escapeHtml(visible(patch.before))} → ${escapeHtml(visible(patch.after))}</code></p>`).join("")}</div>`;
  }
  async function aiExplore(issue,session) { // WS-A-01: requested only for ambiguous encoding repairs.
    const candidates=state.rows.filter(row=>ReviewPageEngine.whitespaceTypes(row[issue.column]).includes("broken encoding"));
    if(!candidates.length)return;
    return ReviewCore.requestAi(issue,"explore",{column:issue.column,type:"whitespace",role:"text",headers:state.headers,meaning:columnPolicy(issue.column).meaning,allowedFixes:["fix-encoding","keep"],count:state.rows.length,affected:candidates.length,values:ReviewPageEngine.frequencies(candidates,issue.column).slice(0,20).map(group=>({value:group.value,count:group.rows.length,locked:true})),samples:candidates.slice(0,20).map(row=>repaired(row[issue.column])),statistics:{},groups:[]});
  }
  function bind(issue,session){document.querySelectorAll("[data-whitespace-type]").forEach(input=>input.onchange=()=>{const before=lockedRows(issue,session).length,type=input.dataset.whitespaceType;session.locked=input.checked?session.locked.concat(type):session.locked.filter(value=>value!==type);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});}
  function bindEncoding(issue,session) {
    bind(issue,session);
    if(session.tab!=="explore" || !state.rows.some(row=>ReviewPageEngine.whitespaceTypes(row[issue.column]).includes("broken encoding")))return;
    const section=document.querySelector('[data-ui="review.explore.whitespace"]');
    const button=document.createElement("button");button.className="secondary";button.textContent="Is this encoding repair right? AI";button.onclick=()=>aiExplore(issue,session);section.append(button);
    if(session.aiRequested)section.insertAdjacentHTML("beforeend",ReviewCore.aiStatus(issue));
    if(session.ai)section.insertAdjacentHTML("beforeend",`<p>AI · ${escapeHtml(session.aiProvider)}: ${escapeHtml(session.ai.note)}</p>`);
  }
  return {detect,init,count,unit:"cells",lockedRows,renderExplore,getFixOptions,reminder,consequence,renderPreview,renderReview,aiExplore,bind:bindEncoding};
})();
