// WS-D-01, WS-D-02, WS-D-03: visible characters and their hidden group-by impact.
ReviewModules.whitespace = (() => {
  const types=["leading / trailing spaces","double spaces","non-breaking spaces","line breaks / tabs","zero-width characters","broken encoding"];
  const visible=value=>String(value).replace(/ /g,"␣").replace(/\u00a0/g,"·").replace(/\t/g,"→").replace(/[\r\n]/g,"↵").replace(/[\u200b-\u200d\u2060\ufeff]/g,"⌀");
  function repaired(value){const row={_row:1,value:String(value)},preview=CleaningEngine.treatment(["value"],[row],[1],"value",{operation:"cleanCharacters",scope:{mode:"selected",rowIds:[1]},decimals:2},CleaningEngine.defaultPolicy("value"),[],{});return preview.patches[0]?.after??String(value);}
  function detect(dataset){return dataset.headers.flatMap(column=>{if(["number","integer","date"].includes(dataset.profile.columns.find(profile=>profile.column===column).role))return [];const rows=dataset.rows.filter(row=>ReviewPageEngine.whitespaceTypes(row[column]).length);return rows.length?[{column,reviewType:"whitespace",type:"Hidden spaces & characters",label:"Hidden spaces & characters",rows,recommendation:"manual",severity:"medium",summary:"Invisible representation differences can break grouping and joins.",status:"open",unit:"cells"}]:[];});}
  function init(issue,session){if(session.locked===null)session.locked=types.filter(type=>state.rows.some(row=>ReviewPageEngine.whitespaceTypes(row[issue.column]).includes(type)));}
  function lockedRows(issue,session){init(issue,session);return state.rows.filter(row=>ReviewPageEngine.whitespaceTypes(row[issue.column]).some(type=>session.locked.includes(type)));}
  function count(issue){return issue.rows.length;}
  function hiddenGroups(issue){return ReviewPageEngine.frequencies(state.rows,issue.column,value=>repaired(value)).map(group=>({...group,variants:ReviewPageEngine.frequencies(group.rows,issue.column)})).filter(group=>group.variants.length>1);}
  function getFixOptions(issue,session){return [{key:"clean-all",label:"Clean all locked problems",risk:"Doesn't invent information",compute:()=>({operation:"cleanCharacters",characterTypes:session.locked})},{key:"trim",label:"Trim ends",risk:"Doesn't invent information",compute:()=>({operation:"trimEnds"})},{key:"collapse-spaces",label:"Single spaces",risk:"Doesn't invent information",compute:()=>({operation:"collapseSpaces"})},{key:"remove-hidden",label:"Remove invisible characters",risk:"Doesn't invent information",compute:()=>({operation:"stripInvisible"})},{key:"fix-encoding",label:"Repair encoding",risk:"Estimates values",more:true,compute:()=>({operation:"fixEncoding"})},{key:"keep",label:"Keep as is",risk:"Doesn't change values",more:true,compute:()=>({operation:"retain",interpretation:"legitimate"})}];}
  function reminder(issue,session){return `Fixing: ${session.locked.join(" + ")} in ${issue.column} · ${lockedRows(issue,session).length} cells`;}
  function consequence(issue,session,preview){ // WS-F-01: describe actual scoped merges, not potential merges from unchosen repairs.
    const old=new Set(state.rows.map(row=>row[issue.column])).size,next=new Set(preview.after.map(row=>row[issue.column])).size,source=new Map(state.rows.map(row=>[row._row,row[issue.column]])),merge=ReviewPageEngine.frequencies(preview.after,issue.column).map(group=>({...group,variants:[...new Set(group.rows.map(row=>source.get(row._row)))]})).find(group=>group.variants.length>1);
    return {sentence:`${preview.patches.length} cells cleaned · ${issue.column} groups ${old} → ${next}${merge?` (“${visible(merge.variants[0])}” and “${visible(merge.variants[1])}” merge: ${merge.rows.length} rows join “${visible(merge.value)}”)`:""}.`,figures:[{label:"Distinct groups",before:old,after:next}],reason:"Restores readable representations; no real group or person is assigned."};}
  async function aiExplore(issue,session) { // WS-A-01: requested only for ambiguous encoding repairs.
    const candidates=state.rows.filter(row=>ReviewPageEngine.whitespaceTypes(row[issue.column]).includes("broken encoding"));
    if(!candidates.length)return;
    return ReviewCore.requestAi(issue,"explore",{column:issue.column,type:"whitespace",role:"text",headers:state.headers,meaning:columnPolicy(issue.column).meaning,allowedFixes:["fix-encoding","keep"],count:state.rows.length,affected:candidates.length,values:ReviewPageEngine.frequencies(candidates,issue.column).slice(0,20).map(group=>({value:group.value,count:group.rows.length,locked:true})),samples:candidates.slice(0,20).map(row=>repaired(row[issue.column])),statistics:{},groups:[]});
  }
  function bind(issue,session){document.querySelectorAll("[data-whitespace-type]").forEach(input=>input.onchange=()=>{const before=lockedRows(issue,session).length,type=input.dataset.whitespaceType;session.locked=input.checked?session.locked.concat(type):session.locked.filter(value=>value!==type);ReviewCore.lockChanged(issue,before);renderPreservingReviewFocus();});}
  function exploreContent(issue,session){ // WS-E-01…04 / C3 marked values, C2 implication, C4 examples.
    init(issue,session);const c=ReviewComponents,items=types.flatMap(type=>{const rows=state.rows.filter(row=>ReviewPageEngine.whitespaceTypes(row[issue.column]).includes(type));return rows.length?[{value:type,raw:false,count:rows.length,share:`${(rows.length/state.rows.length*100).toFixed(1)}%`,control:`<input type="checkbox" data-whitespace-type="${escapeHtml(type)}" ${session.locked.includes(type)?"checked":""}>`,extra:`<span>${escapeHtml(rows.slice(0,3).map(row=>type==="broken encoding"?`${visible(row[issue.column])} → ${visible(repaired(row[issue.column]))}`:visible(row[issue.column])).join(" · "))}</span>`,ui:"review.explore.whitespace.type",attrs:{"data-type":type},meta:"changes matching and grouping"}]:[];});
    const merges=hiddenGroups(issue),rows=lockedRows(issue,session).slice(0,5).map(row=>({row:row._row,before:{value:visible(row[issue.column]),raw:true,problem:true},after:{value:visible(repaired(row[issue.column])),raw:true}}));
    return {lead:`Which hidden characters in ${issue.column} should be cleaned?`,sub:`${count(issue)} values may split matching names into separate groups.`,selection:c.selection(items,{ui:"review.explore.whitespace.types",total:`${lockedRows(issue,session).length} values selected`}),evidence:c.headline(merges.length?`${merges.length} groups contain names that become identical after cleaning; check whether they should merge.`:"No additional matching names were found after cleaning.")+c.table({columns:[{key:"row",label:"Row",numeric:true},{key:"before",label:"Visible source characters"},{key:"after",label:"Repaired example"}],rows,ui:"review.explore.whitespace.impact"})};
  }
  function fixContent(issue,session,preview){ // WS-F-02 / C6 pairs with visible characters.
    return {examples:ReviewComponents.table({columns:[{key:"row",label:"Row",numeric:true},{key:"before",label:"Before"},{key:"after",label:"After"}],rows:preview.patches.slice(0,5).map(patch=>({row:patch.rowId,before:{value:visible(patch.before),raw:true},after:{value:visible(patch.after),raw:true}})),card:false,empty:"No characters change for this method."})};
  }
  function reviewContent(issue,decision){ // WS-R-01…03 / no redundant chart.
    const a=decision.reviewImpact.beforeRows,b=decision.reviewImpact.afterRows;
    return {lead:`${decision.patches.length} values cleaned in ${issue.column}.`,sub:`${decision.reviewSpec.label} · ${new Date(decision.createdAt).toLocaleTimeString()} · ${decision.note||"No note"}`,count:decision.rows.length,change:{metrics:[{label:"Values cleaned",value:decision.patches.length},{label:"Distinct values",value:`${new Set(a.map(row=>row[issue.column])).size} → ${new Set(b.map(row=>row[issue.column])).size}`}],text:consequence(issue,{}, {after:b,patches:decision.patches}).sentence},examples:fixContent(issue,{}, {patches:decision.patches}).examples};
  }
  return {detect,init,count,unit:"cells",lockedRows,exploreContent,fixContent,reviewContent,renderExplore:(issue,session)=>ReviewComponents.explore(issue,exploreContent(issue,session)),getFixOptions,reminder,consequence,aiExplore,bind};
})();
