const assert = require("node:assert/strict");
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || "/tmp/opencode/node_modules/playwright");
const fs=require("node:fs");
const base=process.env.BASE_URL || "http://localhost:4174", artifacts=process.env.ARTIFACT_DIR || "docs/screenshots/review-spec/01-missing";
(async()=>{
  fs.mkdirSync(artifacts,{recursive:true});const browser=await chromium.launch({ignoreDefaultArgs:["--disable-dev-shm-usage"]});
  try { for(const width of [1440,390]) {
    const page=await browser.newPage({viewport:{width,height:900}}),errors=[],requests=[];page.on("pageerror",error=>errors.push(error.message));
    await page.route("**/api/ai/**",route=>{if(route.request().method()==="GET")return route.fulfill({json:{available:false,turnstileSiteKey:""}});const payload=route.request().postDataJSON();requests.push(payload);if(!route.request().url().endsWith("/review"))return route.fulfill({status:503,json:{error:"not configured"}});return route.fulfill({json:{provider:"mock",result:{note:"NULL probably represents a missing observation. Zero is plausible and should remain observed.",assessments:payload.context.values.map(value=>({value:value.value,confidence:!value.value || value.value==="NULL"?95:30,reason:"Review this exact representation."})),locks:payload.context.values.filter(value=>!value.value || value.value==="NULL").map(value=>value.value)}}});});
    await page.goto(`${base}/?debug=ui`);await page.waitForFunction(()=>typeof ReviewCore!=="undefined"&&typeof loadData==="function");
    const load=async()=>page.evaluate(async()=>{loadData(await(await fetch("sales_orders.csv")).text(),"sales_orders.csv");cancelAutomaticReview(false);});
    const select=column=>page.evaluate(column=>ReviewCore.select(state.issues.find(issue=>issue.column===column&&issue.reviewType==="missing").id),column);
    const ready=()=>page.waitForFunction(()=>!ReviewCore.data(ReviewCore.current()).pending && Boolean(ReviewCore.data(ReviewCore.current()).preview));
    const capture=async name=>{assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name}: no page overflow`);if(width===1440)assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),`${name}: one desktop screen`);await page.screenshot({path:`${artifacts}/${name}-${width}.png`,fullPage:true});};
    await load();await select("sales_rep");assert.equal(await page.locator('[data-ui="review.explore.missing.value"]').count(),1);assert.match(await page.locator('[data-ui="review.explore.missing.only-blanks"]').innerText(),/32, 3.2%/);assert.equal(requests.length,0,"MISS-T-01 no blank-only AI request");await capture("sales-rep-explore");
    await page.locator("#reviewTab-fix").click();await ready();assert.equal(await page.locator('[data-fix="constant"]').getAttribute("aria-pressed"),"true");assert.match(await page.locator('[data-ui="review.fix.risk"]').innerText(),/Doesn't invent information/);assert.equal(await page.locator('[data-ui="review.fix.preview"] svg').count(),0);await capture("sales-rep-fix");
    await page.locator("#reviewMore").selectOption("mode");await ready();assert.match(await page.locator('[data-ui="review.fix.risk"]').innerText(),/Invents information/);assert.match(await page.locator('[data-ui="review.fix.consequence"]').innerText(),/REP-/);await page.locator("#reviewApply").click();assert.ok(await page.locator('[data-ui="review.review.metrics"]').isVisible());await capture("sales-rep-review");await page.locator("#reviewUndo").click();assert.equal(await page.evaluate(()=>metrics().changedCells),0);
    await select("delivery_days");const sourceOrder=await page.evaluate(()=>state.rows.map(row=>row._row));await page.locator("#missingAddOrder").selectOption("channel");await page.locator("#missingAllRows").click();assert.equal(await page.locator('[data-ui="review.explore.missing.sheet"] table').count(),1);assert.equal(await page.locator('.priority-table tbody tr').count(),1000);assert.equal(await page.locator('.priority-table td.locked-gap').count(),86);const channels=await page.evaluate(()=>ReviewModules.missing.inspectionRows(ReviewCore.current(),ReviewCore.data(ReviewCore.current())).map(row=>row.channel));assert.deepEqual(channels,[...channels].sort((a,b)=>a.localeCompare(b)));assert.deepEqual(await page.evaluate(()=>state.rows.map(row=>row._row)),sourceOrder);assert.deepEqual(await page.evaluate(()=>ReviewCore.data(ReviewCore.current()).locks),[]);await capture("delivery-explore");
    await page.locator("#reviewTab-fix").click();await ready();await page.locator('.missing-fill-groups > summary').click();await page.locator("#missingAddLock").selectOption("channel");await ready();await page.locator('[data-fix="median-by-group"]').click();await ready();assert.match(await page.locator('[data-ui="review.fix.consequence"]').innerText(),/Distributor 4.3/);assert.match(await page.locator('[data-ui="review.fix.consequence"]').innerText(),/Online 4.5/);assert.match(await page.locator('[data-ui="review.fix.preview"]').innerText(),/\+86 filled/);await capture("delivery-fix");await page.locator("#reviewApply").click();assert.match(await page.locator('[data-ui="review.review.metrics"]').innerText(),/86 \(8.6%\) → 0/);await capture("delivery-review");await page.locator("#reviewUndo").click();assert.equal(await page.evaluate(()=>metrics().changedCells),0);
    await select("discount_pct");await page.locator("#reviewTab-fix").click();await ready();await page.locator('[data-fix="constant"]').click();await ready();await page.locator("#missingConstant").fill("0");await page.locator("#missingConstant").dispatchEvent("change");await ready();await page.locator("#missingBlankMeans").check();await ready();assert.match(await page.locator('[data-ui="review.fix.risk"]').innerText(),/Doesn't invent information/);await capture("discount-fix");
    await page.locator("#reviewTab-explore").click();const zero=page.locator('[data-ui="review.explore.missing.value"]').filter({has:page.locator("code",{hasText:"0.0"})});if(await zero.count())await zero.first().click();await page.locator("#reviewTab-fix").click();await ready();assert.equal(await page.locator('[data-fix="constant"]').getAttribute("aria-pressed"),"true");assert.match(await page.locator(".review-update").innerText(),/Updated/);await page.locator("#reviewApply").click();await capture("discount-review");await page.locator("#reviewUndo").click();assert.equal(await page.evaluate(()=>metrics().changedCells),0);
    await select("customer_tenure_months");await page.locator("#reviewTab-fix").click();await ready();const medians=await page.evaluate(()=>{const issue=ReviewCore.current(),selected=new Set(ReviewCore.affected(issue).map(row=>row._row)),values=state.rows.filter(row=>!selected.has(row._row)).flatMap(row=>{try{return [CleaningEngine.parseNumber(row[issue.column])];}catch{return [];}});return {expected:CleaningEngine.stats(values).median,actual:[...new Set(ReviewCore.data(issue).preview.patches.map(patch=>Number(patch.after)))]};});assert.deepEqual(medians.actual,[medians.expected]);const integerText=await page.locator('[data-ui="review.fix.consequence"]').innerText();assert.ok(!/\b\d+\.\d{2,}\b/.test(integerText.replace(/\$[\d,.]+/g,"money")),"MISS-T-07 integers do not show raw float precision");await capture("tenure-fix");
    await page.evaluate(()=>{const csv="id,amount,region\n"+Array.from({length:80},(_,index)=>`${index+1},${index<10?"NULL":index<20?"0":String(10+index%4)},${index%2?"North":"South"}`).join("\n");loadData(csv,"NULL-and-zero-fixture.csv");cancelAutomaticReview(false);ReviewCore.select(state.issues.find(issue=>issue.column==="amount"&&issue.reviewType==="missing").id);});await page.waitForFunction(()=>ReviewCore.data(ReviewCore.current()).aiStatus==="ready");assert.match(await page.locator('[data-ui="review.explore.missing.values"]').innerText(),/AI 95%/);assert.match(await page.locator('[data-ui="review.explore.missing.values"]').innerText(),/AI 30%/);await page.locator("#missingAiPicks").click();assert.equal(await page.evaluate(()=>ReviewCore.affected(ReviewCore.current()).length),10);await page.locator("#reviewTab-fix").click();await ready();assert.match(await page.locator('[data-ui="review.fix.reminder"]').innerText(),/NULL/);
    assert.deepEqual(errors,[]);await page.close();console.log(`CORE/MISS acceptance paths passed at ${width}px`);
  }}finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
