// Direct browser evidence for the five archived Review critique priorities and the blue + interaction.
const assert=require("node:assert/strict"),fs=require("node:fs");
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||"/tmp/opencode/node_modules/playwright");
const base=process.env.BASE_URL||"http://localhost:4174",folder=process.env.ARTIFACT_DIR||"/tmp/opencode/review-clarity";
(async()=>{
  fs.mkdirSync(folder,{recursive:true});const browser=await chromium.launch();
  try{for(const width of [1440,390]){
    const page=await browser.newPage({viewport:{width,height:900},hasTouch:width===390}),errors=[];
    page.on("pageerror",error=>errors.push(error.stack));
    await page.route("**/api/ai/**",route=>route.fulfill({status:route.request().method()==="POST"?503:200,json:{available:false,turnstileSiteKey:"",error:"AI unavailable"}}));
    await page.goto(base);
    const ready=()=>page.waitForFunction(()=>!ReviewCore.data(ReviewCore.current()).pending&&Boolean(ReviewCore.data(ReviewCore.current()).preview));
    const capture=async name=>{if(process.env.CAPTURE!=="0"){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`${folder}/${name}-${width}.png`,fullPage:true});}};
    const sample=()=>page.evaluate(async()=>{loadData(await(await fetch("sales_orders.csv")).text(),"sales_orders.csv");cancelAutomaticReview(false);});
    const select=column=>page.evaluate(column=>ReviewCore.select(state.issues.find(issue=>issue.column===column&&issue.reviewType==="missing").id),column);
    await sample();await select("revenue_usd");
    const counts=await page.evaluate(()=>({candidates:ReviewModules.missing.remainingCandidates(ReviewCore.current()).length,selected:ReviewCore.affected(ReviewCore.current()).length}));
    assert.ok(counts.candidates>0);assert.equal(counts.selected,0);
    assert.match(await page.locator('[data-ui="review.issue-header"]').innerText(),new RegExp(`${counts.candidates} candidate cells? · 0 selected`));
    assert.equal(await page.locator('[data-review-issue][data-column="revenue_usd"][data-issue="missing"] b').textContent(),String(counts.candidates));
    assert.ok(await page.locator("#reviewTabHelp").isVisible());
    await capture("unselected-candidates");
    await select("delivery_days");
    await page.waitForFunction(()=>{const session=ReviewCore.data(ReviewCore.current());return Boolean(session.compareKey)&&!session.comparePending&&session.aiStatus!=="pending";});
    assert.equal(await page.locator("#missingAddOrder").isVisible(),false);
    const add=page.locator("#missingOrderAdd");
    assert.equal(await add.evaluate(node=>getComputedStyle(node).backgroundColor),"rgb(36, 91, 197)");
    if(width===390)await add.tap();else await add.click();
    assert.ok(await page.locator("#missingAddOrder").isVisible());
    await page.locator("#missingAddOrder").selectOption("channel");
    assert.equal(await page.locator("#missingAddOrder").isVisible(),false);
    await add.click();await page.locator("#missingAddOrder").selectOption("quantity");
    assert.equal(await page.locator('[data-ui="review.explore.missing.priority"]').count(),2);
    assert.ok(!(await page.locator('.priority-toolbar').innerText()).includes("Then by"));
    assert.deepEqual(await page.evaluate(()=>ReviewCore.data(ReviewCore.current()).locks),[]);
    await capture("blue-add-priorities");
    await page.locator("#reviewTab-fix").click();await ready();
    assert.ok(await page.locator("#reviewMethodHelp").isVisible());
    assert.equal(await page.locator('[data-fix="median-by-group"]').getAttribute("aria-describedby"),"reviewMethodHelp");
    assert.match(await page.locator('[data-ui="review.fix.consequence"]').innerText(),/Sum of unit_price_usd for these 86 selected rows/);
    assert.equal(await page.locator('[data-ui="review.fix.options"] #reviewAskAi').count(),0);
    assert.ok(await page.locator('.review-fix-footer #reviewAskAi').isVisible());
    await page.locator("#reviewRows").click();
    assert.equal(await page.locator('.review-row-panel').evaluate(node=>node.tagName),"DIALOG");
    for(let i=0;i<4;i++){await page.keyboard.press("Tab");assert.ok(await page.evaluate(()=>document.querySelector('.review-row-panel').contains(document.activeElement)));}
    await page.keyboard.press("Escape");await page.waitForFunction(()=>document.activeElement.id==="reviewRows");
    await page.locator("#reviewRows").click();await page.locator("#reviewCloseRows").click();await page.waitForFunction(()=>document.activeElement.id==="reviewRows");
    await page.locator('.review-impact-setting > summary').click();
    const source=await page.evaluate(()=>csvText());
    await page.locator("#reviewImpactMetric").selectOption("revenue_usd");await ready();
    assert.equal(await page.evaluate(()=>csvText()),source,"Metric choice cannot execute a treatment");
    assert.match(await page.locator('[data-ui="review.fix.consequence"]').innerText(),/Sum of revenue_usd/);
    await page.locator("#reviewChooseFillGroups").click();assert.ok(await page.locator("#missingAddLock").isVisible());
    await page.locator("#missingAddLock").selectOption("channel");await ready();
    await page.locator('[data-fix="median-by-group"]').click();await ready();
    await page.locator('.missing-fill-groups > summary').click();
    if(width===390){for(const selector of ["#reviewTab-explore","#reviewTab-fix","#reviewTab-review","#reviewApply","#reviewRows","#reviewAddNote","#reviewAskAi"]){const size=await page.locator(selector).evaluate(node=>({w:node.getBoundingClientRect().width,h:node.getBoundingClientRect().height}));assert.ok(size.h>=44&&size.w>=44,`${selector} is a 44px touch target`);}}
    await capture("fix-clear-impact");
    await page.locator("#reviewApply").click();
    assert.equal(await page.locator('.review-primary-metrics > div').count(),2);
    assert.equal(await page.locator('.review-decision-details').evaluate(node=>node.open),false);
    assert.match(await page.locator('.review-outcome').innerText(),/86 cells filled/);
    const remaining=await page.evaluate(()=>ReviewModules.missing.remainingCandidates(ReviewCore.current()).length);
    assert.ok(remaining>0);assert.match(await page.locator('.review-outcome').innerText(),new RegExp(`${remaining} candidate cells still need review`));
    await capture("review-outcome");
    await page.locator('.review-decision-details > summary').click();assert.match(await page.locator('[data-ui="review.review.metrics"]').innerText(),/Median|Rows removed|Columns added/);
    await page.locator("#reviewRemainingCandidates").click();assert.equal(await page.locator("#reviewTab-explore").getAttribute("aria-selected"),"true");
    await page.locator("#reviewTab-review").click();await page.locator("#reviewUndo").click();assert.equal(await page.evaluate(()=>metrics().changedCells),0);
    await page.evaluate(()=>{loadData("id,contact\n1,jane@example.com\n2,bob@example.com","private.csv");cancelAutomaticReview(false);ReviewCore.select(state.issues.find(issue=>issue.reviewType==="sensitive").id);});
    await page.locator("#reviewTab-fix").click();await ready();await page.locator('[data-fix="keep"]').click();await ready();
    assert.equal(await page.locator("#reviewApply").isDisabled(),true);assert.match(await page.locator("#reviewApplyReason").innerText(),/Add a note/);
    await page.locator("#reviewRows").click();assert.ok(!(await page.locator('.review-row-panel').innerText()).includes("jane@example.com"));await page.keyboard.press("Escape");await page.waitForFunction(()=>document.activeElement.id==="reviewRows");
    const main=await page.locator('.review-main').elementHandle();
    await page.setViewportSize({width,height:850});await page.waitForTimeout(150);assert.equal(await main.evaluate(node=>node.isConnected),true,"Height-only resize preserves focused controls and drag nodes");
    await page.setViewportSize({width:width+10,height:850});await page.waitForTimeout(150);assert.equal(await main.evaluate(node=>node.isConnected),false,"Width changes still recompose chart geometry");
    assert.deepEqual(errors,[]);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    await page.close();console.log(`Review critique priorities and blue + passed at ${width}px`);
  }}finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
